from aiortc import RTCIceServer


DATA_CHANNEL_LABEL = "gpstation.v1"
DEFAULT_RTC_ICE_SERVERS = (RTCIceServer(urls="stun:stun.l.google.com:19302"),)

ATTACHMENT_CHUNK_SIZE = 16 * 1024
BUFFERED_AMOUNT_HIGH_WATER_MARK = 512 * 1024
BUFFERED_AMOUNT_LOW_THRESHOLD = 128 * 1024
BUFFERED_AMOUNT_DRAIN_TIMEOUT_SECONDS = 30.0
PEER_CLOSE_TIMEOUT_SECONDS = 5.0
