import type { CatalogSearchItem } from '@/api/catalog'
import { cadElementCatalog } from '@/lib/cad'
import { CALCULATION_MATHJS_REFERENCE, CALCULATION_SOURCE_SKELETON } from '@/lib/calculation'
import { docsSectionHref, type DocsSectionId } from './docsRoute'

export type DocsKnowledgeChunk = Readonly<{
  aliases?: readonly string[]
  anchor?: string
  collapsed?: boolean
  content: string
  href: string
  id: string
  item?: string
  keywords: readonly string[]
  section: DocsSectionId
  summary: string
  title: string
}>

function manualChunk(
  chunk: Omit<DocsKnowledgeChunk, 'href'> & {
    section: 'workbench' | 'program' | 'reference' | 'troubleshooting'
  },
): DocsKnowledgeChunk {
  return Object.freeze({ ...chunk, href: docsSectionHref(chunk.section, undefined, chunk.anchor) })
}

export const manualDocsKnowledge: readonly DocsKnowledgeChunk[] = Object.freeze([
  manualChunk({
    id: 'workbench-quickstart',
    section: 'workbench',
    anchor: 'workbench-quickstart',
    title: 'CAE Workbench 빠른 시작',
    summary: 'Experiment candidate를 준비하고 Measurement로 고정한 뒤 실행하는 전체 흐름입니다.',
    keywords: ['Quickstart', '시작', 'Candidate', 'Measurement', 'Prepared', 'Recorded', 'Launcher', 'Ready'],
    content: [
      'Caemble의 Experiment는 공통 형상과 변수, Material, solver Task, 실행 프로그램과 RecordedData 계약을 하나의 source bundle로 관리합니다.',
      '',
      '1. 로그인하고 CAE Launcher가 연결되어 있는지 확인합니다.',
      '2. 상단 **Experiment** 메뉴를 선택하고 왼쪽 목록에서 Example 또는 저장된 namespace / repository / SemVer Version을 연 뒤, 오른쪽 Source 탭에서 source bundle을 작성합니다.',
      '3. source 상태가 `Ready`가 될 때까지 compile/evaluate 오류를 해결합니다.',
      '4. **Generate Candidate**로 `varsSchema` 범위의 새 변수 조건과 frozen Material 값을 미리 봅니다.',
      '5. 원하는 조건이면 **Save Current Measurement**로 변수와 Material snapshot을 고정합니다. 이 단계는 solver를 실행하지 않습니다.',
      '6. 상단 **Calculation** 메뉴의 왼쪽 점 배열에서 prepared Measurement를 선택합니다. Ctrl/Cmd+클릭으로 여러 항목을 선택하고 Shift+클릭으로 현재 페이지의 범위를 선택할 수 있습니다.',
      '7. **Generate & Run**은 클릭할 때마다 새 Candidate를 생성하고 새 Measurement로 저장한 뒤 즉시 실행합니다. Candidate 생성이나 저장 단계는 취소할 수 없고, Simulation이 시작된 뒤에는 Cancel할 수 있습니다.',
      '8. 횟수를 입력하고 **Repeat Run**을 누르면 Generate & Run 파이프라인을 순차적으로 N회 시도합니다. 기본값은 10이며, N은 성공 횟수가 아니라 전체 시도 횟수입니다.',
      '9. Repeat Run은 Candidate 평가, Measurement 준비 또는 Simulation이 실패한 시도를 집계하고 다음 시도를 계속합니다. 결과 저장 실패나 명시적 Cancel은 남은 반복을 중단하며, 저장 실패 결과는 **Retry Saving Results**로 다시 저장할 수 있습니다.',
      '10. 기존 prepared Measurement를 실행하려면 **Run Selected**를 사용합니다. Generate & Run 실행이 실패하거나 취소되어도 새 Measurement는 Prepared 상태로 남습니다.',
      '11. 성공하면 RecordedData가 원자적으로 기록되고 Measurement는 Recorded 상태가 됩니다. 결과 저장만 실패하면 세션 결과를 유지한 채 **Retry Saving Results**로 저장을 다시 시도합니다.',
      '',
      'Measurement는 immutable Experiment revision을 가리킵니다. 생성 요청의 source hash가 현재 revision과 다르면 저장이 거부되므로, source가 바뀌면 새 revision에서 새 Measurement를 준비하세요.',
      '',
      'Task 파일이 하나도 없는 Experiment도 Geometry preview와 Experiment 저장은 사용할 수 있습니다. 이 경우 Measurement 생성·선택·분석과 Simulation 실행은 Task를 추가할 때까지 비활성화됩니다.',
    ].join('\n'),
  }),
  manualChunk({
    id: 'workbench-authoring-cycle',
    section: 'workbench',
    anchor: 'workbench-authoring-cycle',
    title: '편집, Candidate 생성과 실행 결과의 관계',
    summary: 'source 수정과 candidate 생성이 prepared·recorded Measurement에 미치는 영향을 설명합니다.',
    keywords: [
      'Dirty',
      'Checking',
      'Compiling',
      'Evaluating',
      'Resolving Materials',
      'Candidate',
      'Prepared',
      'Recorded',
    ],
    content: [
      'Source를 수정하면 `Dirty → Checking → Compiling → Evaluating → Resolving Materials → Ready` 순서로 검증됩니다. `Error`가 보이면 가장 먼저 diagnostics의 파일명과 line을 확인합니다.',
      '',
      '- **Source 수정**은 새 revision을 compile합니다.',
      '- **Generate Candidate**는 source를 바꾸지 않고 완전한 새 vars를 생성해 preview합니다.',
      '- Calculation의 **Vars** 패널에서는 현재 Candidate의 `varsSchema` key를 선택해 scalar·1-D 막대 또는 2-D/N-D heatmap으로 값을 직접 편집할 수 있습니다. 편집값은 Viewer에 다시 평가되며 schema의 min/max를 벗어날 수 없습니다.',
      '- Candidate는 저장 전까지 임시 상태이며 provenance나 seed 계약이 아닙니다.',
      '- **Save Current Measurement**는 현재 vars와 Material snapshot을 고정하지만 solver를 실행하지 않습니다.',
      '- **Save & Run**은 화면의 현재 수동 Candidate를 새 Prepared Measurement로 저장한 뒤 그대로 실행합니다. **Generate & Run**과 달리 새 무작위 Candidate를 만들지 않습니다.',
      '- 선택한 prepared Measurement만 실행할 수 있고, Recorded 상태가 된 Measurement는 다시 실행할 수 없습니다.',
      '',
      '새 조건으로 다시 계산하려면 기존 Measurement를 덮어쓰지 말고 새 Candidate를 생성한 뒤 새 Measurement로 저장하세요.',
    ].join('\n'),
  }),
  manualChunk({
    id: 'workbench-calculation',
    section: 'workbench',
    anchor: 'workbench-calculation',
    title: 'Calculation으로 RecordedData 후처리',
    summary:
      '선택한 Measurement의 RecordedData를 JavaScript와 Math.js로 계산하고 scalar, line, heatmap으로 확인합니다.',
    keywords: [
      'Calculation',
      'Vars',
      'Candidate',
      'RecordedData',
      'Math.js',
      'mathjs',
      'Output',
      'scalar',
      'line',
      'heatmap',
    ],
    content: [
      '상단 **Calculation** 메뉴는 왼쪽부터 Measurements/Vars·Experiment Records & RecordedData·Calculation 목록, 3D Viewer, Source Editor, Output Chart를 표시합니다. 첫 패널의 **Measurements / Vars** 탭은 현재 화면 세션 동안 선택을 유지합니다. 가운데 통합 카탈로그에는 Experiment가 선언한 모든 ExperimentRecord가 표시되며 **Used**는 현재 source가 참조하는 Record, **RecordedData Ready/Missing/Invalid**는 선택 Measurement의 실제 값 상태를 뜻합니다. 이름으로 검색할 수 있고 각 행의 **Insert**를 누르면 현재 Source Editor selection에 `record["group.signal"]` 형식의 고정-key 참조를 삽입합니다. 행 자체를 누르는 것은 source를 변경하지 않습니다. 3D Viewer 아래에는 공통 AI Agent/Console 도크가 있으며 Calculation의 `console.log`와 실행 오류도 이 Console에 누적됩니다. 우측 열은 Output Chart와 Return 요약을 기본 65/35로 나눕니다. 열 경계, 왼쪽 세 영역, 하단 도크와 Chart/Return 경계는 드래그하거나 키보드 방향키로 조절하며 마지막 Workbench draft에 저장됩니다. Viewer를 확장하면 왼쪽 목록과 Viewer 열을 합쳐 full height Viewer로 사용하고, Source Editor와 Output 열은 계속 표시합니다.',
      '',
      '**Vars**는 현재 `varsSchema`의 key를 선언 순서대로 카드에 표시합니다. 별도 팝업 없이 카드를 누르면 그 자리에서 편집기가 펼쳐지며, 한 번에 하나만 열립니다. Candidate 값이 갱신되어도 열린 카드는 유지되고 Experiment 또는 varsSchema가 바뀔 때만 접힙니다. scalar와 1-D Tensor는 schema min/max 고정 축의 막대그래프로, 2-D Tensor는 같은 범위의 heatmap으로 편집합니다. N-D Tensor는 마지막 두 축을 heatmap으로 사용하고 앞 축 index 조합을 8개씩 페이지로 표시합니다. 막대는 클릭·드래그 위치를 따라가며, heatmap은 사각 영역을 드래그한 뒤 휠 또는 직접 입력으로 일괄 변경합니다. 휠 한 notch는 범위의 1%, Shift는 10배, Alt는 0.1배이고 모든 값은 schema min/max 안으로 제한됩니다.',
      '',
      'Vars를 바꾸면 기존 scene 평가를 취소하고 최신 Candidate로 다시 평가해 Viewer를 갱신합니다. 저장된 Measurement를 편집한 경우 원본 Measurement를 수정하지 않고 선택을 해제한 새 editable Candidate가 되며 기존 Material snapshot은 유지됩니다. **Save Current**는 이를 새 Prepared Measurement로 저장하고, **Save & Run**은 저장 후 같은 vars로 즉시 실행합니다. 저장이 완료된 뒤 평가나 실행이 실패해도 Prepared Measurement는 남으며 Simulation 시작 후에는 Cancel할 수 있습니다.',
      '',
      'Calculation 리본의 **Save**를 누르면 이름과 설명을 입력하는 저장 모달이 열리고 현재 source와 함께 명시적으로 저장합니다. 새 Calculation, source가 바뀐 Calculation, 기존의 미계약 Calculation은 선택한 Recorded Measurement에서 최신 preview가 성공해야 저장할 수 있습니다. 저장 시 source hash, 정적으로 확인한 ExperimentRecord dependency, preflight Measurement와 Output의 dtype·정확한 shape·axes가 하나의 고정 계약으로 기록됩니다. 이름이나 설명만 바뀌고 source hash가 같으면 기존 계약을 재사용합니다. 저장하지 않은 source도 선택 Measurement에 대해 500ms 뒤 자동 실행하지만 Output은 DB에 저장하지 않습니다.',
      'Calculation 리본의 **Calculation Data** 그룹에서는 **Selected Calc**로 선택 Calculation과 모든 미저장 Recorded Measurement를, **Selected Measurement**로 현재 Measurement와 모든 저장 Calculation을, **All Missing**으로 전체 미저장 조합을 순차 계산해 저장합니다. 진행 중에는 완료 수와 현재 대상을 표시하며 **Cancel Data**로 남은 작업을 취소할 수 있습니다. 이미 저장된 성공 결과는 취소나 일부 실패가 발생해도 유지됩니다.',
      'Calculation 탭의 Measurement 점은 **회색=Run 전**, **노란색=Recorded이지만 Calculation 미완료**, **초록색=모든 저장 Calculation 완료**를 뜻합니다. 점의 tooltip과 접근성 label에는 `완료 수/전체 수`가 표시됩니다. 저장된 Calculation이 하나도 없으면 Recorded Measurement는 `0/0 완료`이므로 초록색입니다. Calculation 목록을 확인하는 중이거나 조회에 실패하면 Recorded 점은 중립색으로 표시됩니다.',
      '**Save & Run**, **Generate & Run**, **Repeat Run**, 기존 Measurement의 **Run**, **Retry Save**는 RecordedData 저장 뒤 해당 Experiment의 모든 저장 CalculationData까지 자동으로 계산합니다. 일부 Calculation이 실패하면 나머지는 계속되지만 해당 시도는 부분 실패로 집계되고 상세 대상과 오류는 Console에 남습니다. 저장된 Calculation이 없으면 이 단계는 즉시 완료됩니다.',
      '저장된 Calculation source를 변경하면 이전 source로 만든 CalculationData는 자동 삭제되어 다시 미저장 상태가 됩니다. 이름이나 설명만 바꾼 경우에는 유지됩니다. 미저장 또는 수정 중인 draft는 일괄 계산 대상이 아닙니다.',
      '현재 Output이 scalar이면 다른 Measurement에 저장된 같은 CalculationData를 Histogram으로 표시하고 현재 선택 Measurement의 최신 preview 위치를 주황색 marker로 겹쳐 표시합니다. 새 Calculation이나 수정 중인 draft에서는 서로 다른 source 결과를 섞지 않도록 Histogram을 숨깁니다.',
      '',
      'Calculation 탭에서 하단 **AI Agent**를 열면 현재 Calculation #id 또는 New draft가 편집 대상으로 표시됩니다. Agent 변경은 `sourceCode`에만 미저장 dirty draft로 반영되며 이름·설명, Output과 DB row는 변경하지 않습니다. Source Editor 위의 **AI 미검증** strip에서 JavaScript diff와 변경 줄 수를 확인하거나 전체 Undo할 수 있습니다. 실행 중 source, Calculation target 또는 Experiment reference가 바뀌면 자동 적용하지 않고 **AI staged** 충돌 diff만 보존합니다.',
      '',
      'Agent에는 현재 source, 선택 Measurement ID, 전체 ExperimentRecord 계약과 각 Record의 Used/선택 Measurement 상태, dependency RecordedData의 path/dtype/shape/axis tick 앞뒤 표본/QuantityKind/tensorOrder/unit/유효성, 최신 preview의 상태·오류 또는 Output 표본만 전달됩니다. 전체 RecordedData 값은 자동 전송하지 않으며 context가 32 KiB를 넘으면 사용하지 않는 ExperimentRecord부터 생략하고 생략 수를 함께 전달합니다. 필요한 경우 Agent가 Measurement detail에서 RecordedData ID를 확인한 뒤 bounded slice 도구로 일부 값만 읽습니다. Agent가 source를 작성해도 compile·실행 검증을 수행했다고 간주하지 않으며, 브라우저의 500ms preview와 Console을 확인한 뒤 리본 **Save**로 명시적으로 저장하세요.',
      '',
      "Source는 순수 JavaScript의 동기 `default export` 함수 하나여야 합니다. TypeScript 문법과 JSX는 허용하지 않으며, package import는 `mathjs`의 named import만 허용합니다. Editor는 허용된 Math.js 함수 signature를 안내하고 입력과 Output 계약은 실행 과정에서 검증합니다. 디버깅에는 frozen console의 `log`만 사용할 수 있으며 `console.log(...)`, `console['log'](...)`, `const log = console.log` 같은 alias를 지원합니다. 다른 console API는 허용하지 않습니다.",
      'Source policy 오류가 발생하면 Editor가 문제가 된 코드를 밑줄로 표시하고 Output Chart와 Console에 줄·열, 거부 이유와 코드 조각을 표시합니다. 자동 preview는 오류 위치로 커서나 스크롤을 이동시키지 않습니다.',
      '',
      '```js',
      ...CALCULATION_SOURCE_SKELETON.trimEnd().split('\n'),
      '```',
      '',
      'Experiment를 저장하면 컴파일된 RecordedData 선언이 dotted path별 **ExperimentRecord** 계약으로 함께 저장됩니다. QuantityKind, tensorOrder, dtype과 data schema는 Measurement마다 복제되지 않고 이 계약에서 제공되며, Measurement의 RecordedData는 ExperimentRecord ID와 실제 tensor 값만 저장합니다. Measurement 조회와 Viewer에서는 join된 metadata를 기존과 같은 형태로 표시합니다.',
      '',
      "Calculation 입력은 ExperimentRecord의 dotted path를 key로 쓰는 읽기 전용 map입니다. `record.signal`, `record['group.signal']`, 정적 object destructuring과 추적 가능한 `const` alias만 dependency로 허용합니다. `record[key]`, `Object.keys/values/entries(record)`, spread, Record 전체 전달·반환, 재할당과 존재하지 않는 key는 정확한 source 위치가 있는 저장 오류입니다. 각 leaf에는 `dtype`, component 차원까지 포함한 전체 `shape`, row-major flat `data`, 외부 `axes`, `quantityKind`, `tensorOrder`, 값 `unit`이 있습니다.",
      'Calculation에 전달되는 axis는 실제 shape와 정확히 맞지만 ticks는 숫자 또는 문자열일 수 있습니다. 기본 템플릿은 원본 axis를 그대로 반환하므로 문자열 ticks는 Output 계약 오류가 됩니다. 필요한 경우 ticks를 숫자로 변환하거나 Output에서 `axes`를 생략해 ordinal axis를 사용하세요.',
      '',
      '### Tensor 연산',
      '',
      'RecordedData의 flat row-major data는 Math.js `reshape`로 원래 tensor shape를 복원할 수 있습니다. 고차원 결과는 마지막 축부터 `mean`을 적용하면 원하는 축만 남길 수 있습니다.',
      '',
      '```js',
      "import { index, map, mean, range, reshape, subset, transpose } from 'mathjs'",
      '',
      'const source = record.signal',
      'const flat = Array.isArray(source.data) ? source.data : [source.data]',
      'let tensor = reshape(flat, source.shape.length > 0 ? source.shape : [1])',
      '',
      '// 첫 두 축만 유지하고 나머지 축을 평균합니다.',
      'for (let axis = source.shape.length - 1; axis >= 2; axis -= 1) {',
      '  tensor = mean(tensor, axis)',
      '}',
      '',
      '// 영역 선택, element-wise 변환, 축 교환',
      'const window = subset(tensor, index(range(0, 10), range(0, 20)))',
      'const doubled = map(window, (value) => value * 2)',
      'const swapped = transpose(doubled)',
      '',
      '// 동적으로 계산한 숫자 index도 일반 bracket 문법으로 읽고 쓸 수 있습니다.',
      'const base = 2',
      'const sample = flat[base]',
      '```',
      '',
      '`reshape`는 shape 변경, `mean`/`sum`은 축약, `subset`과 `index`는 slicing, `map`은 element-wise 변환, `transpose`와 `squeeze`는 축 정리에 사용합니다. 빈 축의 2차원 shape를 유지해야 할 때는 `zeros(rows, columns)`를 반환할 수 있습니다.',
      '',
      '작성하는 Output은 `dtype`, finite real `data`, 선택적인 `axes`만 가집니다. `shape`를 작성하면 오류이며 scalar는 `[]`, flat array는 `[length]`, 직사각 2D array는 `[rows, columns]`, Math.js Matrix는 `size()`에서 자동 추론합니다. axes를 생략하면 `index` 또는 `row`/`column` ordinal ticks를 생성하고, 제공하면 모든 축과 ticks 길이가 추론 shape에 정확히 맞아야 합니다. 성공한 preflight의 dtype·shape·axes는 저장 뒤 강제 계약이 되며 이후 어느 Measurement에서든 하나라도 달라지면 해당 CalculationData만 저장하지 않습니다. Output에는 QuantityKind와 값 unit이 없습니다. rank 0은 scalar, rank 1은 line, rank 2는 heatmap으로 표시합니다.',
      '2차원 heatmap은 tensor의 columns:rows shape 비율을 유지해 각 cell을 정사각형으로 표시하며, Output Chart의 가용 영역과 splitter 조절에 맞춰 확대됩니다. 숫자 축 라벨은 최대 유효숫자 5개로 반올림하지만 hover 좌표와 Return 데이터는 원본 정밀도를 유지합니다.',
      '',
      '### 허용 Math.js API',
      '',
      ...CALCULATION_MATHJS_REFERENCE.map(
        ({ group, names }) => `- **${group}**: ${names.map((name) => `\`${name}\``).join(', ')}`,
      ),
      '',
      '`mathjs` 이외 package, default/namespace/deep/dynamic import, `require`, expression parser와 symbolic API, mutable configuration, BigNumber/Fraction/Unit, random 함수는 허용하지 않습니다. stdlib는 v1에 포함되지 않습니다.',
      "`values[index]` 같은 동적 bracket index는 실행 시 `number`, 0 이상, safe integer인지 검사한 뒤 허용합니다. 문자열·BigInt·NaN·Infinity·음수·소수 index는 source 위치가 포함된 policy 오류가 됩니다. 고정된 `record['path.to.leaf']`는 계속 허용하지만 `record[path]` 같은 동적 문자열 property와 computed object property/method 선언은 차단합니다. `constructor`, `prototype`, `__proto__`, 동적 Math member, random 함수, native `Object`/`Array` alias와 global·network·storage·timer·Worker 접근도 허용하지 않습니다.",
      '',
      '### 오류와 한도',
      '',
      '- 전체 입력은 64 MiB 이하여야 합니다.',
      '- Output은 최대 5,000,000개의 수치 원소를 가질 수 있습니다.',
      '- 한 실행은 최대 30초이며 source, Measurement, Calculation 또는 Experiment가 바뀌면 이전 실행을 취소합니다.',
      '- 명시적인 `shape`, 불완전한 axes, ticks 길이 불일치, 유효하지 않은 UCUM axis unit은 Output 계약 오류입니다.',
      '- `console.log`는 호출당 4 KiB, 실행당 100건·64 KiB로 제한되며 초과분은 한 번의 truncation 경고로 대체됩니다.',
      '- `timeout`은 계산량을 줄이고, `input-too-large`는 필요한 RecordedData만 만드는 Experiment 계약으로 나누고, `output-too-large`는 downsample 또는 aggregate한 rank 0/1/2 결과를 반환해 해결합니다.',
    ].join('\n'),
  }),
  manualChunk({
    id: 'workbench-prediction',
    section: 'workbench',
    anchor: 'workbench-prediction',
    title: 'Prediction으로 Vars와 CalculationData 상호 예측',
    summary:
      '저장된 Measurement의 k-Nearest Neighbor 모델로 Forward·Inverse 예측을 자동 전환하고 Save & Run으로 검증합니다.',
    keywords: [
      'Prediction',
      'Forward',
      'Inverse',
      'kNN',
      'k-Nearest Neighbor',
      'Vars',
      'RecordedData',
      'CalculationData',
      'Save & Run',
      'Validation',
    ],
    content: [
      '파라미터 없이 Workbench를 열면 **Prediction**에서 시작합니다. 왼쪽 위 Experiment 선택기는 로그인 사용자의 **내 Experiment**를 먼저, 큐레이션된 **Demo**를 다음에 표시합니다. 비로그인 사용자는 대표 Demo가 자동으로 열리며 `?experiment=…&section=prediction` URL을 그대로 공유할 수 있습니다.',
      '',
      '상단 **Prediction** 메뉴는 현재 Experiment의 저장된 Recorded Measurement를 학습 데이터로 사용합니다. 왼쪽 **Vars**와 오른쪽 **Calculation Data** 사이의 중앙 3D Viewer 및 하단 AI Agent/Console은 다른 Workbench와 같은 상태로 유지됩니다. Demo 표시는 원본 source와 데이터를 수정할 수 없다는 뜻이며, Vars와 Target 조작은 로컬 Candidate에만 적용됩니다.',
      '',
      '공개 Demo에서는 로그인하지 않아도 Forward Prediction, Inverse Design, Calculation 데이터 탐색, Analysis 그래프·표·CSV와 Experiment source를 볼 수 있습니다. Calculation 탭에서는 Demo의 Measurement 점과 RecordedData를 선택하고, 기존 Calculation source를 수정하거나 새 로컬 Draft를 만들어 Output을 즉시 미리볼 수 있습니다. 이 편집은 현재 Workbench에만 남고 원본 Calculation과 저장 데이터는 바뀌지 않으며, 탭을 떠날 때 폐기 확인 후 새로고침하면 원본으로 돌아갑니다. Demo 원본의 **Save & Run**, Simulation, 누락 데이터 계산, Measurement·Calculation 저장과 삭제는 로그인 상태에서도 사용할 수 없습니다. 일반 Experiment에서 이 작업들은 로그인과 기존 소유권이 필요합니다. **Edit a copy**는 Experiment source bundle만 새 로컬 Draft로 복제하며 원격 ID, Measurement, Calculation과 공개 Demo 데이터 연결은 복제하지 않습니다.',
      '',
      '### 마지막 편집이 예측 방향을 정합니다',
      '',
      '- 왼쪽 Vars를 편집하면 **Forward**가 됩니다. `vars → RecordedData`를 kNN으로 예측한 뒤, 선택한 각 Calculation의 저장된 source를 브라우저에서 직접 실행해 오른쪽 CalculationData를 갱신합니다.',
      '- 오른쪽의 Forward 결과를 처음 편집하면 전체 결과가 Target draft가 되고 **Inverse**가 됩니다. 선택한 CalculationData target 전체에서 vars를 kNN으로 예측하고, 완전한 vars 묶음을 한 번에 Candidate와 Viewer에 적용합니다. 입력한 target은 유지되며 Forward surrogate도 다시 계산합니다. 저장 Measurement를 Target으로 불러오는 selector는 없으며, Inverse는 현재 Forward 결과를 편집해서 시작합니다.',
      '- 연속 편집은 잠시 모아 처리하며 이전 요청의 늦은 결과는 버립니다. Inverse가 적용한 vars 때문에 Forward가 다시 시작되지는 않습니다. 리본의 Direction과 상태를 확인하고, 오래 걸리는 작업은 **Cancel**로 중단할 수 있습니다.',
      '- Prediction의 Vars도 Calculation과 같은 인라인 단일-open 카드입니다. Candidate 값이나 Inverse 결과가 갱신되어도 열린 카드는 유지되며 별도 팝업을 열지 않습니다.',
      '- 오른쪽 편집기는 기준 데이터와 비교 시리즈를 한 화면에 표시합니다. Forward는 파란 **Predicted**와 초록 **Save + Run Actual**을, Inverse는 주황 **Target**, 보라 **Re-predicted**, 초록 **Save + Run Actual**을 사용합니다. 비교 시리즈는 읽기 전용이므로 hover나 legend 확인이 Prediction 방향을 바꾸지 않습니다.',
      '- scalar는 공통 수치축 marker, 1-D는 공통 축의 line overlay로 비교합니다. 2-D는 동일 axes와 color scale을 공유하는 heatmap을 한 행에 병렬 배치하며, 같은 cell을 hover하면 모든 heatmap에서 좌표와 값을 함께 강조합니다. 좁은 패널에서는 가로 스크롤로 각 heatmap의 판독 크기를 유지합니다.',
      '- 각 CalculationData 카드의 **Display range**는 새 Forward primary 결과가 들어올 때 실제 min/max에 5% 여백을 더해 한 번 맞춘 뒤 고정됩니다. Target 편집, Inverse, Re-predicted 또는 Actual 도착만으로는 다시 확대·축소하지 않습니다. **Fit**은 현재 primary와 ready 상태인 호환 비교 시리즈 전체로 범위를 다시 맞춥니다. 범위 밖 cell은 끝 색으로 표시하고 `clipped` 수를 알리지만 데이터 값이나 dtype 허용 범위를 변경하지 않습니다.',
      '- Target heatmap의 선택 사각형은 Target commit, Inverse 시작·완료, Re-predicted·Actual 갱신과 Fit 뒤에도 유지됩니다. 새 Forward primary로 교체되거나 dtype, shape, axes가 바뀔 때만 선택을 초기화합니다.',
      '',
      '### Settings와 cohort',
      '',
      '리본의 **Prediction Settings**에서 한 개 이상의 저장된 Calculation, 각 Calculation의 거리 weight, k의 Auto/Manual 방식과 Neighbor weighting을 선택한 뒤 **적용**합니다. 성공한 preflight 계약이 없는 기존 Calculation은 선택할 수 없고 다시 저장해야 합니다. 설정 초안은 적용 전까지 현재 모델을 바꾸지 않습니다. Calculation을 선택하는 즉시 저장된 Output layout으로 오른쪽 카드와 shape·axes가 만들어지며 값이 도착하기 전에는 비편집 **Updating…** 상태입니다. **새로고침**은 최신 Measurement와 CalculationData를 다시 읽고, **누락 데이터 계산**은 선택한 Calculation의 미저장 조합을 계산한 뒤 데이터를 다시 불러옵니다.',
      '공개 Demo의 새로고침과 Model Details는 누구나 사용할 수 있지만 누락 데이터 계산은 데이터 변경이므로 로그인이 필요합니다.',
      '',
      'Forward는 선택한 Calculation dependency의 합집합에 해당하는 RecordedData만 조회합니다. 공유 ExperimentRecord는 한 번만 다운로드·모델링하고 관련 없는 Record는 flatten이나 메모리 계산에 포함하지 않습니다. 각 ExperimentRecord는 독립 kNN 모델을 가지며 numeric·finite runtime tensor를 정확한 shape별로 묶어 가장 큰 cohort를 사용합니다. 동률이면 가장 낮은 Measurement ID가 포함된 shape를 선택합니다. 따라서 Record A의 shape 불일치는 A 모델에서만 제외되고 Record B의 cohort나 다른 Calculation은 줄어들지 않습니다.',
      '',
      'Forward 예측 결과는 ExperimentRecord 계약 metadata와 해당 Record의 dominant runtime shape로 Calculation 입력을 복원합니다. 필요한 Record 모델이 없는 Calculation만 오류가 되고 다른 Calculation 결과는 유지됩니다. Settings와 Model Details에서는 Calculation별 dependency, Record별 포함/shape 제외 Measurement와 선택 cohort shape를 확인할 수 있습니다. Inverse는 저장된 Calculation Output 계약을 기준으로 complete-case 교집합을 만들므로 dtype·shape·axes layout을 다시 추측하지 않습니다.',
      '',
      'Runtime Console의 source를 **Prediction**으로 선택하면 Record별 shape 제외와 모델 실패를 확인할 수 있습니다. model fingerprint에는 ExperimentRecord contract hash, Calculation dependency·source hash·Output layout이 포함되므로 어느 계약이 바뀌어도 이전 모델, surrogate와 validation은 즉시 stale이 됩니다.',
      '',
      'Auto k는 포함된 행 수 `n`에 대해 `round(sqrt(n))`을 사용하되 1–15와 실제 cohort 크기 안으로 제한합니다. Manual k는 1–`n` 범위의 정수만 허용합니다. **Distance**는 가까운 이웃에 더 큰 weight를 주고, **Uniform**은 실제 선택된 이웃을 동일하게 평균합니다. Forward 거리는 varsSchema 범위로, Inverse 거리는 cohort의 표준편차로 정규화됩니다.',
      '',
      '모델은 브라우저 Prediction Worker의 Float64 배열에만 만들어지며 PCA, sampling이나 summary 값으로 대체하지 않습니다. 모델 하나의 numeric cell은 **1천만 개**, persistent array는 **192 MiB**, 전체 working set은 **256 MiB**가 상한입니다. 하나라도 초과하면 모델을 만들지 않고 메모리 오류를 표시합니다. 이 경우 선택 Calculation 수를 줄이거나 RecordedData·CalculationData tensor 크기를 줄인 뒤 새로고침하세요. 실제 사용량은 **Model Details**에서 확인할 수 있습니다.',
      '',
      '### Save & Run 검증',
      '',
      '최신 예측이 현재 Candidate와 일치하고 Experiment가 저장된 clean 상태일 때 리본의 **Save & Run**을 사용할 수 있습니다. 실행 시 현재 CalculationData와 Candidate revision을 비교 snapshot으로 고정하고, 현재 vars를 새 Measurement로 저장한 뒤 실제 Simulation, RecordedData 저장과 저장된 Calculation 자동 계산을 끝까지 수행합니다. Forward에서는 Predicted와 실제 CalculationData를 겹쳐 비교합니다. Inverse에서는 Target과 그 Target으로 추론한 Vars의 Re-predicted를 먼저 비교하고, 실행이 끝나면 Save + Run Actual까지 더해 세 결과를 함께 비교합니다.',
      '',
      '비교에는 dtype, shape와 axes가 정확히 같아야 하며, 호환되는 각 Calculation에 대해 MAE, RMSE와 최대 절대 오차를 오른쪽 카드와 **Model Details**에 표시합니다. Inverse 세부 정보에는 Target↔Re-predicted, Target↔Actual, Re-predicted↔Actual의 pairwise metric이 모두 표시됩니다. source 또는 snapshot이 현재 기준과 다르면 해당 시리즈를 겹치지 않고 Incompatible로 표시합니다. Simulation·저장·계산 실패나 Cancel은 검증 실패로 표시되고, 실제 CalculationData가 없는 대상은 개별 오류가 됩니다. 성공하면 새 Measurement가 cohort를 바꾸므로 Prediction 데이터가 stale 상태가 되며, 다음 검증 전에 Prediction Settings의 **새로고침**을 실행하세요.',
    ].join('\n'),
  }),
  manualChunk({
    id: 'workbench-admin-demo-curation',
    section: 'workbench',
    anchor: 'workbench-admin-demo-curation',
    title: 'Admin: 공개 Demo 큐레이션',
    summary: '관리자가 공개 Prediction Demo의 순서와 대표 항목을 관리하고 공개 범위를 확인합니다.',
    keywords: ['Admin', 'Demo', 'Curation', 'Public Materials', 'Users', '공개', '대표 Demo'],
    content: [
      '**Admin** 메뉴는 admin 역할에만 표시되며 **Users**, **All Experiments**, **Demo Curation**, **Public Materials** 화면을 제공합니다. 기존 Experiment와 Material 화면의 관리자 기능도 그대로 사용할 수 있습니다.',
      '',
      'Demo Curation에는 admin 사용자가 소유한 정확한 Experiment Version만 등록할 수 있습니다. 완전한 Recorded Measurement와 그 Measurement를 사용하는 ready Calculation 및 CalculationData가 하나 이상 있어야 **Ready**가 됩니다. 순서를 바꾸고 대표 Demo를 별표로 지정한 뒤 저장하세요. 대표 Demo를 해제하거나 삭제하면 다음 순서의 정상 Demo가 대표가 됩니다.',
      '',
      '**주의:** Demo 등록은 스냅샷을 만들지 않습니다. 해당 Version의 source bundle과 현재 및 향후 생성되는 전체 ExperimentRecord, Measurement, RecordedData, Calculation, CalculationData가 즉시 공개되고 복사 가능한 정보로 간주됩니다. 민감하거나 앞으로 공개되어서는 안 되는 데이터를 가진 Experiment는 등록하지 마세요. 공개 해제를 저장하면 익명 접근은 즉시 철회됩니다.',
    ].join('\n'),
  }),
  manualChunk({
    id: 'workbench-analysis',
    section: 'workbench',
    anchor: 'workbench-analysis',
    title: 'Analysis: Explore, Mining과 Data',
    summary: 'CalculationData가 저장된 Measurement를 탐색하고 고급 분석과 CSV 내보내기를 사용하는 방법입니다.',
    keywords: ['Analysis', 'Explore', 'Pearson', 'Spearman', 'Mining', 'PCA', 'CSV'],
    content: [
      '**Analysis**는 현재 Experiment에서 CalculationData가 하나 이상 저장된 Measurement만 분석합니다. Measurement의 숫자 input vars와 Material parameter는 feature로 유지하고, 저장된 CalculationData만 target으로 사용합니다. RecordedData는 Analysis에서 조회하거나 사용하지 않습니다. 중앙 3D Viewer와 Console은 그대로 유지되며, 오른쪽 Analysis 결과와 왼쪽 탭별 설정은 각각 스크롤할 수 있습니다.',
      '',
      '### Explore',
      '',
      'Analysis에 들어오면 사용할 수 있는 숫자 input vars와 숫자 CalculationData target의 모든 조합을 계산합니다. scalar CalculationData는 원값을 사용하고 rank 1–2 결과는 모든 원소의 `mean`과 표본 `std` 열로 요약합니다. 원소가 하나인 tensor의 `std`는 0이며 빈 tensor는 결측값입니다. Material parameter는 기본 상관 순위에 포함하지 않습니다. `|Pearson r|`이 큰 순서로 정렬하고, 같으면 `|Spearman ρ|`와 안정적인 key 순서를 사용합니다. 1위 조합이 자동으로 선택되며 검색 가능한 두 선택기나 순위 행으로 다른 조합을 고를 수 있습니다.',
      '',
      'Pearson과 Spearman은 완전한 input/target 값 쌍이 3개 이상이고 두 축이 상수가 아닐 때만 계산합니다. `n`은 실제 계산에 사용한 완전한 쌍의 수입니다. 산점도의 점에 포인터를 올리면 Measurement ID와 좌표를 확인할 수 있습니다.',
      '',
      '### Mining',
      '',
      '**Mining**은 2–50개 feature를 표준화해 PCA projection, 자동 K-Means, principal-component loadings와 reconstruction anomaly를 계산합니다. Explore 선택과는 독립적이며 검색, source 그룹, 전체 선택과 초기화를 사용할 수 있습니다.',
      '',
      '### Data와 CSV',
      '',
      '**Data**에는 histogram, scalar profile과 100행 데이터 표가 있습니다. 표와 **선택 데이터 CSV**는 Data 설정에서 선택한 feature 및 CalculationData 요약 열만 사용하며 CalculationData 원본 tensor 배열은 포함하지 않습니다.',
    ].join('\n'),
  }),
  manualChunk({
    id: 'workbench-viewer-selection',
    section: 'workbench',
    anchor: 'workbench-viewer-selection',
    title: '3D Viewer에서 Geometry와 Surface ID 확인',
    summary: 'Viewer 클릭과 Source의 ID 선택을 연결해 실제 Scene 전역 경로를 확인합니다.',
    keywords: ['Viewer', 'Geometry ID', 'Surface ID', 'selection', '전역 경로', 'surface'],
    content: [
      '3D Viewer의 **Off / Geometry / Surface** 선택 모드로 렌더링된 대상의 실제 Scene 전역 경로를 확인할 수 있습니다. 최초 모드는 **Off**이며 이 상태에서는 기존 카메라 회전·이동만 동작합니다.',
      '',
      '- **Geometry** 모드에서 클릭하면 가장 가까운 part 전체가 강조되고 `starter.body` 같은 geometry 전역 경로가 표시됩니다.',
      '- **Surface** 모드에서 클릭하면 해당 면만 강조되고 `starter.body/surface/1` 같은 surface 전역 경로가 표시됩니다.',
      '- 선택 카드의 복사 버튼으로 Solver group에 사용할 경로를 복사할 수 있습니다. Focus 버튼은 해당 geometry 또는 surface에 현재 카메라 방향을 유지한 채 화면을 맞춥니다. 선택된 경로는 Source에서 자동으로 확인되며 정확한 문자열 사용처가 있을 때만 Source 찾기 버튼이 활성화됩니다. 한 곳이면 바로 이동하고 여러 곳이면 결과 목록을 표시합니다. 빈 공간을 클릭하거나 Clear 버튼을 누르면 Viewer 선택이 해제됩니다.',
      '- 마우스를 움직인 동작은 클릭이 아니라 카메라 조작으로 처리하므로 드래그 도중 대상이 바뀌지 않습니다.',
      '',
      'Source 편집기에서 `geometryGroup`·`surfaceGroup`의 전역 경로 문자열에 커서를 두면 정확한 대상이 Viewer에서 강조됩니다. 정적인 JSX `id="body"`에 커서를 두면 해당 local segment가 만든 현재 Scene의 모든 실행 인스턴스를 강조하고 각각의 전역 경로를 보여 줍니다.',
      '',
      '계산식이나 expression이 포함된 template ID는 Source에 하나의 구체적인 실행 경로가 없으므로 코드에서 자동 역매칭하지 않습니다. 이 경우 Viewer에서 인스턴스를 직접 선택해 확정된 전역 경로를 확인하세요. Viewer 선택만으로는 코드 탭이나 커서를 이동시키지 않으며 Source 찾기 버튼을 누른 경우에만 검색 결과로 이동합니다. 선택은 Draft나 URL에 저장되지 않습니다.',
    ].join('\n'),
  }),
  manualChunk({
    id: 'workbench-ai-helper',
    section: 'workbench',
    anchor: 'workbench-ai-helper',
    title: 'AI Agent에 질문하는 방법',
    summary: '현재 작업과 문서 근거를 활용해 재현 가능한 답을 받는 질문법입니다.',
    keywords: ['AI Agent', '질문', '코드 작성', 'reference context', '출처', '하단 Dock'],
    content: [
      '중앙 하단 Dock의 **AI Agent**는 이 문서와 catalog에서 질문에 관련된 부분을 찾아 현재 응답에만 참고자료로 붙입니다. 일반 Lab의 AI Chat과 대화 기록은 공유하지 않습니다.',
      '',
      'AI Agent 상단의 대상 badge가 **Experiment**, **Calculation #id** 또는 **Calculation New** 중 무엇인지 먼저 확인하세요. Calculation 대상에서는 현재 Experiment source를 참고용으로 읽을 수 있지만 수정할 수 없고, Agent 결과는 Calculation source의 미저장 dirty draft로만 반영됩니다.',
      '',
      'AI Agent 채팅은 Experiment와 Calculation을 전환하거나 source를 편집해도 하나의 대화로 유지됩니다. 대화 안의 구분선은 각 질문과 답변이 사용한 작업 대상을 표시합니다. target별 보안 session은 분리되므로 다음 실행은 현재 열린 source와 최근 대화만 사용하며, 편집 권한과 적용 대상도 현재 target으로 제한됩니다.',
      '',
      '채팅 기록은 현재 브라우저 탭의 session storage에만 저장되어 새로고침 후 복원되지만 탭을 닫으면 사라집니다. **새 대화**는 채팅 기록과 Agent session 문맥을 모두 지우며, 로그아웃하거나 다른 사용자로 바뀌어도 기록을 제거합니다.',
      '',
      '좋은 질문에는 다음 정보를 함께 적으세요.',
      '',
      '- 만들 물리 문제와 기대하는 RecordedData',
      '- 사용하려는 solver 또는 `methodId`',
      '- 오류 메시지와 발생 단계(compile, evaluate, candidate, Measurement run)',
      '- 유지해야 할 단위, Geometry group, Material 조건',
      '',
      'AI가 제안한 코드는 현재 catalog의 실제 key, unit, target과 일치하는지 확인하고 Workbench에서 `Ready`와 Measurement 실행으로 검증해야 합니다.',
    ].join('\n'),
  }),
  manualChunk({
    id: 'program-overview',
    section: 'program',
    anchor: 'experiment-program-overview',
    aliases: ['experiment-program-mental-model', 'experiment-physical-model'],
    title: 'Experiment Program의 파일과 책임',
    summary: '공통 계약, named task와 Python orchestration을 독립 파일로 나눕니다.',
    keywords: [
      'Experiment Program',
      'experiment.tsx',
      'geometry.tsx',
      'material.tsx',
      'tasks',
      'simulate.py',
      'orchestration',
    ],
    content: [
      'Experiment Program은 공통 정의와 solver별 task, 실행 정책을 분리합니다.',
      '',
      '| 파일 | 책임 |',
      '| --- | --- |',
      '| `experiment.tsx` | 공통 lengthUnit, geometry, varsSchema, Material 역할 주입, group과 최종 recordedData 계약 |',
      '| `geometry.tsx` | Experiment와 Task가 공유하는 named Geometry component |',
      '| `material.tsx` | named Material 객체 또는 vars를 받는 Material factory |',
      '| `tasks/<name>.tsx` | solver identity, 선택적 Task-local scene과 `config({ vars })` |',
      '| `simulate.py` | named task 실행 순서, 분기, artifact 전달·해제·기록 |',
      '| 그 밖의 `.ts`, `.tsx` 파일 | bundle 내부에서 상대 import하는 보조 모듈 |',
      '',
      '공통 형상과 Task 보조 형상은 `geometry.tsx`, Material 정의는 `material.tsx`에서 named export하고 `experiment.tsx`와 각 Task에서 상대 import합니다. 필요한 보조 코드는 bundle에 파일을 추가해 로컬 상대 import할 수 있습니다. Source bundle 밖 package, URL, 동적 `import()`와 `require()`는 지원하지 않습니다.',
      '',
      '`experiment.tsx`의 `lengthUnit`, `varsSchema`, `geometry({ vars })`, `geometryGroup`, `surfaceGroup`, `recordedData`가 여러 Task가 공유하는 물리 세계와 최종 결과 계약입니다. 숫자만 보고 SI라고 가정하지 말고 scene 길이 단위와 각 DataSchema의 UCUM 단위를 명시하세요.',
    ].join('\n'),
  }),
  manualChunk({
    id: 'program-definition',
    section: 'program',
    anchor: 'experiment-program-definition',
    aliases: ['experiment-vars-geometry'],
    title: 'experiment.tsx: 변수와 RecordedData 계약',
    summary: '실험 공통 변수와 Measurement에 남길 최종 데이터만 선언합니다.',
    keywords: ['experiment()', 'varsSchema', 'recordedData', 'DataSchema', 'Measurement'],
    content: [
      '`experiment({...})`의 `recordedData`는 성공한 Measurement가 브라우저에 저장할 최종 schema입니다. task의 `outputs`는 이 계약이 아니라 kernel의 중간 artifact 요청입니다.',
      '',
      '각 RecordedData 항목에는 `dtype`, `unit`, `quantityKind`를 쓰고 다차원 값이면 축의 이름·단위·QuantityKind도 선언합니다. 성공 실행에서는 모든 declared key가 정확히 한 번 기록되어야 합니다. undeclared, duplicate 또는 missing record는 실행 오류입니다.',
      '',
      '`varsSchema`의 각 항목은 `min`, `max`와 선택적인 `shape`를 사용합니다. scalar는 `shape`를 생략할 수 있으며 기본값은 `[]`입니다. 명시적인 `shape: []`도 유효합니다. tensor는 `[3]`, `[4, 4, 1]`처럼 양의 safe integer 차원을 반드시 명시합니다. `min`과 `max`는 tensor가 아니라 모든 원소에 공통 적용되는 finite scalar이고 `min <= max`여야 합니다. shape 전체 원소 수는 65,536개 이하여야 하며 tensor shape 추론과 scalar/tensor broadcast는 지원하지 않습니다.',
      '',
      '```tsx',
      'varsSchema: {',
      '  radius: { min: 2, max: 5 },',
      '  position: { shape: [3], min: -10, max: 10 },',
      '}',
      '```',
      '',
      'Candidate는 선언한 shape와 정확히 같은 dense rectangular numeric tensor여야 합니다. 축별 범위가 다르면 `positionX`, `positionY`, `positionZ`처럼 의미별 scalar 변수로 분리한 뒤 Geometry callback에서 다시 조합하세요. Geometry callback은 `({ vars })`로 값을 받고 외부의 변경 가능한 상태에 의존하지 않아야 합니다. 같은 parent 아래의 component `id`는 고유해야 하며, 이 ID를 `geometryGroup`에 넣어 `experiment.geometry.<group>`으로 참조합니다. CAD API v1의 surface member는 `<geometry-id>/surface/<non-negative-index>` 형식이며 Geometry Catalog에 표시된 primitive별 고정 slot을 사용합니다.',
      '',
      '[Electro-Thermal Notched Bar의 canonical experiment.tsx 열기](/docs?section=solvers&item=experiment:caemble:experiment/caemble/verified/electro-thermal-notched-bar@1.0.0)',
    ].join('\n'),
  }),
  manualChunk({
    id: 'program-materials',
    section: 'program',
    anchor: 'experiment-program-materials',
    aliases: ['experiment-materials', 'experiment-program-material-roles'],
    title: 'Material 역할과 물성값',
    summary: 'canonical property와 역할 map을 선언하고 leaf의 body 역할로 연결합니다.',
    keywords: [
      'Material',
      'material.tsx',
      'role map',
      'body',
      'Mat',
      'canonical key',
      'dtype',
      'unit',
      'errorRate',
      'tire',
      'wheel',
    ],
    content: [
      '`new Material(...)`은 `material.tsx`에서만 사용합니다. named Material 객체 또는 factory를 export하고 Experiment와 Task는 이를 import해 root Geometry의 역할 map에 주입합니다.',
      '',
      '`materials` key는 `tire`, `wheel`, `shell` 같은 역할 이름입니다. primitive는 `body` 역할을 소비합니다. child에서 `materials`를 생략하면 map을 상속하고, 명시하면 교체하며, `{}`는 상속을 지웁니다. 중간 Geometry는 `materials={{ body: materials?.wheel }}`처럼 역할을 remap할 수 있습니다.',
      '',
      'Property는 [Material Catalog](/docs?section=materials)의 canonical key를 사용하고 solver가 요구하는 `dtype`, UCUM `unit`, QuantityKind와 tensor shape를 맞춥니다. 등방성 2차 tensor는 `Mat(value)`로 표현할 수 있습니다.',
      '',
      '`errorRate`가 있으면 Candidate의 frozen 값이 달라질 수 있습니다. 같은 이름과 선언의 Material은 Experiment와 모든 Task에서 한 번만 sampling되며, 저장한 Measurement에는 실제 parameter snapshot이 고정됩니다. unresolved 역할은 preview할 수 있지만 Measurement 생성과 solver 실행은 차단됩니다.',
      '',
      '[Two-material Wheel Assembly의 canonical Experiment bundle 열기](/docs?section=solvers&item=experiment:caemble:experiment/caemble/assemblies/two-material-wheel-assembly@1.0.0)',
    ].join('\n'),
  }),
  manualChunk({
    id: 'program-task',
    section: 'program',
    anchor: 'experiment-program-task',
    aliases: ['experiment-program-minimal-pair', 'experiment-program-kernel-limits', 'experiment-program-methods'],
    title: 'tasks/*.tsx: solver task 선언',
    summary: 'manifest의 parameter, method, target과 output 계약을 defineTask로 작성합니다.',
    keywords: ['defineTask', 'kernel', 'config', 'parameters', 'initializations', 'boundaryConditions', 'outputs'],
    content: [
      '`defineTask({...})`는 `kernel: { name, version }`, Task 전용 `lengthUnit`과 `geometry`, 그리고 `config({ vars })`를 선언합니다. Geometry를 사용하지 않아도 현재 계약에 맞는 scene과 단위를 명시하세요.',
      '',
      '`parameters`, `initializations`, `boundaryConditions`, `outputs`의 이름과 occurrence는 [Physics Catalog](/docs?section=solvers)의 현재 manifest가 단일 원본입니다. target은 `experiment.geometry.*`, `experiment.surface.*`, `task.geometry.*`, `task.surface.*` 중 method가 요구하는 source/kind와 일치해야 합니다.',
      '',
      '[Electro-Thermal Notched Bar의 canonical Task source 열기](/docs?section=solvers&item=experiment:caemble:experiment/caemble/verified/electro-thermal-notched-bar@1.0.0)',
    ].join('\n'),
  }),
  manualChunk({
    id: 'program-ray-tracing',
    section: 'program',
    anchor: 'experiment-program-ray-tracing',
    aliases: ['non-sequential-ray-tracing', 'ray-tracing-thin-film'],
    title: 'Non-sequential Ray Tracing',
    summary: '광선의 비순차 추적, 적응형 박막 처리와 detector 결과를 구성하는 방법입니다.',
    keywords: [
      'ray-tracing@0.1.0',
      'non-sequential',
      'point source',
      'area source',
      'directional source',
      'Lambertian source',
      'Stokes',
      'ABg',
      'Henyey-Greenstein',
      'detector',
      'thin film',
      'TMM',
      '50 um',
      'frequency',
      'ray paths',
    ],
    content: [
      '`ray-tracing@0.1.0`은 미리 정한 표면 순서를 따르지 않고, 광선이 기하와 만나는 순서대로 반사·굴절·산란·흡수를 추적하는 non-sequential solver입니다. 다중 반사, stray light, 바플과 혼탁 매질을 포함한 광학계에 사용하세요.',
      '',
      '### 광원과 산란',
      '',
      '- 광원은 point, area, directional, Lambertian 형식을 지원합니다. 모든 광원의 emitter locator geometry 또는 surface는 `ray.domain` group에서 제외하고, 실제 방출 위치도 모든 collision solid 바깥에 두세요. 각 광원 initialization call은 하나의 이산 wavelength line을 나타내므로, 여러 call을 나란히 추가해 다중 파장 광원을 구성합니다.',
      '- 편광은 광원의 4성분 Stokes vector로 주입합니다. 표면의 ABg 및 Lambertian scatter와 체적의 Henyey–Greenstein(HG) scatter를 사용하며, 산란된 광선은 depolarized 상태로 계속 추적됩니다.',
      '- `ray.domain` collision solid는 올바르게 중첩할 수 있지만 서로 부분적으로 겹치면 안 됩니다. 매질 경계의 진입·이탈 순서가 모호한 overlap은 실행을 거부합니다.',
      '',
      '### Shell layer의 적응형 박막 처리',
      '',
      '`<coating>` element를 따로 만들지 마세요. Solver가 canonical `<shell>`의 **각 layer에 대한 물리적 두께**를 판정합니다. 두께가 엄격히 `50 µm` 미만인 layer는 transfer-matrix method(TMM) 박막으로 적응형 처리하고, 인접한 박막 layer는 하나의 multilayer stack으로 계산합니다. 정확히 `50 µm`인 layer와 그보다 두꺼운 layer는 일반 광선–표면 collision으로 추적됩니다.',
      '',
      '박막과 체적의 광학 물성은 기존 Material parameter를 그대로 사용합니다. 카탈로그의 `MaterialParameter.frequency` 칼럼에 Hz 샘플을 넣으면 frozen Material에 Frequency 축 series로 전달되고, solver는 광원 파장에 대한 `frequency = c / wavelength`에서 선형 보간합니다. 샘플 범위 밖은 외삽하지 않고 실행을 거부하므로, `_by_wavelength` 별도 파라미터를 만들지 마세요.',
      '',
      '### Detector와 ray path',
      '',
      'Detector surface에서 irradiance, detected power, source 대비 efficiency를 기록할 수 있습니다. Ray path 시각화가 필요하면 semantic group `rayPaths` 안에 `vertices`, `pathOffsets`, `segmentPower`, `pathWavelength`, `segmentEvent` 다섯 tensor를 함께 선언하고 한 번의 `sim.record("rayPaths", {...})`로 기록하세요. 각 path는 최대 32개 segment를 담고 `maxPaths`는 65,536 이하입니다. Workbench는 이 group을 직접 3D Viewer에 표시합니다.',
      '',
      '[Folded Ray-Tracing Bench의 검증된 source, detector와 ray-path 계약 열기](/docs?section=solvers&item=experiment:caemble:experiment/caemble/verified/folded-ray-tracing@1.0.0)',
    ].join('\n'),
  }),
  manualChunk({
    id: 'program-simulate',
    section: 'program',
    anchor: 'experiment-program-simulate',
    title: 'simulate.py: 실행, 전달, 기록',
    summary: 'sim.run, sim.record, sim.release로 task와 artifact의 수명주기를 제어합니다.',
    keywords: ['simulate', 'sim.run', 'sim.record', 'sim.release', 'artifact', 'state', 'inputs'],
    content: [
      'Python `simulate(*, sim, tasks, vars)`가 named task의 실행 순서를 정합니다. `sim.run()`의 결과에는 opaque `state`, 다음 kernel에 전달하거나 기록할 `artifacts`, 작은 scalar `observations`가 있습니다.',
      '',
      '- `await sim.record(name, artifact)`: declared RecordedData로 승격하고 브라우저 ACK까지 대기',
      '- `sim.release(artifact)`: 더 사용하지 않는 중간 artifact 해제',
      '- `inputs={port: artifact}`: producer artifact를 호환되는 consumer input port에 전달',
      '- `state=...`: kernel의 opaque revision을 이어서 실행할 때만 사용',
      '',
      '[Electro-Thermal Notched Bar의 canonical simulate.py 열기](/docs?section=solvers&item=experiment:caemble:experiment/caemble/verified/electro-thermal-notched-bar@1.0.0)',
    ].join('\n'),
  }),
  manualChunk({
    id: 'program-runtime-rules',
    section: 'program',
    anchor: 'experiment-program-runtime-rules',
    aliases: ['experiment-program-troubleshooting'],
    title: '실행 중 state와 artifact 규칙',
    summary: 'capability reference의 수명, rollback과 provisional RecordedData 규칙입니다.',
    keywords: ['state', 'artifact', 'rollback', 'provisional', 'ACK', 'fatal', 'release'],
    content: [
      'state와 artifact reference는 현재 run 안에서만 유효합니다. 다른 run의 ref, release한 artifact, 잘못된 schema나 격리 위반을 사용하면 전체 실행이 실패합니다.',
      '',
      'kernel call이 실패하면 해당 호출이 만든 state와 artifact를 함께 rollback합니다. `sim.record()`로 브라우저에 도착한 결과도 실행이 끝날 때까지 provisional이며, 뒤 Task나 Python orchestration이 실패하면 모두 폐기됩니다.',
      '',
      'time-series는 같은 이름을 반복 기록하지 말고 시간축이 있는 하나의 tensor artifact로 만드세요. 작은 반복 조건은 observation을 사용하고 큰 물리 데이터는 artifact로 전달합니다.',
    ].join('\n'),
  }),
  manualChunk({
    id: 'program-verified-examples',
    section: 'program',
    anchor: 'experiment-program-examples',
    aliases: ['experiment-verified-example'],
    title: '검증된 Examples',
    summary: '실제 UI-CAE fixture로 검증되는 단계별 Experiment Program입니다.',
    keywords: ['program examples', 'DC', 'current density', 'notched', 'electro thermal', 'multiphysics'],
    content: [
      '다음 Examples는 SQLite 카탈로그의 source bundle을 Workbench와 UI-CAE 계약 테스트가 직접 사용합니다.',
      '',
      '- [Electro-Thermal Notched Bar](/docs?section=solvers&item=experiment:caemble:experiment/caemble/verified/electro-thermal-notched-bar@1.0.0)',
      '- [Folded Ray-Tracing Bench](/docs?section=solvers&item=experiment:caemble:experiment/caemble/verified/folded-ray-tracing@1.0.0)',
      '- [FDTD Drude Slab Pulse](/docs?section=solvers&item=experiment:caemble:experiment/caemble/verified/fdtd-drude-slab@1.0.0)',
      '- [Fiber Bundle](/docs?section=solvers&item=experiment:caemble:experiment/caemble/advanced-shapes/fiber-bundle@1.0.0)',
      '- [Shell Cutaways](/docs?section=solvers&item=experiment:caemble:experiment/caemble/advanced-shapes/shell-cutaways@1.0.0)',
      '- [Random Curved-edge Cylinder Array](/docs?section=solvers&item=experiment:caemble:experiment/caemble/arrays/random-curved-edge-cylinder-array@1.0.0)',
      '- [Random Curved-surface Sphere HCP Array](/docs?section=solvers&item=experiment:caemble:experiment/caemble/arrays/random-curved-surface-sphere-hcp-array@1.0.0)',
      '- [Two-material Wheel Assembly](/docs?section=solvers&item=experiment:caemble:experiment/caemble/assemblies/two-material-wheel-assembly@1.0.0)',
    ].join('\n'),
  }),
  manualChunk({
    id: 'program-multiphysics-example',
    section: 'program',
    anchor: 'experiment-program-multiphysics',
    title: 'Multiphysics 예제: Electro-Thermal Notched Bar',
    summary: 'DC의 Joule heating artifact를 정상상태 Heat task로 전달하는 orchestration입니다.',
    keywords: ['multiphysics', 'Joule heating', 'heatSource', 'electric', 'thermal'],
    collapsed: true,
    content:
      '[Electro-Thermal Notched Bar의 canonical bundle 열기](/docs?section=solvers&item=experiment:caemble:experiment/caemble/verified/electro-thermal-notched-bar@1.0.0)',
  }),
  manualChunk({
    id: 'reference-source-import',
    section: 'reference',
    anchor: 'cad-reference-overview',
    aliases: ['cad-reference-source-import'],
    title: '공개 Source와 import 경계',
    summary: 'TSX source에서 사용할 수 있는 @caemble/core 공개 경계를 설명합니다.',
    keywords: ['CAD Reference', '@caemble/core', 'import', 'default export', 'compile', 'evaluate'],
    content: [
      'Experiment source bundle은 핵심 파일뿐 아니라 사용자가 추가한 로컬 `.ts`, `.tsx` 파일도 함께 저장합니다. TypeScript/TSX 파일은 bundle 안의 다른 파일을 상대 경로로 import할 수 있습니다. Python은 핵심 `simulate.py` 한 파일만 사용합니다. `@caemble/core` 외 package, URL, 동적 `import()`와 `require()`는 지원하지 않습니다.',
      '',
      'Experiment 정의는 `experiment({...})`, 각 Task는 `defineTask({...})`를 default export합니다. `material.tsx`는 named Material 객체 또는 factory를 export하고, `geometry.tsx`는 PascalCase named `Geometry<Props>` 함수 component를 여러 개 export할 수 있습니다. 모든 의존 코드는 같은 Experiment bundle 안에 있으므로 별도 Geometry Repository나 Version coordinate를 해석하지 않습니다.',
      '',
      '부분 예시 — 다음 fence는 완성 파일이 아니라 로컬 bundle import 경계만 보여줍니다.',
      '',
      '```tsx',
      '// geometry.tsx',
      'import { profilePoints } from "./lib/profile"',
      'export const Conductor: Geometry = () => <Polygon points={profilePoints} />',
      '```',
      '',
      'Experiment Manager는 source-only **Example**, 저장된 사용자 Experiment Version, 데이터가 있는 공개 **Demo**를 구분해 엽니다. 저장된 coordinate는 `namespace / repository / key / SemVer`로 식별하며, Repository는 별도 관리 객체가 아니라 저장된 Experiment에서 파생되는 그룹입니다.',
      '',
      '**Save**는 현재 Version을 덮어쓰고, **Save New Version**은 patch/minor/major를 증가시키며, **Save As**는 새 repository/key의 `0.1.0`을 만듭니다. 저장 과정에서 컴파일된 RecordedData 선언은 ExperimentRecord 계약으로 함께 동기화됩니다. Measurement, RecordedData 또는 Calculation이 연결된 Version은 source와 Record 계약이 잠기므로 key·QuantityKind·tensorOrder·dtype·data schema를 바꾸려면 새 Version 또는 Save As를 사용해야 합니다. name/description 같은 metadata는 현재 Version에 저장할 수 있습니다.',
      '',
      'Standalone preview는 선택한 named export를 props 없이 호출할 수 있습니다. 모든 local PascalCase `Geometry<Props>` 함수는 custom prop을 직접 구조 분해하고 각각 명시적인 기본값을 제공해야 합니다. `id`, Material, children과 transform은 evaluator가 공통 기본값을 주입합니다.',
      '',
      'Source revision은 compile한 뒤 명시적인 Candidate vars로 같은 compiled source를 다시 evaluate합니다. 브라우저나 Node 전역, 시간, 네트워크 같은 외부 상태에 의존하는 코드는 재현 가능한 Measurement를 만들 수 없습니다.',
    ].join('\n'),
  }),
  manualChunk({
    id: 'reference-geometry-skeleton',
    section: 'reference',
    anchor: 'cad-reference-geometry-skeleton',
    title: 'Geometry 저작 골격과 좌표계',
    summary: 'CAD API v1 source의 기본 구조, 필수 prop 기본값, PascalCase primitive와 제어문 활용을 함께 보여줍니다.',
    keywords: [
      'CAD API v1',
      'geometry.tsx',
      'Geometry',
      'PascalCase',
      'loop',
      'control flow',
      'right-handed',
      'lengthUnit',
      '좌표계',
    ],
    content: [
      'CAD API v1 Geometry는 JSX를 반환하는 순수 함수 component입니다. `geometry.tsx`에는 재사용할 named `Geometry<Props>`를 두고, `experiment.tsx`의 `geometry` callback에서 호출합니다. 모든 custom prop은 required/optional 표기와 관계없이 구조 분해 initializer가 있어야 하므로 `<Assembly />`처럼 props 없이 호출할 수 있습니다. 숫자로 된 길이는 모두 해당 scene의 `lengthUnit`으로 해석됩니다.',
      '',
      '새 Experiment를 만들 때 Workbench가 제공하는 starter source bundle도 이 규칙을 따르며, AI reference 생성 시 같은 `experiment.tsx`와 `geometry.tsx`를 사용합니다.',
      '',
      '좌표계는 오른손 좌표계입니다. `+X`, `+Y`, `+Z`와 회전의 양의 방향에는 오른손 법칙을 적용합니다. primitive의 기준축과 원점은 요소마다 다르므로 추측하지 말고 [Geometry Catalog](/docs?section=geometry)의 **Origin / surfaces**를 확인하세요. 예를 들어 기본 cylinder 축은 Z이고, box와 cylinder는 자신의 local origin을 중심으로 생성됩니다.',
      '',
      'component는 입력 props와 `vars`만으로 같은 tree를 만들어야 합니다. 시간, 난수, DOM, 네트워크나 변경 가능한 module 상태에 의존하면 같은 source와 Measurement를 재현할 수 없습니다.',
      '',
      'Primitive는 props를 생략하면 Catalog에 표시된 canonical 단위 형상 기본값을 사용합니다. 자동 ID는 authoring name의 lower-kebab과 sibling 순번(`box`, `box-2`)으로 정해집니다.',
      '',
      '`for`, `Array.from`/`map`, `if`와 조건부 JSX를 사용할 수 있습니다. 반복 횟수는 유한하고 입력으로 재현 가능해야 하며, 반복되는 sibling에는 삽입·재정렬에도 유지되는 index나 domain key 기반의 명시적 `id`를 만드세요. 규칙적인 격자는 JS loop보다 `array` operation을 우선합니다.',
    ].join('\n'),
  }),
  manualChunk({
    id: 'reference-geometry-transforms',
    section: 'reference',
    anchor: 'cad-reference-geometry-transforms',
    aliases: ['cad-reference-v7-migration'],
    title: 'Transform: direct props와 operation wrapper',
    summary: 'direct Euler prop과 계층적인 translate·rotate·scale wrapper를 구분해 사용합니다.',
    keywords: [
      'position',
      'rotation',
      'scale',
      'translate',
      'axis angle',
      'radians',
      'Euler',
      'transform order',
      'pos',
      'rotate',
    ],
    content: [
      'Primitive, Boolean·shell·array operation과 `Geometry` component 호출은 같은 direct transform 계약을 사용합니다. `translate`·`rotate`·`scale` wrapper는 별도의 전용 prop 계약을 사용합니다.',
      '',
      '| Prop | 형식 | 의미 |',
      '| --- | --- | --- |',
      '| `position` | `[x, y, z]` | parent 좌표계에서의 이동 |',
      '| `rotation` | `[x, y, z]` | radian 단위의 intrinsic XYZ Euler, `THREE.Euler(x, y, z, "XYZ")`와 같은 의미 |',
      '| `scale` | `[x, y, z]` | 축별 배율. 균일 배율은 세 값을 같게 작성 |',
      '',
      '한 node 안에서는 **scale → rotation → position** 순서로 적용됩니다. parent와 child transform은 tree 계층대로 합성됩니다. 각도는 degree가 아니라 radian이므로 `Math.PI / 2`처럼 작성하세요.',
      '',
      '부분 예시 — 아래 fence는 완성 파일이 아닌 단일 intrinsic element 식입니다.',
      '',
      '```tsx',
      '<Cylinder',
      '  id="arm"',
      '  radius={2.5}',
      '  height={200}',
      '  position={[0, 100, 298]}',
      '  rotation={[Math.PI / 2, 0, 0]}',
      '/>',
      '```',
      '',
      '여러 child를 한 local transform 아래 묶을 때는 lowercase operation wrapper를 사용합니다. Wrapper는 아래 전용 prop만 받고 direct transform prop과 섞지 않습니다. 안쪽 wrapper부터 적용되므로 다음 순서는 scale → rotate → translate입니다.',
      '',
      '```tsx',
      "import { Box, radians } from '@caemble/core'",
      '',
      '<translate offset={[100, 0, 0]}>',
      '  <rotate axis={[0, 0, 1]} angle={radians(90)}>',
      '    <scale x={2} y={1} z={1}>',
      '      <Box id="body" size={[20, 10, 5]} />',
      '    </scale>',
      '  </rotate>',
      '</translate>',
      '```',
      '',
      '`radians(number)`와 `radians(Vec3)`는 degree를 radian으로 바꿉니다. Direct `rotation`은 intrinsic XYZ Euler Vec3이고, `<rotate>`는 오른손 법칙의 axis-angle이므로 두 표현의 의미를 구분하세요.',
      '',
      '`pos`와 `{ axis, angle }` 형태의 `rotate`는 v7 안에서 기존 source를 잠시 옮기기 위한 deprecated 호환 문법입니다. 새 코드는 `position`과 `rotation`만 사용하세요. 같은 node에서 canonical family와 deprecated family를 섞을 수 없으며 `translation` prop은 지원하지 않습니다.',
    ].join('\n'),
  }),
  manualChunk({
    id: 'reference-geometry-identity',
    section: 'reference',
    anchor: 'cad-reference-geometry-identity',
    title: 'ID, group과 surface identity',
    summary: '안정적인 solver target을 위해 component, primitive와 operation의 소유권을 구분합니다.',
    keywords: [
      'id',
      'identity',
      'geometryGroup',
      'surfaceGroup',
      'numeric surface',
      'surface-N',
      'operation',
      'Fragment',
    ],
    content: [
      '`id`는 단순한 화면 label이 아니라 Geometry 결과의 identity입니다. custom `Geometry` component를 호출할 때는 `id`가 필수이고, 모든 intrinsic primitive와 operation에는 필요할 때 `id`를 줄 수 있습니다. Fragment(`<>...</>`)에는 `id`나 transform을 줄 수 없습니다.',
      '',
      '- primitive의 `id`는 그 primitive가 만든 part를 소유합니다.',
      '- topology를 바꾸는 `union`, `subtract`, `intersect`, `shell` 같은 operation에 `id`가 있으면 그 operation의 최종 결과가 해당 identity를 소유합니다. 피연산자 ID가 Boolean 결과의 ID라고 가정하지 마세요.',
      '- component의 `id`는 재사용되는 subtree의 namespace/root identity가 됩니다. 같은 parent 아래의 sibling ID는 서로 달라야 합니다.',
      '- evaluator가 component 호출의 `id`를 이미 소비하므로 받은 `id`를 leaf intrinsic에 그대로 전달하지 마세요. child에 별도 local segment가 필요할 때만 intrinsic `id`를 부여합니다.',
      '- `geometryGroup`에는 의도적으로 부여한 결과 ID만 넣고, 실행 전에 Viewer에서 실제 resolve 결과를 확인하세요.',
      '- CAD API v1 surface는 `<geometry-id>/surface/<non-negative-index>`로 참조합니다. 예를 들어 `conductor.body` Box leaf의 local +X slot은 `conductor.body/surface/1`입니다. leaf에 명시적 `id`를 주고 Geometry Catalog에 표시된 고정 slot을 사용하세요.',
      '- 공식 Catalog는 각 Example의 공개 계약 v1 Version만 제공합니다. 제거된 이전 coordinate에는 alias나 redirect가 없으며 조회 시 `404 catalog_not_found`를 반환합니다.',
      '- 한 Boolean operation은 최대 128개 operand를 받습니다. 큰 lattice를 중첩 Boolean으로 전개하면 Manifold 실행 전에 triangle 및 triangle-pair work 예산에서 거부됩니다.',
      '',
      '중간 조립용 Fragment에 억지로 identity를 만들기보다 named `Geometry` component로 추출하세요. 반대로 solver가 최종 Boolean body 하나만 필요하면 operation에 `id`를 주는 편이 소유권이 가장 분명합니다.',
    ].join('\n'),
  }),
  manualChunk({
    id: 'reference-geometry-elements',
    section: 'reference',
    anchor: 'cad-reference-geometry-elements',
    title: 'Primitive 선택과 operation 규칙',
    summary: '가장 단순한 primitive에서 시작하고 child cardinality와 순서 계약을 지킵니다.',
    keywords: ['box', 'cylinder', 'sphere', 'fiber', 'array', 'shell', 'union', 'subtract', 'intersect', 'children'],
    content: [
      '표현할 수 있다면 `Box`, `Cylinder`, `Sphere`부터 사용하세요. Primitive는 `@caemble/core`에서 PascalCase로 import하고 operation은 lowercase JSX tag로 작성합니다. 곡선 단면·표면이 실제 요구사항일 때만 `CurvedEdgeCylinder`, `CurvedSurfaceSphere`, `Fiber`를 선택하면 parameter와 mesh 비용을 줄일 수 있습니다. 각 prop의 type, 필수 여부, 기본값, 제약, 기준 원점, surface 의미와 실행 가능한 예제는 [Geometry Catalog](/docs?section=geometry)가 공식 원본입니다.',
      '',
      '| Operation | child 계약 | 핵심 규칙 |',
      '| --- | --- | --- |',
      '| `translate` | 1개 이상 | `offset` Vec3로 child group을 상대 이동 |',
      '| `rotate` | 1개 이상 | `axis`와 radian `angle`로 오른손 axis-angle 회전 |',
      '| `scale` | 1개 이상 | `x`, `y`, `z` 축별 배율을 local 원점 기준으로 적용 |',
      '| `union` | 1개 이상 | 모든 child를 하나의 결과로 결합 |',
      '| `subtract` | 2개 이상 | 첫 child가 base, 이후 child는 cutter |',
      '| `intersect` | 2개 이상 | 모든 child의 공통 체적만 유지 |',
      '| `shell` | 정확히 1개 | material role별 offset surface 생성 |',
      '| `array` | 정확히 1개의 identified intrinsic 또는 `Geometry` child | `shape`, `period`, 선택적 `axes`와 canonical `inject`로 instance 생성 |',
      '',
      'Boolean child 순서는 source 계약의 일부입니다. ring은 큰 cylinder 하나로 근사하지 말고, 큰 cylinder에서 더 높고 작은 cylinder를 빼서 실제 annular solid를 만드세요. 0 두께, 음수 크기, NaN/Infinity, 퇴화한 축처럼 유효하지 않은 입력은 evaluator가 거부합니다.',
      '',
      'Material은 root에서 역할 map으로 주입하고 leaf에서 `body`로 remap합니다. 생략하면 parent map을 상속하고, 명시하면 교체하며, `materials={{}}`는 상속을 지웁니다. 자세한 선언과 sampling 계약은 [Material과 물성값](/docs?section=program#experiment-materials)을 참고하세요.',
    ].join('\n'),
  }),
  manualChunk({
    id: 'reference-core-api',
    section: 'reference',
    anchor: 'cad-reference-core-api',
    aliases: ['cad-reference-primitives', 'cad-reference-operations', 'cad-reference-vars-geometry'],
    title: '@caemble/core 핵심 API',
    summary: 'CAE 저작에서 가장 자주 사용하는 공개 symbol의 책임을 정리합니다.',
    keywords: ['experiment', 'defineTask', 'Material', 'Mat', 'Geometry', 'Vec3', 'DataSchema'],
    content: [
      '| Symbol | 사용 위치 | 역할 |',
      '| --- | --- | --- |',
      '| `experiment` | `experiment.tsx` | 공통 geometry, vars, Material 역할 주입, group과 RecordedData schema 정의 |',
      '| `defineTask` | `tasks/*.tsx` | solver identity, Task scene과 config 정의 |',
      '| `Material` | `material.tsx` | canonical property와 sampling/freeze 정책 정의 |',
      '| `Mat` | Material tensor 값 | scalar를 등방성 3×3 tensor로 표현 |',
      '| `Geometry<Props>` | TSX component type | 재사용 가능한 Geometry component의 props 정의 |',
      '| `Vec3` | 위치·크기 props | 길이 3 vector type |',
      '| `Box` 등 | Geometry TSX | PascalCase primitive literal alias |',
      '| `radians` | Geometry transform | degree number 또는 Vec3를 radian으로 변환 |',
      '',
      'Geometry element의 실제 tag와 prop syntax는 [Geometry Catalog](/docs?section=geometry), solver method와 parameter는 [Physics Catalog](/docs?section=solvers)를 사용하세요. catalog가 declaration과 manifest의 최신 단일 원본입니다.',
    ].join('\n'),
  }),
  manualChunk({
    id: 'reference-data-schema',
    section: 'reference',
    anchor: 'cad-reference-data-schema',
    aliases: ['cad-reference-material'],
    title: 'DataSchema, QuantityKind와 UCUM 단위',
    summary: 'scalar·tensor shape와 물리 의미, 변환 가능한 단위를 함께 선언합니다.',
    keywords: ['DataSchema', 'dtype', 'axes', 'shape', 'QuantityKind', 'UCUM', 'unit', 'tensorOrder'],
    content: [
      '물리 데이터는 값만 전달하지 않습니다. `dtype`, `unit`, `quantityKind`, 필요하면 `axes`가 함께 계약을 이룹니다.',
      '',
      '- scalar는 axes가 없습니다.',
      '- vector 또는 matrix의 component shape는 QuantityKind의 `tensorOrder`와 일치해야 합니다.',
      '- 공간장과 time-series의 sample 축은 `axes`에서 길이와 의미를 선언합니다.',
      '- unit은 [Quantity Catalog](/docs?section=quantity-kinds)의 `applicableUnits`에 있고 worker가 변환할 수 있는 UCUM 문자열이어야 합니다.',
      '- `{fraction}`처럼 중괄호가 있는 UCUM annotation도 문자열 그대로 사용합니다.',
      '',
      'Material catalog에 key가 존재한다는 사실만으로 임의 unit이 허용되는 것은 아닙니다. Material의 QuantityKind와 실제 worker unit converter 계약을 모두 만족해야 합니다.',
    ].join('\n'),
  }),
  manualChunk({
    id: 'reference-targets-results',
    section: 'reference',
    anchor: 'cad-reference-targets-results',
    aliases: ['cad-reference-task-recorded-data', 'cad-reference-kernels', 'cad-reference-results'],
    title: 'Target, run 상태와 결과 경계',
    summary: 'Experiment/Task scene target과 RecordedData가 worker 경계를 통과하는 방식을 설명합니다.',
    keywords: ['target', 'experiment.geometry', 'task.geometry', 'run status', 'RecordedData', 'trace', 'provenance'],
    content: [
      'target 문자열은 `<scene>.<kind>.<group>` 형태입니다. `experiment.*`는 공통 물리 scene, `task.*`는 현재 named Task의 local scene을 가리킵니다. method manifest의 `source`와 `kind`가 target과 일치해야 합니다.',
      '',
      'Prepared Measurement는 고정 입력 조건이며 그 자체가 실행 상태를 갖는 run은 아닙니다. 선택한 Measurement로 시작한 실행 요청이 성공, 실패 또는 취소로 끝나고, 성공 결과를 한 번 저장하면 Measurement가 Recorded 상태가 됩니다. opaque solver state와 중간 artifact는 CAE worker 밖으로 나오지 않습니다. 브라우저는 Experiment에 선언되고 `sim.record()`가 완료된 RecordedData만 받습니다. trace와 provenance는 진단용이며 사용자 결과 schema에 자동 추가되지 않습니다.',
    ].join('\n'),
  }),
  manualChunk({
    id: 'troubleshooting-ready',
    section: 'troubleshooting',
    anchor: 'troubleshooting-ready',
    title: '문서가 Ready가 되지 않을 때',
    summary: 'compile/evaluate 단계와 source 위치를 기준으로 오류를 좁힙니다.',
    keywords: ['troubleshooting', 'Ready', 'compile', 'evaluate', 'diagnostic', 'source error'],
    content: [
      '1. diagnostics에 표시된 **파일명, line, column과 첫 오류**부터 확인합니다.',
      '2. import가 `@caemble/core`인지, 올바른 default export를 사용하는지 확인합니다.',
      '3. TSX tag와 prop 이름을 Geometry Catalog의 syntax와 비교합니다.',
      '4. `varsSchema`의 scalar min/max, tensor의 필수 shape, Candidate의 정확한 shape, Geometry ID 중복과 group member ID를 확인합니다.',
      '5. surface group이 `<geometry-id>/surface/<non-negative-index>`를 사용하고 Geometry Catalog의 primitive별 고정 slot 범위에 있는지 확인합니다.',
      '6. Material key, dtype, unit과 tensor shape를 catalog와 비교합니다.',
      '',
      'source를 고친 뒤에도 이전 조건만 보인다면 상태가 `Ready`인지 확인하고 새 Candidate를 생성합니다. 이전 Experiment revision의 Measurement는 현재 revision에서 실행할 수 없습니다.',
    ].join('\n'),
  }),
  manualChunk({
    id: 'troubleshooting-target-manifest',
    section: 'troubleshooting',
    anchor: 'troubleshooting-target-manifest',
    title: 'target 또는 solver manifest 오류',
    summary: 'solver identity, method occurrence와 group target을 현재 manifest에 맞춥니다.',
    keywords: ['target', 'manifest', 'methodId', 'occurrence', 'group', 'solver', 'invalid_manifest'],
    content: [
      '- Physics Catalog에서 `name@version`이 정확히 존재하는지 확인합니다.',
      '- method가 `initializations`, `boundaryConditions`, `outputs` 중 어디에 속하는지 확인합니다.',
      '- required parameter와 occurrence의 최소·최대 횟수를 확인합니다.',
      '- target의 scene(`experiment`/`task`)과 kind(`geometry`/`surface`)를 확인합니다.',
      '- group 이름이 source에 선언되어 있고 실제 Geometry 또는 surface로 resolve되는지 확인합니다.',
      '',
      'solver manifest 내용을 UI에 복사해 고치지 마세요. 배포된 manifest와 [Physics Catalog](/docs?section=solvers)가 현재 계약입니다.',
    ].join('\n'),
  }),
  manualChunk({
    id: 'troubleshooting-units-materials',
    section: 'troubleshooting',
    anchor: 'troubleshooting-units-materials',
    title: 'unit, QuantityKind 또는 Material 오류',
    summary: 'canonical key와 변환 가능한 UCUM 단위, tensor shape를 함께 점검합니다.',
    keywords: ['invalid_unit', 'UCUM', 'QuantityKind', 'Material', 'tensor', 'conductivity'],
    content: [
      '1. Material key를 Material Catalog에서 정확히 복사합니다.',
      '2. 그 key가 가리키는 QuantityKind를 확인합니다.',
      '3. Quantity Catalog에서 현재 unit이 `applicableUnits`에 있는지 확인합니다.',
      '4. solver parameter가 요구하는 QuantityKind와 dtype을 Physics Catalog에서 확인합니다.',
      '5. vector/matrix 값의 shape와 basis 조건을 확인합니다.',
      '',
      '`invalid_unit`은 이름이 그럴듯한 단위라도 worker가 해당 QuantityKind에 대해 변환할 수 없다는 뜻입니다. catalog membership 하나만 보고 새 단위를 추가하지 마세요.',
    ].join('\n'),
  }),
  manualChunk({
    id: 'troubleshooting-runtime-results',
    section: 'troubleshooting',
    anchor: 'troubleshooting-runtime-results',
    title: 'Measurement 실행 또는 결과 오류',
    summary: '선택 입력, artifact 수명과 RecordedData 계약을 순서대로 점검합니다.',
    keywords: ['Measurement', 'artifact', 'recordedData', 'stale', 'failed', 'cancelled', 'Launcher'],
    content: [
      '1. 로그인과 CAE Launcher 연결 상태를 확인합니다.',
      '2. 현재 Experiment revision에 속하고 RecordedData가 아직 없는 prepared Measurement를 선택했는지 확인합니다.',
      '3. Python의 task 이름이 `tasks/<name>.tsx` 파일명과 일치하는지 확인합니다.',
      '4. output key와 `result["artifacts"]` key를 확인합니다.',
      '5. `sim.record()` 이름과 Experiment `recordedData` 이름을 확인합니다.',
      '6. release한 artifact를 다시 전달하거나 기록하지 않았는지 확인합니다.',
      '7. source를 수정했다면 stale 결과를 버리고 다시 실행합니다.',
      '',
      '취소는 정상적인 terminal 상태일 수 있습니다. 실패 원인을 분석할 때는 사용자에게 보이는 첫 오류와 현재 task/method를 함께 기록하고, opaque worker state나 전체 binary 결과를 복사하지 마세요.',
    ].join('\n'),
  }),
])

export const catalogDocsKnowledge: readonly DocsKnowledgeChunk[] = Object.freeze([
  ...cadElementCatalog.map((entry) =>
    Object.freeze({
      id: `geometry:${entry.tag}`,
      section: 'geometry' as const,
      title: entry.authoringName,
      summary: entry.summary,
      item: entry.tag,
      href: docsSectionHref('geometry', entry.tag),
      keywords: Object.freeze([
        entry.authoringName,
        entry.tag,
        entry.category,
        entry.syntax,
        ...entry.keywords,
        ...entry.properties.flatMap(({ name, type }) => [name, type]),
      ]),
      content: [
        `Authoring name: ${entry.authoringName}`,
        `Registry tag: ${entry.tag}`,
        `Category: ${entry.category}`,
        `Syntax: ${entry.syntax}`,
        `Summary: ${entry.summary}`,
        `Origin: ${entry.origin}`,
        `Children (${entry.children.count}): ${entry.children.description}`,
        '',
        'Properties:',
        ...entry.properties.map(
          (property) =>
            `- ${property.name}: ${property.type}; ${property.required ? 'required' : 'optional'}${'default' in property && property.default !== undefined ? `; default ${property.default}` : ''}. ${property.description}`,
        ),
        '',
        'Surfaces:',
        ...(entry.surfaces.length
          ? entry.surfaces.map((surface) => `- \`surface/${surface.index}\` — ${surface.label}: ${surface.description}`)
          : ['- No fixed surface contract.']),
        '',
        '검증된 부분 TSX 예시 — 완성 파일이 아닌 단일 element 식:',
        '```tsx',
        entry.example,
        '```',
      ].join('\n'),
    }),
  ),
])

export function catalogSearchKnowledge(items: readonly CatalogSearchItem[]): readonly DocsKnowledgeChunk[] {
  return Object.freeze(
    items.map((item) => {
      const section =
        item.kind === 'quantityKind'
          ? 'quantity-kinds'
          : item.kind === 'solver' || item.kind === 'experiment'
            ? 'solvers'
            : 'materials'
      const selectedItem = item.kind === 'experiment' ? `experiment:${item.key}` : item.key
      return Object.freeze({
        id: `${item.kind}:${item.key}`,
        section,
        title: item.title,
        summary: item.subtitle,
        item: selectedItem,
        href: docsSectionHref(section, selectedItem),
        keywords: Object.freeze([item.kind, item.key, item.title, item.subtitle]),
        content: item.subtitle,
      })
    }),
  )
}

export function getDocsKnowledge(): readonly DocsKnowledgeChunk[] {
  return [...manualDocsKnowledge, ...catalogDocsKnowledge]
}

export function searchDocsKnowledge(
  query: string,
  chunks: readonly DocsKnowledgeChunk[] = getDocsKnowledge(),
): readonly DocsKnowledgeChunk[] {
  const needle = query.normalize('NFKC').trim().toLocaleLowerCase()
  if (!needle) return []
  const terms = needle.split(/\s+/).filter(Boolean)

  return chunks
    .flatMap((chunk) => {
      const title = chunk.title.normalize('NFKC').toLocaleLowerCase()
      const normalizedKeywords = chunk.keywords.map((keyword) => keyword.normalize('NFKC').toLocaleLowerCase())
      const keywords = normalizedKeywords.join(' ')
      const text = `${title} ${chunk.summary} ${keywords}${chunk.item ? ` ${chunk.content}` : ''}`
        .normalize('NFKC')
        .toLocaleLowerCase()
      const matchedTerms = terms.filter((term) => text.includes(term)).length
      if (!text.includes(needle) && matchedTerms === 0) return []
      const rank =
        title === needle
          ? 0
          : title.startsWith(needle)
            ? 1
            : normalizedKeywords.some((keyword) => keyword === needle)
              ? 2
              : normalizedKeywords.some((keyword) => keyword.startsWith(needle))
                ? 3
                : text.includes(needle)
                  ? 4
                  : 5
      return [{ chunk, matchedTerms, rank }]
    })
    .sort(
      (left, right) =>
        left.rank - right.rank ||
        right.matchedTerms - left.matchedTerms ||
        left.chunk.title.localeCompare(right.chunk.title, 'ko') ||
        left.chunk.id.localeCompare(right.chunk.id),
    )
    .map(({ chunk }) => chunk)
}
