import { execFileSync } from 'node:child_process'
import { readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { build } from 'esbuild'
import { format } from 'prettier'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const changed = []

const elementManifestPath = path.join(root, 'src/lib/cad/elements/manifest.json')
const elementManifest = JSON.parse(await readFile(elementManifestPath, 'utf8'))

function catalogQuery(resource, key, ...identityArguments) {
  const catalogRoot = path.resolve(root, '../catalog')
  const executable = process.env.PYTHON || (process.platform === 'win32' ? 'python' : 'python3')
  const output = execFileSync(
    executable,
    [
      '-m',
      'caemble_catalog',
      '--database',
      path.join(catalogRoot, 'caemble_catalog/catalog.sqlite3'),
      'query',
      resource,
      key,
      ...identityArguments,
    ],
    {
      cwd: catalogRoot,
      encoding: 'utf8',
      env: {
        ...process.env,
        PYTHONPATH: [catalogRoot, process.env.PYTHONPATH].filter(Boolean).join(path.delimiter),
      },
    },
  )
  return JSON.parse(output)
}

function tsString(value) {
  return `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`
}

function formatGenerated(relativePath, source) {
  return format(source, {
    filepath: path.join(root, relativePath),
    printWidth: 120,
    semi: false,
    singleQuote: true,
    trailingComma: 'all',
  })
}

function groupedImports(entries, moduleKey, exportKey) {
  const modules = new Map()
  entries.forEach((entry) => {
    const names = modules.get(entry[moduleKey]) ?? []
    if (!names.includes(entry[exportKey])) names.push(entry[exportKey])
    modules.set(entry[moduleKey], names)
  })
  return [...modules.entries()]
    .map(([moduleName, names]) => `import { ${names.join(', ')} } from ${tsString(moduleName)}`)
    .join('\n')
}

async function loadBundledModule(entryPoint) {
  const result = await build({
    bundle: true,
    entryPoints: [entryPoint],
    format: 'esm',
    logLevel: 'silent',
    platform: 'node',
    target: 'node20',
    define: { 'import.meta.env.MODE': '"production"' },
    write: false,
  })
  const source = Buffer.from(result.outputFiles[0].text).toString('base64')
  return import(`data:text/javascript;base64,${source}`)
}

async function emit(relativePath, content) {
  const outputPath = path.join(root, relativePath)
  let current = ''
  try {
    current = await readFile(outputPath, 'utf8')
  } catch {
    // New generated file.
  }
  if (current.replaceAll('\r\n', '\n') === content) return
  changed.push(relativePath)
  await writeFile(outputPath, content, 'utf8')
}
function generatedElementRegistry() {
  const elements = elementManifest.elements
  return `// Generated by scripts/generate-cad-api.mjs from manifest.json. Do not edit.\n${groupedImports(
    elements,
    'definitionModule',
    'manifestExport',
  )}\n${groupedImports(elements, 'runtimeModule', 'definitionExport')}\nimport { cadAuthoringContract } from './authoringContract'\nimport type { CadElementDefinition } from '../evaluation/types'\n\nexport { cadAuthoringContract }\n\nexport const cadPrimitiveAuthoringBindings = Object.freeze({\n${elements
    .filter((element) => element.authoringName !== element.tag)
    .map((element) => `  ${element.authoringName}: ${tsString(element.tag)},`)
    .join(
      '\n',
    )}\n} as const)\n\nexport const cadElementCatalog = [\n${elements.map((element) => `  ${element.manifestExport},`).join('\n')}\n] as const\n\nexport const cadElementDefinitions = [\n${elements.map((element) => `  ${element.definitionExport},`).join('\n')}\n] as const satisfies readonly CadElementDefinition[]\n`
}

function generatedJsxDeclaration() {
  const attributes = [
    ...new Set(
      elementManifest.elements
        .filter((element) => element.authoringName === element.tag)
        .map((element) => element.attributes),
    ),
  ].sort()
  return `// Generated by scripts/generate-cad-api.mjs from elements/manifest.json. Do not edit.\nimport type {\n${attributes.map((name) => `  ${name},`).join('\n')}\n  Geometry,\n  GeometryInvocationAttributes,\n} from '@caemble/core'\n\ndeclare global {\n  function h(type: unknown, attributes: unknown, ...children: unknown[]): unknown\n  function Fragment(props: { children?: unknown }): unknown\n\n  namespace JSX {\n    type LibraryManagedAttributes<Component, Props> = Props extends { readonly id: string }\n      ? Component extends Geometry<infer CustomProps>\n        ? GeometryInvocationAttributes<CustomProps>\n        : Props\n      : Props\n\n    interface IntrinsicElements {\n${elementManifest.elements
    .filter((element) => element.authoringName === element.tag)
    .map((element) => `      ${element.tag}: ${element.attributes}`)
    .join('\n')}\n    }\n  }\n}\n\nexport {}\n`
}

function primitiveAuthoringDeclarations() {
  return `// <generated:primitive-authoring-bindings>
${elementManifest.elements
  .filter((element) => element.authoringName !== element.tag)
  .map((element) => `export const ${element.authoringName}: (props: ${element.attributes}) => unknown`)
  .join('\n')}
// </generated:primitive-authoring-bindings>`
}

function quantityKindTypes() {
  return `// <generated:quantity-kind-types>
export interface CatalogQuantityKindMap {}
export type QuantityKindName = keyof CatalogQuantityKindMap extends never ? string : keyof CatalogQuantityKindMap
export type QuantityKindDomain = string
export type QuantityKindNameForDomain<Domain extends QuantityKindDomain> = keyof CatalogQuantityKindMap extends never
  ? string & { readonly __domain?: Domain }
  : { [Name in keyof CatalogQuantityKindMap]: CatalogQuantityKindMap[Name]['domain'] extends Domain ? Name : never }[keyof CatalogQuantityKindMap]
export type TensorQuantityKindName = keyof CatalogQuantityKindMap extends never
  ? string
  : { [Name in keyof CatalogQuantityKindMap]: CatalogQuantityKindMap[Name]['tensorOrder'] extends 0 ? never : Name }[keyof CatalogQuantityKindMap]
export type ScalarQuantityKindName = keyof CatalogQuantityKindMap extends never
  ? string
  : { [Name in keyof CatalogQuantityKindMap]: CatalogQuantityKindMap[Name]['tensorOrder'] extends 0 ? Name : never }[keyof CatalogQuantityKindMap]
export type ApplicableUnit<Name extends QuantityKindName> = Name extends keyof CatalogQuantityKindMap
  ? CatalogQuantityKindMap[Name]['applicableUnits'][number]
  : UcumUnit
// </generated:quantity-kind-types>`
}

function materialCatalogTypes(properties, models) {
  void properties
  void models
  return `// <generated:material-catalog-types>
// Catalog keys are augmented in memory from the active Solver runtime slice.
export interface MaterialPropertyQuantityKindMap {}
export type MaterialPropertyKey = keyof MaterialPropertyQuantityKindMap extends never
  ? string
  : keyof MaterialPropertyQuantityKindMap
export type MaterialPropertyQuantityKind<Key extends MaterialPropertyKey> = Key extends keyof MaterialPropertyQuantityKindMap
  ? MaterialPropertyQuantityKindMap[Key]
  : QuantityKindName
export type MaterialPropertyDefinitionFor<Key extends MaterialPropertyKey> = Readonly<{
  key: Key
  quantity_kind: MaterialPropertyQuantityKind<Key>
}>

export interface MaterialModelDefinitionMap {}
export type MaterialModelKey = keyof MaterialModelDefinitionMap extends never ? string : keyof MaterialModelDefinitionMap
export type MaterialModelDefinitionFor<Key extends MaterialModelKey> = Key extends keyof MaterialModelDefinitionMap
  ? MaterialModelDefinitionMap[Key]
  : Readonly<{
      key: Key
      kind: 'sampled_relation'
      input: Readonly<{ quantity_kind: QuantityKindName }>
      output: Readonly<{ quantity_kind: QuantityKindName }>
      minimum_samples: number
      shared_basis: boolean
    }>
export type MaterialCatalogKey = MaterialPropertyKey | MaterialModelKey

type MaterialAuthoringBasis<Name extends QuantityKindName> = Name extends ScalarQuantityKindName
  ? Readonly<{ basis?: never }>
  : Readonly<{ basis?: CartesianBasis }>
type MaterialNormalizedBasis<Name extends QuantityKindName> = Name extends ScalarQuantityKindName
  ? Readonly<{ basis?: never }>
  : Readonly<{ basis: CartesianBasis }>

export type MaterialDataValueDescriptor<
  Key extends MaterialPropertyKey = MaterialPropertyKey,
> = Key extends MaterialPropertyKey ? Readonly<{
  dtype: FloatDataDType
  value: number | readonly unknown[]
  unit: ApplicableUnit<MaterialPropertyQuantityKind<Key>>
  errorRate?: number
  axes?: never
  quantityKind?: never
}> & MaterialAuthoringBasis<MaterialPropertyQuantityKind<Key>> : never

export type NormalizedMaterialDataValueDescriptor<
  Key extends MaterialPropertyKey = MaterialPropertyKey,
> = Key extends MaterialPropertyKey ? Readonly<{
  dtype: FloatDataDType
  value: number | readonly unknown[]
  unit: UcumUnit
  quantityKind: MaterialPropertyQuantityKind<Key>
  errorRate: number
  axes?: never
}> & MaterialNormalizedBasis<MaterialPropertyQuantityKind<Key>> : never

type MaterialModelInputQuantityKind<Key extends MaterialModelKey> =
  MaterialModelDefinitionFor<Key>['input']['quantity_kind']
type MaterialModelOutputQuantityKind<Key extends MaterialModelKey> =
  MaterialModelDefinitionFor<Key>['output']['quantity_kind']
export type MaterialQuantitySeries<Name extends QuantityKindName> = Readonly<{
  unit: ApplicableUnit<Name>
  values: readonly unknown[]
}> & MaterialAuthoringBasis<Name>
export type MaterialSampledRelation<
  Key extends MaterialModelKey = MaterialModelKey,
> = Key extends MaterialModelKey ? Readonly<{
  kind: 'sampled_relation'
  input: MaterialQuantitySeries<MaterialModelInputQuantityKind<Key>>
  output: MaterialQuantitySeries<MaterialModelOutputQuantityKind<Key>>
}> : never

export type MaterialVariable = string | MaterialDataValueDescriptor | MaterialSampledRelation
export type MaterialVariables = keyof MaterialPropertyQuantityKindMap extends never
  ? Readonly<Record<string, unknown> & { color?: string; errorRate?: number }>
  : Readonly<
      { [Key in keyof MaterialPropertyQuantityKindMap]?: MaterialDataValueDescriptor<Key> } &
      { [Key in keyof MaterialModelDefinitionMap]?: MaterialSampledRelation<Key> } &
      { color?: string; errorRate?: number }
    >
export type NormalizedMaterialVariables = keyof MaterialPropertyQuantityKindMap extends never
  ? Readonly<Record<string, unknown> & { color?: string }>
  : Readonly<
      { [Key in keyof MaterialPropertyQuantityKindMap]?: NormalizedMaterialDataValueDescriptor<Key> } &
      { [Key in keyof MaterialModelDefinitionMap]?: MaterialSampledRelation<Key> } &
      { color?: string }
    >
export type ResolvedMaterialVariables = NormalizedMaterialVariables
// </generated:material-catalog-types>`
}

function quantityKindFacade() {
  return `import { activeCatalogRuntimeSlice } from '../catalog/runtime'
import { QuantityKindEntry } from './runtime'
import type { QuantityKindDefinition, QuantityKindName } from './runtime'

export type {
  ApplicableUnit, CartesianBasis, QuantityKindComponentShape, QuantityKindComponentValue,
  QuantityKindDefinition, QuantityKindDomain, QuantityKindName, QuantityKindNameForDomain,
  QuantityKindTensorOrder, QuantityMetadata, QuantityValueReference, ScalarQuantityKindName,
  TensorQuantityKindName,
} from './runtime'
export { transformQuantityValue } from './runtime'
export { identityCartesianBasis } from './identityBasis'

export const QuantityKind = new Proxy(Object.create(null) as Record<string, QuantityKindDefinition<string>>, {
  get(target, name) {
    if (typeof name !== 'string') return undefined
    if (!activeCatalogRuntimeSlice().quantityKinds.some((entry) => entry.name === name)) return undefined
    target[name] ??= new QuantityKindEntry(name)
    return target[name]
  },
  has(_target, name) {
    return typeof name === 'string' && activeCatalogRuntimeSlice().quantityKinds.some((entry) => entry.name === name)
  },
  ownKeys() { return activeCatalogRuntimeSlice().quantityKinds.map((entry) => entry.name) },
  getOwnPropertyDescriptor(_target, name) {
    return typeof name === 'string' && activeCatalogRuntimeSlice().quantityKinds.some((entry) => entry.name === name)
      ? { configurable: true, enumerable: true }
      : undefined
  },
}) as Readonly<Record<QuantityKindName, QuantityKindDefinition<QuantityKindName>>>
`
}

const coreDeclarationPath = path.join(root, 'src/lib/cad/api/caemble-core.d.ts')
const coreDeclaration = await formatGenerated(
  'src/lib/cad/api/caemble-core.d.ts',
  await readFile(coreDeclarationPath, 'utf8').then((source) =>
    source
      .replace(
        /^\/\/ @caemble\/core declaration version: .*$/m,
        '// Generated @caemble/core declaration.',
      )
      .replace(
        /\/\/ <generated:primitive-authoring-bindings>[\s\S]*?\/\/ <\/generated:primitive-authoring-bindings>/,
        primitiveAuthoringDeclarations(),
      )
      .replace(
        /\/\/ <generated:quantity-kind-types>[\s\S]*?\/\/ <\/generated:quantity-kind-types>/,
        quantityKindTypes(),
      )
      .replace(
        /\/\/ <generated:material-catalog-types>[\s\S]*?\/\/ <\/generated:material-catalog-types>/,
        materialCatalogTypes(),
      ),
  ),
)
const jsxDeclaration = await formatGenerated('src/lib/cad/api/cad-jsx.d.ts', generatedJsxDeclaration())
await Promise.all([
  emit('src/lib/cad/elements/generated.ts', generatedElementRegistry()),
  emit('src/lib/cad/api/cad-jsx.d.ts', jsxDeclaration),
  emit('src/lib/cad/api/caemble-core.d.ts', coreDeclaration),
  emit('src/lib/quantitykind/index.ts', await formatGenerated('src/lib/quantitykind/index.ts', quantityKindFacade())),
])

const [authoringReferenceModule, generatedElementsModule] = await Promise.all([
  loadBundledModule(path.join(root, 'src/lib/cad/authoringReference.ts')),
  loadBundledModule(path.join(root, 'src/lib/cad/elements/generated.ts')),
])
const geometrySkeletonExperiment = catalogQuery(
  'experiment',
  'geometry-authoring-skeleton',
  '1.0.0',
  '--namespace',
  'caemble',
  '--repository',
  'getting-started',
)
const authoringReferencePayload = authoringReferenceModule.buildCadAuthoringReference({
  authoringContract: generatedElementsModule.cadAuthoringContract,
  elements: generatedElementsModule.cadElementCatalog,
  experimentSkeleton: geometrySkeletonExperiment.sourceBundle.files['experiment.tsx'],
  geometrySkeleton: geometrySkeletonExperiment.sourceBundle.files['geometry.tsx'],
})
await emit('../api/app/ai/cad_authoring_reference.json', `${JSON.stringify(authoringReferencePayload, null, 2)}\n`)

if (changed.length > 0) {
  console.log(`Updated generated CAD API files:\n${changed.map((file) => `- ${file}`).join('\n')}`)
}
