// Generated by python -m app.solver_framework.codegen. Do not edit.
import { defineKernelTask } from '../authoring'
import type { KernelDescriptor, KernelTaskConfig } from '../kernelContract'

export const dcCurrentDensityDescriptor = Object.freeze({
  name: 'dc-current-density',
  version: '0.0.0',
  description: 'Solves steady-state electric potential and requested current outputs in one conductor.',
  referenceLengthUnit: 'm',
  minimumOutputs: 1,
  parameters: {
    relativeTolerance: {
      description: 'Relative convergence tolerance for the preconditioned conjugate-gradient solve.',
      data: {
        dtype: 'float64',
        quantityKind: 'DimensionlessRatio',
        unit: '{fraction}',
        minimum: 0,
        maximum: 1,
        exclusiveMinimum: true,
        exclusiveMaximum: true,
      },
    },
    maxIterations: {
      description: 'Maximum number of solver iterations.',
      data: {
        dtype: 'int32',
        minimum: 1,
      },
    },
  },
  materials: [
    {
      role: 'conductor',
      description: 'The homogeneous isotropic conductor targeted by dc.voxel-grid.',
      target: {
        category: 'initializations',
        methodId: 'dc.voxel-grid',
      },
      properties: {
        'electrical.conductivity': {
          description: 'Positive isotropic electrical-conductivity tensor in the global identity basis.',
          data: {
            dtype: 'float64',
            quantityKind: 'electromagnetism.ElectricConductivity',
            unit: 'S.m-1',
            basis: [
              [1, 0, 0],
              [0, 1, 0],
              [0, 0, 1],
            ],
          },
        },
      },
    },
  ],
  inputPorts: {},
  observations: {
    iterations: {
      description: 'Number of completed PCG iterations.',
      type: 'number',
    },
    relativeResidual: {
      description: 'Final relative residual of the PCG solve.',
      type: 'number',
    },
  },
  methods: {
    initializations: [
      {
        methodId: 'dc.voxel-grid',
        description: 'Defines the cell-centered conductor voxel grid in axial, u, and v order.',
        minimumOccurrences: 1,
        maximumOccurrences: 1,
        target: {
          source: 'structure',
          kind: 'geometry',
          minimumTargets: 1,
          maximumTargets: 1,
          minimumResolved: 1,
          maximumResolved: 1,
        },
        parameters: {
          gridShape: {
            description: 'Number of cells along the s, u, and v grid axes.',
            data: {
              dtype: 'int32',
              axes: [
                {
                  length: 3,
                },
              ],
              minimum: 3,
            },
          },
        },
      },
    ],
    boundaryConditions: [
      {
        methodId: 'dc.source-potential',
        description: 'Applies the source terminal electric potential.',
        minimumOccurrences: 1,
        maximumOccurrences: 1,
        target: {
          source: 'structure',
          kind: 'surface',
          minimumTargets: 1,
          maximumTargets: 1,
          minimumResolved: 1,
          maximumResolved: 1,
        },
        parameters: {
          voltage: {
            description: 'Source terminal electric potential.',
            data: {
              dtype: 'float64',
              quantityKind: 'electromagnetism.Voltage',
              unit: 'V',
            },
          },
        },
      },
      {
        methodId: 'dc.reference-potential',
        description: 'Applies the reference terminal electric potential.',
        minimumOccurrences: 1,
        maximumOccurrences: 1,
        target: {
          source: 'structure',
          kind: 'surface',
          minimumTargets: 1,
          maximumTargets: 1,
          minimumResolved: 1,
          maximumResolved: 1,
        },
        parameters: {
          voltage: {
            description: 'Reference terminal electric potential.',
            data: {
              dtype: 'float64',
              quantityKind: 'electromagnetism.Voltage',
              unit: 'V',
            },
          },
        },
      },
    ],
    outputs: [
      {
        methodId: 'dc.current-density',
        description: 'Produces a two-dimensional current-density cross-section.',
        minimumOccurrences: 0,
        maximumOccurrences: 9007199254740991,
        target: {
          source: 'structure',
          kind: 'geometry',
          minimumTargets: 1,
          maximumTargets: 1,
          minimumResolved: 1,
          maximumResolved: 1,
        },
        parameters: {
          crossSectionPosition: {
            description: 'Normalized axial position of the requested cross-section.',
            data: {
              dtype: 'float64',
              quantityKind: 'DimensionlessRatio',
              unit: '{fraction}',
              minimum: 0,
              maximum: 1,
              exclusiveMinimum: true,
              exclusiveMaximum: true,
            },
          },
        },
        artifactType: 'caemble.dc/current-density@1',
        data: {
          dtype: 'float64',
          quantityKind: 'electromagnetism.ElectricCurrentDensity',
          unit: 'A.m-2',
          basis: [
            [1, 0, 0],
            [0, 1, 0],
            [0, 0, 1],
          ],
          axes: [
            {
              name: 'cross-section v',
              quantityKind: 'Length',
              unit: 'm',
            },
            {
              name: 'cross-section u',
              quantityKind: 'Length',
              unit: 'm',
            },
          ],
        },
      },
      {
        methodId: 'dc.total-current',
        description: 'Produces absolute current integrated over a cross-section.',
        minimumOccurrences: 0,
        maximumOccurrences: 9007199254740991,
        target: {
          source: 'structure',
          kind: 'geometry',
          minimumTargets: 1,
          maximumTargets: 1,
          minimumResolved: 1,
          maximumResolved: 1,
        },
        parameters: {
          crossSectionPosition: {
            description: 'Normalized axial position of the requested cross-section.',
            data: {
              dtype: 'float64',
              quantityKind: 'DimensionlessRatio',
              unit: '{fraction}',
              minimum: 0,
              maximum: 1,
              exclusiveMinimum: true,
              exclusiveMaximum: true,
            },
          },
        },
        artifactType: 'caemble.dc/total-current@1',
        data: {
          dtype: 'float64',
          quantityKind: 'electromagnetism.ElectricCurrent',
          unit: 'A',
        },
      },
      {
        methodId: 'dc.joule-heating',
        description: 'Produces volumetric Joule heating on the conductor voxel grid.',
        minimumOccurrences: 0,
        maximumOccurrences: 1,
        target: {
          source: 'structure',
          kind: 'geometry',
          minimumTargets: 1,
          maximumTargets: 1,
          minimumResolved: 1,
          maximumResolved: 1,
        },
        parameters: {},
        artifactType: 'caemble.dc/joule-heating@1',
        data: {
          dtype: 'float64',
          quantityKind: 'PowerDensity',
          unit: 'W.m-3',
          axes: [
            {
              name: 'axial position',
              quantityKind: 'Length',
              unit: 'm',
            },
            {
              name: 'cross-section v',
              quantityKind: 'Length',
              unit: 'm',
            },
            {
              name: 'cross-section u',
              quantityKind: 'Length',
              unit: 'm',
            },
          ],
        },
      },
    ],
  },
}) as unknown as KernelDescriptor

export const dcCurrentDensityKernelRef = Object.freeze({
  name: dcCurrentDensityDescriptor.name,
  version: dcCurrentDensityDescriptor.version,
})

export function dcCurrentDensity(config: KernelTaskConfig) {
  return defineKernelTask(dcCurrentDensityDescriptor, config)
}

export const steadyStateHeatDescriptor = Object.freeze({
  name: 'steady-state-heat',
  version: '0.0.0',
  description: 'Solves steady-state heat conduction with fixed-temperature ends and adiabatic side walls.',
  referenceLengthUnit: 'm',
  minimumOutputs: 1,
  parameters: {
    relativeTolerance: {
      description: 'Relative convergence tolerance for the preconditioned conjugate-gradient solve.',
      data: {
        dtype: 'float64',
        quantityKind: 'DimensionlessRatio',
        unit: '{fraction}',
        minimum: 0,
        maximum: 1,
        exclusiveMinimum: true,
        exclusiveMaximum: true,
      },
    },
    maxIterations: {
      description: 'Maximum number of solver iterations.',
      data: {
        dtype: 'int32',
        minimum: 1,
      },
    },
  },
  materials: [
    {
      role: 'thermalDomain',
      description: 'The homogeneous isotropic thermal domain targeted by heat.voxel-grid.',
      target: {
        category: 'initializations',
        methodId: 'heat.voxel-grid',
      },
      properties: {
        'thermal.conductivity': {
          description: 'Positive isotropic thermal-conductivity tensor in the global identity basis.',
          data: {
            dtype: 'float64',
            quantityKind: 'thermodynamics.ThermalConductivity',
            unit: 'W.m-1.K-1',
            basis: [
              [1, 0, 0],
              [0, 1, 0],
              [0, 0, 1],
            ],
          },
        },
      },
    },
  ],
  inputPorts: {
    heatSource: {
      description: 'Optional volumetric heat source sampled on the same voxel grid.',
      artifactTypes: ['caemble.dc/joule-heating@1'],
      minimumOccurrences: 0,
      maximumOccurrences: 1,
      data: {
        dtype: 'float64',
        quantityKind: 'PowerDensity',
        unit: 'W.m-3',
        axes: [
          {
            name: 'axial position',
            quantityKind: 'Length',
            unit: 'm',
          },
          {
            name: 'cross-section v',
            quantityKind: 'Length',
            unit: 'm',
          },
          {
            name: 'cross-section u',
            quantityKind: 'Length',
            unit: 'm',
          },
        ],
      },
    },
  },
  observations: {
    iterations: {
      description: 'Number of completed PCG iterations.',
      type: 'number',
    },
    relativeResidual: {
      description: 'Final relative residual of the PCG solve.',
      type: 'number',
    },
  },
  methods: {
    initializations: [
      {
        methodId: 'heat.voxel-grid',
        description: 'Defines the cell-centered thermal voxel grid in axial, u, and v order.',
        minimumOccurrences: 1,
        maximumOccurrences: 1,
        target: {
          source: 'structure',
          kind: 'geometry',
          minimumTargets: 1,
          maximumTargets: 1,
          minimumResolved: 1,
          maximumResolved: 1,
        },
        parameters: {
          gridShape: {
            description: 'Number of cells along the s, u, and v grid axes.',
            data: {
              dtype: 'int32',
              axes: [
                {
                  length: 3,
                },
              ],
              minimum: 3,
            },
          },
        },
      },
    ],
    boundaryConditions: [
      {
        methodId: 'heat.fixed-temperature',
        description: 'Applies a fixed temperature to one complete end surface.',
        minimumOccurrences: 2,
        maximumOccurrences: 2,
        target: {
          source: 'structure',
          kind: 'surface',
          minimumTargets: 1,
          maximumTargets: 1,
          minimumResolved: 1,
          maximumResolved: 1,
        },
        parameters: {
          temperature: {
            description: 'Fixed surface temperature.',
            data: {
              dtype: 'float64',
              quantityKind: 'thermodynamics.Temperature',
              unit: 'K',
              minimum: 0,
            },
          },
        },
      },
    ],
    outputs: [
      {
        methodId: 'heat.temperature',
        description: 'Produces the three-dimensional voxel temperature field.',
        minimumOccurrences: 0,
        maximumOccurrences: 1,
        target: {
          source: 'structure',
          kind: 'geometry',
          minimumTargets: 1,
          maximumTargets: 1,
          minimumResolved: 1,
          maximumResolved: 1,
        },
        parameters: {},
        artifactType: 'caemble.heat/temperature@1',
        data: {
          dtype: 'float64',
          quantityKind: 'thermodynamics.Temperature',
          unit: 'K',
          axes: [
            {
              name: 'axial position',
              quantityKind: 'Length',
              unit: 'm',
            },
            {
              name: 'cross-section v',
              quantityKind: 'Length',
              unit: 'm',
            },
            {
              name: 'cross-section u',
              quantityKind: 'Length',
              unit: 'm',
            },
          ],
        },
      },
      {
        methodId: 'heat.maximum-temperature',
        description: 'Produces the maximum temperature among occupied voxel cells.',
        minimumOccurrences: 0,
        maximumOccurrences: 1,
        target: {
          source: 'structure',
          kind: 'geometry',
          minimumTargets: 1,
          maximumTargets: 1,
          minimumResolved: 1,
          maximumResolved: 1,
        },
        parameters: {},
        artifactType: 'caemble.heat/maximum-temperature@1',
        data: {
          dtype: 'float64',
          quantityKind: 'thermodynamics.Temperature',
          unit: 'K',
        },
      },
    ],
  },
}) as unknown as KernelDescriptor

export const steadyStateHeatKernelRef = Object.freeze({
  name: steadyStateHeatDescriptor.name,
  version: steadyStateHeatDescriptor.version,
})

export function steadyStateHeat(config: KernelTaskConfig) {
  return defineKernelTask(steadyStateHeatDescriptor, config)
}

const productionKernelCatalog = Object.freeze([
  Object.freeze({
    authoringName: 'dcCurrentDensity',
    builder: dcCurrentDensity,
    descriptor: dcCurrentDensityDescriptor,
  }),
  Object.freeze({
    authoringName: 'steadyStateHeat',
    builder: steadyStateHeat,
    descriptor: steadyStateHeatDescriptor,
  }),
])

export const kernelModules = Object.freeze(
  productionKernelCatalog.map(({ descriptor }) => Object.freeze({ descriptor })),
)

export const kernelAuthoring = Object.freeze(
  Object.fromEntries(productionKernelCatalog.map(({ authoringName, builder }) => [authoringName, builder])),
)
