import page0 from '../../../../docs/manual/workbench/workbench-quickstart.md?raw'
import page1 from '../../../../docs/manual/workbench/workbench-authoring-cycle.md?raw'
import page2 from '../../../../docs/manual/workbench/workbench-calculation.md?raw'
import page3 from '../../../../docs/manual/workbench/workbench-prediction.md?raw'
import page4 from '../../../../docs/manual/workbench/workbench-admin-demo-curation.md?raw'
import page5 from '../../../../docs/manual/workbench/workbench-analysis.md?raw'
import page6 from '../../../../docs/manual/workbench/workbench-viewer-selection.md?raw'
import page7 from '../../../../docs/manual/program/program-overview.md?raw'
import page8 from '../../../../docs/manual/program/program-definition.md?raw'
import page9 from '../../../../docs/manual/program/program-materials.md?raw'
import page10 from '../../../../docs/manual/program/program-task.md?raw'
import page11 from '../../../../docs/manual/program/program-ray-tracing.md?raw'
import page12 from '../../../../docs/manual/program/program-simulate.md?raw'
import page13 from '../../../../docs/manual/program/program-runtime-rules.md?raw'
import page14 from '../../../../docs/manual/program/program-domain-recording.md?raw'
import page15 from '../../../../docs/manual/program/program-verified-examples.md?raw'
import page16 from '../../../../docs/manual/program/program-multiphysics-example.md?raw'
import page17 from '../../../../docs/manual/reference/reference-source-import.md?raw'
import page18 from '../../../../docs/manual/reference/reference-geometry-skeleton.md?raw'
import page19 from '../../../../docs/manual/reference/reference-geometry-transforms.md?raw'
import page20 from '../../../../docs/manual/reference/reference-geometry-identity.md?raw'
import page21 from '../../../../docs/manual/reference/reference-geometry-elements.md?raw'
import page22 from '../../../../docs/manual/reference/reference-core-api.md?raw'
import page23 from '../../../../docs/manual/reference/reference-data-schema.md?raw'
import page24 from '../../../../docs/manual/reference/reference-targets-results.md?raw'
import page25 from '../../../../docs/manual/troubleshooting/troubleshooting-ready.md?raw'
import page26 from '../../../../docs/manual/troubleshooting/troubleshooting-target-manifest.md?raw'
import page27 from '../../../../docs/manual/troubleshooting/troubleshooting-units-materials.md?raw'
import page28 from '../../../../docs/manual/troubleshooting/troubleshooting-runtime-results.md?raw'
import particlePage from '../../../../docs/manual/program/program-particles.md?raw'
import showcasePage from '../../../../docs/manual/workbench/workbench-showcase.md?raw'
import measurementPage from '../../../../docs/manual/workbench/workbench-measurement.md?raw'
import savePage from '../../../../docs/manual/workbench/workbench-save.md?raw'
import type { DocumentPage } from './types'
import { manualBody } from './body'

export const manualDocuments: readonly DocumentPage[] = [
  {
    ...{
      id: 'workbench-quickstart',
      section: 'workbench',
      anchor: 'workbench-quickstart',
      title: 'CAE Workbench 빠른 시작',
      summary: '예제를 열고 조건 하나를 바꿔 실행한 뒤, 첫 결과를 확인하는 과정을 함께 따라갑니다.',
      keywords: [
        'Quickstart',
        '시작',
        'Candidate',
        'Measurement',
        'Prepared',
        'Recorded',
        'Launcher',
        'Ready',
        '처음',
        '입문',
        '실행',
        '예제',
      ],
    },
    sourcePath: 'docs/manual/workbench/workbench-quickstart.md',
    content: manualBody(page0),
  },
  {
    ...{
      id: 'workbench-authoring-cycle',
      section: 'workbench',
      anchor: 'workbench-authoring-cycle',
      title: '편집, Candidate 생성과 실행 결과의 관계',
      summary: '실험 설계와 변수 조건, 실행 기록의 차이를 익히고 무엇이 저장되는지 알아봅니다.',
      keywords: [
        'Dirty',
        'Checking',
        'Compiling',
        'Evaluating',
        'Validating Models',
        'Candidate',
        'Prepared',
        'Recorded',
        '기본 개념',
        '변수',
        '후보',
        '실행 기록',
        '저장',
      ],
    },
    sourcePath: 'docs/manual/workbench/workbench-authoring-cycle.md',
    content: manualBody(page1),
  },
  {
    ...{
      id: 'workbench-calculation',
      section: 'workbench',
      anchor: 'workbench-calculation',
      title: 'Calculation으로 결과 계산하기',
      summary: '실행 결과에서 필요한 값을 계산하고, 미리보기부터 계산식과 후처리 데이터 저장까지 안내합니다.',
      keywords: [
        'Calculation',
        'Vars',
        'Candidate',
        'RecordedData',
        'Math.js',
        'mathjs',
        'Output',
        'scalar',
        'line',
        'heatmap',
        '후처리',
        '평균',
        '계산식',
        '미리보기',
        '저장',
      ],
    },
    sourcePath: 'docs/manual/workbench/workbench-calculation.md',
    content: manualBody(page2),
  },
  {
    ...{
      id: 'workbench-prediction',
      section: 'workbench',
      anchor: 'workbench-prediction',
      title: 'Prediction으로 결과와 조건 예측하기',
      summary: '기존 결과로 새 조건을 예측하고, 목표에 맞는 조건을 찾아 실제 계산으로 확인합니다.',
      keywords: [
        'Prediction',
        'Forward',
        'Inverse',
        'kNN',
        'k-Nearest Neighbor',
        'Vars',
        'RecordedData',
        'CalculationData',
        'Save & Run',
        'Validation',
        '예측',
        '목표',
        '조건 탐색',
        '학습',
      ],
    },
    sourcePath: 'docs/manual/workbench/workbench-prediction.md',
    content: manualBody(page3),
  },
  {
    ...{
      id: 'workbench-admin-demo-curation',
      section: 'workbench',
      anchor: 'workbench-admin-demo-curation',
      title: '관리자를 위한 공개 Demo 설정',
      summary: '관리자가 공개 Demo의 순서와 대표 항목을 정하고 공개 범위를 확인하는 방법입니다.',
      keywords: ['Admin', 'Demo', 'Curation', 'Model Catalog', 'Users', '공개', '대표 Demo', '관리자', '공개 예제'],
    },
    sourcePath: 'docs/manual/workbench/workbench-admin-demo-curation.md',
    content: manualBody(page4),
  },
  {
    ...{
      id: 'workbench-analysis',
      section: 'workbench',
      anchor: 'workbench-analysis',
      title: 'Analysis로 변수와 결과의 관계 살펴보기',
      summary: '저장된 후처리 결과를 비교하고 변수와 결과의 관계를 살펴보며 데이터를 내보냅니다.',
      keywords: [
        'Analysis',
        'Explore',
        'Pearson',
        'Spearman',
        'Mining',
        'PCA',
        'CSV',
        '분석',
        '상관관계',
        '내보내기',
        '후처리',
      ],
    },
    sourcePath: 'docs/manual/workbench/workbench-analysis.md',
    content: manualBody(page5),
  },
  {
    ...{
      id: 'workbench-viewer-selection',
      section: 'workbench',
      anchor: 'workbench-viewer-selection',
      title: '3D Viewer에서 형상과 결과 살펴보기',
      summary: '3D 화면에서 형상과 결과를 살펴보고, 부품과 표면의 ID를 코드와 연결해 확인합니다.',
      keywords: [
        'Viewer',
        'Geometry ID',
        'Surface ID',
        'selection',
        '전역 경로',
        'surface',
        '결과 보기',
        '표면',
        '부품',
        '뷰어',
      ],
    },
    sourcePath: 'docs/manual/workbench/workbench-viewer-selection.md',
    content: manualBody(page6),
  },
  {
    ...{
      id: 'program-overview',
      section: 'program',
      anchor: 'experiment-program-overview',
      aliases: ['experiment-program-mental-model', 'experiment-physical-model'],
      title: 'Experiment 파일 구성 이해하기',
      summary: '변수·형상·재료·해석 작업과 실행 순서를 어떤 파일에 작성하는지 안내합니다.',
      keywords: [
        'Experiment Program',
        'experiment.tsx',
        'geometry.tsx',
        'material.tsx',
        'tasks',
        'simulate.py',
        'orchestration',
        '파일 구성',
        '소스',
        '실험',
      ],
    },
    sourcePath: 'docs/manual/program/program-overview.md',
    content: manualBody(page7),
  },
  {
    ...{
      id: 'program-definition',
      section: 'program',
      anchor: 'experiment-program-definition',
      aliases: ['experiment-vars-geometry'],
      title: 'experiment.tsx: 변수와 저장할 결과 정하기',
      summary: '변수 범위와 배열 모양을 정하고 Task의 출력을 저장 결과에 연결합니다.',
      keywords: [
        'experiment()',
        'varsSchema',
        'recordedData',
        'DataSchema',
        'Measurement',
        '변수',
        '저장 결과',
        '배열',
      ],
    },
    sourcePath: 'docs/manual/program/program-definition.md',
    content: manualBody(page8),
  },
  {
    ...{
      id: 'program-materials',
      section: 'program',
      anchor: 'experiment-program-materials',
      aliases: ['experiment-materials', 'experiment-program-material-roles'],
      title: '재료의 물성을 정하고 형상에 연결하기',
      summary: '재료 모델과 계수를 입력하고 형상의 역할 및 재료 사이의 상호작용에 연결합니다.',
      keywords: [
        'Material',
        'material.tsx',
        'role map',
        'body',
        'Mat',
        'canonical key',
        'dtype',
        'unit',
        'modelGroups',
        'tire',
        'wheel',
        '재료',
        '물성',
        '계수',
        '접촉',
      ],
    },
    sourcePath: 'docs/manual/program/program-materials.md',
    content: manualBody(page9),
  },
  {
    ...{
      id: 'program-task',
      section: 'program',
      anchor: 'experiment-program-task',
      aliases: ['experiment-program-minimal-pair', 'experiment-program-kernel-limits', 'experiment-program-methods'],
      title: 'tasks/*.tsx: 해석 작업 설정하기',
      summary: 'Solver와 대상을 선택하고 초기조건·경계조건·출력 설정을 읽는 순서를 안내합니다.',
      keywords: [
        'defineTask',
        'kernel',
        'config',
        'parameters',
        'initializations',
        'boundaryConditions',
        'outputs',
        '해석 작업',
        '경계조건',
        '출력',
      ],
    },
    sourcePath: 'docs/manual/program/program-task.md',
    content: manualBody(page10),
  },
  {
    ...{
      id: 'program-ray-tracing',
      section: 'program',
      anchor: 'experiment-program-ray-tracing',
      aliases: ['non-sequential-ray-tracing', 'ray-tracing-thin-film'],
      title: '광선 추적: 광원부터 검출 결과까지',
      summary: '광원·재료·검출기 설정부터 광선 경로, 픽셀 전력과 분광기 결과 해석까지 안내합니다.',
      keywords: [
        'ray-tracing@5.1.0',
        'paraxial lens',
        'Image Spectrometer',
        '영상분광기',
        '주평면',
        'OV9281',
        'non-sequential',
        'point source',
        'area source',
        'directional source',
        'Lambertian source',
        'Stokes',
        'ABg',
        'Henyey-Greenstein',
        'detector',
        'thin film',
        'TMM',
        '50 um',
        'frequency',
        'ray paths',
        '광선 추적',
        '광원',
        '검출기',
        '비순차',
      ],
    },
    sourcePath: 'docs/manual/program/program-ray-tracing.md',
    content: manualBody(page11),
  },
  {
    id: 'program-particles',
    section: 'program',
    anchor: 'experiment-program-particles',
    title: '입자 해석: DEM, SPH, MPM',
    summary: '입자 예제를 선택하고 설정 위치, 시간에 따른 움직임과 수치 결과를 확인합니다.',
    keywords: [
      'particles',
      'DEM',
      'SPH',
      'MPM',
      '입자',
      '접촉',
      '유체',
      '압축',
      'MaterialInteraction',
      '입자 예제',
      '움직임',
    ],
    sourcePath: 'docs/manual/program/program-particles.md',
    content: manualBody(particlePage),
  },
  {
    ...{
      id: 'program-simulate',
      section: 'program',
      anchor: 'experiment-program-simulate',
      title: 'simulate.py: 해석을 실행하고 결과 기록하기',
      summary: 'Task 실행 순서와 중간 데이터 전달, 상태 유지, 최종 결과 기록 방법을 설명합니다.',
      keywords: [
        'simulate',
        'sim.run',
        'sim.record',
        'sim.release',
        'artifact',
        'state',
        'inputs',
        '실행 순서',
        '결과 기록',
      ],
    },
    sourcePath: 'docs/manual/program/program-simulate.md',
    content: manualBody(page12),
  },
  {
    ...{
      id: 'program-runtime-rules',
      section: 'program',
      anchor: 'experiment-program-runtime-rules',
      aliases: ['experiment-program-troubleshooting'],
      title: '실행 상태와 중간 데이터 안전하게 다루기',
      summary: '반복 계산에서 필요한 상태를 남기고 데이터를 해제하며 실패 시 기록 범위를 확인합니다.',
      keywords: [
        'state',
        'artifact',
        'rollback',
        'provisional',
        'ACK',
        'fatal',
        'release',
        '상태',
        '중간 데이터',
        '반복 계산',
      ],
    },
    sourcePath: 'docs/manual/program/program-runtime-rules.md',
    content: manualBody(page13),
  },
  {
    ...{
      id: 'program-domain-recording',
      section: 'program',
      anchor: 'experiment-program-domain-recording',
      title: '해석 결과를 기록하고 Viewer에서 확인하기',
      summary: '수치 기록과 자동 시각화를 구분하고 축·성분·시간에 맞춰 결과를 살펴봅니다.',
      keywords: [
        'RecordedData',
        'FieldValue',
        'domain',
        'mesh',
        'connectivity',
        'quantity',
        'valueUnit',
        '결과',
        '시각화',
        '시간 이력',
      ],
    },
    sourcePath: 'docs/manual/program/program-domain-recording.md',
    content: manualBody(page14),
  },
  {
    ...{
      id: 'program-verified-examples',
      section: 'program',
      anchor: 'experiment-program-examples',
      aliases: ['experiment-verified-example'],
      title: '공식 예제로 익히는 Experiment',
      summary: '배우고 싶은 내용에 맞는 예제를 고르고 내 실험으로 바꾸는 순서를 안내합니다.',
      keywords: [
        'program examples',
        'DC',
        'current density',
        'notched',
        'electro thermal',
        'multiphysics',
        '공식 예제',
        '따라하기',
      ],
    },
    sourcePath: 'docs/manual/program/program-verified-examples.md',
    content: manualBody(page15),
  },
  {
    ...{
      id: 'program-multiphysics-example',
      section: 'program',
      anchor: 'experiment-program-multiphysics',
      title: '전기·열 복합해석 따라 읽기',
      summary: '홈이 있는 막대의 전기 해석에서 발열을 열 해석으로 전달하는 흐름을 살펴봅니다.',
      keywords: [
        'multiphysics',
        'Joule heating',
        'heatSource',
        'electric',
        'thermal',
        '복합해석',
        '전기',
        '열',
        '발열',
      ],
      collapsed: true,
    },
    sourcePath: 'docs/manual/program/program-multiphysics-example.md',
    content: manualBody(page16),
  },
  {
    ...{
      id: 'reference-source-import',
      section: 'reference',
      anchor: 'cad-reference-overview',
      aliases: ['cad-reference-source-import'],
      title: '소스 파일과 import 규칙',
      summary: '같은 소스 묶음의 파일을 가져오고 저장된 실험과 Calculation을 새 버전으로 이어갑니다.',
      keywords: [
        'CAD Reference',
        '@caemble/core',
        'import',
        'default export',
        'compile',
        'evaluate',
        '소스 파일',
        '저장',
        '새 버전',
      ],
    },
    sourcePath: 'docs/manual/reference/reference-source-import.md',
    content: manualBody(page17),
  },
  {
    ...{
      id: 'reference-geometry-skeleton',
      section: 'reference',
      anchor: 'cad-reference-geometry-skeleton',
      title: 'Geometry 작성의 기본 구조와 좌표계',
      summary: '재사용할 형상 함수의 기본값, 길이 단위와 좌표계를 익히고 반복 부품을 배치합니다.',
      keywords: [
        'CAD API v1',
        'geometry.tsx',
        'Geometry',
        'PascalCase',
        'loop',
        'control flow',
        'right-handed',
        'lengthUnit',
        '좌표계',
        '형상',
        '기본값',
        '좌표',
      ],
    },
    sourcePath: 'docs/manual/reference/reference-geometry-skeleton.md',
    content: manualBody(page18),
  },
  {
    ...{
      id: 'reference-geometry-transforms',
      section: 'reference',
      anchor: 'cad-reference-geometry-transforms',
      aliases: ['cad-reference-v7-migration'],
      title: '형상을 이동·회전·확대하는 방법',
      summary: '요소의 변환 속성과 연산 태그를 구분하고 단위와 적용 순서를 확인합니다.',
      keywords: [
        'position',
        'rotation',
        'scale',
        'translate',
        'axis angle',
        'radians',
        'Euler',
        'transform order',
        'pos',
        'rotate',
        '이동',
        '회전',
        '확대',
        '배치',
      ],
    },
    sourcePath: 'docs/manual/reference/reference-geometry-transforms.md',
    content: manualBody(page19),
  },
  {
    ...{
      id: 'reference-geometry-identity',
      section: 'reference',
      anchor: 'cad-reference-geometry-identity',
      title: '형상 ID와 그룹으로 해석 대상 지정하기',
      summary: '부품과 표면에 식별자를 부여하고 그룹을 만들어 Viewer에서 대상을 확인합니다.',
      keywords: [
        'id',
        'identity',
        'geometryGroup',
        'surfaceGroup',
        'numeric surface',
        'surface-N',
        'operation',
        'Fragment',
        '형상 ID',
        '표면',
        '대상 그룹',
      ],
    },
    sourcePath: 'docs/manual/reference/reference-geometry-identity.md',
    content: manualBody(page20),
  },
  {
    ...{
      id: 'reference-geometry-elements',
      section: 'reference',
      anchor: 'cad-reference-geometry-elements',
      title: '기본 형상과 조합 연산 선택하기',
      summary: '기본 요소를 고르고 합치기·빼기·반복 배치와 곡면 작성 규칙을 확인합니다.',
      keywords: [
        'box',
        'cylinder',
        'sphere',
        'fiber',
        'array',
        'shell',
        'union',
        'subtract',
        'intersect',
        'children',
        '기본 형상',
        '조합',
        '곡면',
      ],
    },
    sourcePath: 'docs/manual/reference/reference-geometry-elements.md',
    content: manualBody(page21),
  },
  {
    ...{
      id: 'reference-core-api',
      section: 'reference',
      anchor: 'cad-reference-core-api',
      aliases: ['cad-reference-primitives', 'cad-reference-operations', 'cad-reference-vars-geometry'],
      title: '@caemble/core 핵심 API',
      summary: '형상·재료·해석 작성에 쓰는 공개 API의 역할과 자세한 문법을 찾을 위치를 정리합니다.',
      keywords: ['experiment', 'defineTask', 'Material', 'Mat', 'Geometry', 'Vec3', 'DataSchema', '공개 API', '문법'],
    },
    sourcePath: 'docs/manual/reference/reference-core-api.md',
    content: manualBody(page22),
  },
  {
    ...{
      id: 'reference-data-schema',
      section: 'reference',
      anchor: 'cad-reference-data-schema',
      aliases: ['cad-reference-material'],
      title: '데이터의 모양과 단위 이해하기',
      summary: '자료형, 물리량, UCUM 단위를 확인하고 일반 데이터와 Box Grid 결과의 축을 구분합니다.',
      keywords: [
        'DataSchema',
        'dtype',
        'axes',
        'shape',
        'QuantityKind',
        'UCUM',
        'unit',
        'tensorOrder',
        '단위',
        '데이터 모양',
        '물리량',
      ],
    },
    sourcePath: 'docs/manual/reference/reference-data-schema.md',
    content: manualBody(page23),
  },
  {
    ...{
      id: 'reference-targets-results',
      section: 'reference',
      anchor: 'cad-reference-targets-results',
      aliases: ['cad-reference-task-recorded-data', 'cad-reference-kernels', 'cad-reference-results'],
      title: '해석 대상과 실행 결과의 관계',
      summary: 'target 주소를 읽고 준비된 입력, 중간 상태와 저장 결과의 차이를 확인합니다.',
      keywords: [
        'target',
        'experiment.geometry',
        'task.geometry',
        'run status',
        'RecordedData',
        'trace',
        'provenance',
        '해석 대상',
        '준비 상태',
        '저장 결과',
      ],
    },
    sourcePath: 'docs/manual/reference/reference-targets-results.md',
    content: manualBody(page24),
  },
  {
    ...{
      id: 'troubleshooting-ready',
      section: 'troubleshooting',
      anchor: 'troubleshooting-ready',
      title: '소스가 Ready 상태가 되지 않을 때',
      summary: '소스가 준비되지 않을 때 첫 오류와 파일 위치를 확인하고 단계별로 해결합니다.',
      keywords: [
        'troubleshooting',
        'Ready',
        'compile',
        'evaluate',
        'diagnostic',
        'source error',
        '준비 완료',
        '소스 오류',
        '실행 불가',
      ],
    },
    sourcePath: 'docs/manual/troubleshooting/troubleshooting-ready.md',
    content: manualBody(page25),
  },
  {
    ...{
      id: 'troubleshooting-target-manifest',
      section: 'troubleshooting',
      anchor: 'troubleshooting-target-manifest',
      title: 'Solver 작업과 대상 지정 오류 해결하기',
      summary: '해석 대상과 Solver 설정이 맞지 않을 때 ID, 버전과 입력 규격을 차례로 확인합니다.',
      keywords: [
        'target',
        'manifest',
        'methodId',
        'occurrence',
        'group',
        'solver',
        'invalid_manifest',
        '해석 대상',
        '설정 오류',
        '버전',
      ],
    },
    sourcePath: 'docs/manual/troubleshooting/troubleshooting-target-manifest.md',
    content: manualBody(page26),
  },
  {
    ...{
      id: 'troubleshooting-units-materials',
      section: 'troubleshooting',
      anchor: 'troubleshooting-units-materials',
      title: '단위와 물리량, Material 오류 해결하기',
      summary: '단위, 물리량과 재료 입력의 오류를 구분하고 값과 데이터 모양을 확인합니다.',
      keywords: [
        'invalid_unit',
        'UCUM',
        'QuantityKind',
        'Material',
        'tensor',
        'conductivity',
        '단위 오류',
        '물성',
        '재료 오류',
      ],
    },
    sourcePath: 'docs/manual/troubleshooting/troubleshooting-units-materials.md',
    content: manualBody(page27),
  },
  {
    ...{
      id: 'troubleshooting-runtime-results',
      section: 'troubleshooting',
      anchor: 'troubleshooting-runtime-results',
      title: 'Measurement 실행 또는 결과 오류',
      summary: '실행이 시작되지 않거나 결과가 보이지 않을 때 조건과 작업 상태부터 확인합니다.',
      keywords: [
        'Measurement',
        'artifact',
        'recordedData',
        'stale',
        'failed',
        'cancelled',
        'Launcher',
        '실행 실패',
        '결과 없음',
        '연결',
        '재시도',
      ],
    },
    sourcePath: 'docs/manual/troubleshooting/troubleshooting-runtime-results.md',
    content: manualBody(page28),
  },
  {
    id: 'workbench-showcase',
    section: 'workbench',
    anchor: 'workbench-showcase',
    title: 'Showcase에서 예제 둘러보기',
    summary: '완성된 실험의 형상과 결과를 살펴보고, 관심 있는 작업을 Workbench에서 열어 봅니다.',
    keywords: ['Showcase', 'Demo', '둘러보기', '예제', 'Load', '불러오기', '버전'],
    sourcePath: 'docs/manual/workbench/workbench-showcase.md',
    content: manualBody(showcasePage),
  },
  {
    id: 'workbench-measurement',
    section: 'workbench',
    anchor: 'workbench-measurement',
    title: 'Measurement에서 조건 만들고 실행하기',
    summary: '변수를 조절하고 후보를 실행한 뒤, 예측과 실제 결과를 나란히 비교합니다.',
    keywords: ['Measurement', 'Vars', '변수', '조건', '후보', 'Prepared', 'Run', 'PCA', 'Forward', 'CAE Jobs'],
    sourcePath: 'docs/manual/workbench/workbench-measurement.md',
    content: manualBody(measurementPage),
  },
  {
    id: 'workbench-save',
    section: 'workbench',
    anchor: 'workbench-save',
    title: 'Experiment 저장과 버전 관리',
    summary: '내 실험을 저장하고 새 버전을 만들며, 대표이미지와 처음 보이는 결과를 설정합니다.',
    keywords: ['Save', 'Save As', '저장', '버전', '대표이미지', '초기 화면', 'Preflight'],
    sourcePath: 'docs/manual/workbench/workbench-save.md',
    content: manualBody(savePage),
  },
]
