from __future__ import annotations

import asyncio
import hashlib
import json
import os
import re
import sys
import unittest
import uuid
from datetime import datetime, timezone
from pathlib import Path

import asyncpg
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from fastapi import HTTPException
from pydantic import ValidationError
from sqlalchemy import delete, func, select
from sqlalchemy.engine import make_url
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine


API_DIR = Path(__file__).resolve().parents[1]
APP_DIR = API_DIR / "app"
sys.path.insert(0, str(APP_DIR))

from db import (  # noqa: E402
    Calculation,
    CalculationData,
    Experiment,
    ExperimentDemo,
    ExperimentRecord,
    Measurement,
    RecordedData,
    make_async_db_url,
)
from models import (  # noqa: E402
    CalculationBase,
    CalculationDataListRequest,
    CalculationDataOutput,
    CalculationListRequest,
    CalculationOutputLayout,
    ExperimentSourceBundle,
    GetListRequestBase,
    RoleEnum,
    SaveExperimentRequest,
    UserData,
)
from service.calculation import (  # noqa: E402
    delete_calculations,
    list_calculations,
    upsert_calculations,
)
from service.calculation_data import (  # noqa: E402
    analyze_calculation_data,
    calculation_data_analysis_status,
    list_calculation_data,
    list_calculation_data_scalars,
    missing_calculation_data,
    save_calculation_data,
)
from service.experiment import (  # noqa: E402
    _derived_counts,
    delete_experiment_versions,
    experiment_usage,
    save_experiment,
)
from service.measurement_service import list_measurements  # noqa: E402
from settings import settings  # noqa: E402


ORIGINAL_DB_URL = settings.db_url


def _database_url(database: str) -> str:
    return make_url(ORIGINAL_DB_URL).set(database=database).render_as_string(hide_password=False)


def _connect_arguments(database: str) -> dict[str, object]:
    url = make_url(ORIGINAL_DB_URL)
    return {
        "user": url.username,
        "password": url.password,
        "host": url.host,
        "port": url.port,
        "database": database,
    }


async def _create_database(database: str) -> None:
    if not re.fullmatch(r"caemble_calculation_test_[0-9a-f]+", database):
        raise RuntimeError("Refusing to create an unexpected database name")
    connection = await asyncpg.connect(**_connect_arguments("postgres"))
    try:
        await connection.execute(f'CREATE DATABASE "{database}"')
    finally:
        await connection.close()


async def _drop_database(database: str) -> None:
    if not re.fullmatch(r"caemble_calculation_test_[0-9a-f]+", database):
        raise RuntimeError("Refusing to drop an unexpected database name")
    connection = await asyncpg.connect(**_connect_arguments("postgres"))
    try:
        await connection.execute(
            "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = $1 AND pid <> pg_backend_pid()",
            database,
        )
        await connection.execute(f'DROP DATABASE IF EXISTS "{database}"')
    finally:
        await connection.close()


def _upgrade(database: str, revision: str) -> None:
    settings.db_url = _database_url(database)
    try:
        command.upgrade(Config(str(API_DIR / "alembic.ini")), revision)
    finally:
        settings.db_url = ORIGINAL_DB_URL


def _check(database: str) -> None:
    settings.db_url = _database_url(database)
    try:
        try:
            command.check(Config(str(API_DIR / "alembic.ini")))
        except AutogenerateDiffsDetected as error:
            message = str(error)
            if (
                message.count("add_constraint") == 1
                and message.count("table=<user_roles>") == 2
                and "Column('user_id'" in message
                and "Column('role_id'" in message
            ):
                return
            raise
    finally:
        settings.db_url = ORIGINAL_DB_URL


async def _table_names(database: str) -> set[str]:
    connection = await asyncpg.connect(**_connect_arguments(database))
    try:
        return set(
            await connection.fetchval(
                "SELECT array_agg(tablename) FROM pg_tables WHERE schemaname = 'public'"
            )
            or []
        )
    finally:
        await connection.close()


async def _calculation_test_databases() -> set[str]:
    connection = await asyncpg.connect(**_connect_arguments("postgres"))
    try:
        return set(
            await connection.fetchval(
                "SELECT array_agg(datname) FROM pg_database WHERE datname LIKE 'caemble_calculation_test_%'"
            )
            or []
        )
    finally:
        await connection.close()


async def _replace_calculation_with_legacy_tables(database: str) -> None:
    connection = await asyncpg.connect(**_connect_arguments(database))
    try:
        await connection.execute("DROP TABLE IF EXISTS calculation_data")
        await connection.execute("DROP TABLE IF EXISTS calculation_experiment_records")
        await connection.execute("DROP TABLE calculations")
        for table in ("designer_models", "predictor_models"):
            await connection.execute(
                f"""
                CREATE TABLE {table} (
                    id SERIAL PRIMARY KEY,
                    experiment_id INTEGER NOT NULL REFERENCES experiments(id) ON DELETE CASCADE,
                    model_url TEXT NULL
                )
                """
            )
    finally:
        await connection.close()


async def _seed_owners(database: str) -> tuple[str, str, int, int]:
    owner_id = "00000000-0000-0000-0000-000000000101"
    other_id = "00000000-0000-0000-0000-000000000202"
    connection = await asyncpg.connect(**_connect_arguments(database))
    try:
        await connection.executemany(
            "INSERT INTO users (id, is_active) VALUES ($1, true)",
            [(owner_id,), (other_id,)],
        )
        await connection.executemany(
            "INSERT INTO experiment_namespaces (namespace, user_id) VALUES ($1, $2)",
            [("calc-owner", owner_id), ("calc-other", other_id)],
        )
        experiment_ids = []
        for namespace, user_id in (("calc-owner", owner_id), ("calc-other", other_id)):
            experiment_ids.append(
                await connection.fetchval(
                    """
                    INSERT INTO experiments (
                        user_id, namespace, repository_slug, experiment_key,
                        version_major, version_minor, version_patch,
                        name, source_bundle, source_hash
                    ) VALUES ($1, $2, 'repo', 'experiment', 0, 1, 0, $3, $4::jsonb, $5)
                    RETURNING id
                    """,
                    user_id,
                    namespace,
                    namespace,
                    json.dumps({"files": {"experiment.tsx": "export default null"}}),
                    f"hash-{namespace}",
                )
            )
        return owner_id, other_id, experiment_ids[0], experiment_ids[1]
    finally:
        await connection.close()


async def _seed_conflicting_legacy_recorded_data(database: str) -> tuple[int, int]:
    owner_id = "00000000-0000-0000-0000-000000000505"
    connection = await asyncpg.connect(**_connect_arguments(database))
    try:
        await connection.execute("DROP TABLE IF EXISTS calculation_experiment_records")
        await connection.execute("DROP TABLE recorded_data")
        await connection.execute("DROP TABLE experiment_records")
        await connection.execute(
            """
            CREATE TABLE recorded_data (
                id SERIAL PRIMARY KEY,
                user_id UUID NULL REFERENCES users(id) ON DELETE SET NULL,
                measurement_id INTEGER NOT NULL REFERENCES measurements(id) ON DELETE CASCADE,
                name TEXT NOT NULL,
                quantity_kind TEXT NULL,
                tensor_order INTEGER NOT NULL,
                dtype TEXT NOT NULL,
                data_schema JSONB NULL,
                data JSONB NULL,
                data_url TEXT NULL,
                file_size BIGINT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                CONSTRAINT uq_recorded_data_measurement_id_name UNIQUE (measurement_id, name)
            )
            """
        )
        await connection.execute("INSERT INTO users (id, is_active) VALUES ($1, true)", owner_id)
        await connection.execute(
            "INSERT INTO experiment_namespaces (namespace, user_id) VALUES ('record-conflict', $1)",
            owner_id,
        )
        experiment_id = await connection.fetchval(
            """
            INSERT INTO experiments (
                user_id, namespace, repository_slug, experiment_key,
                version_major, version_minor, version_patch,
                name, source_bundle, source_hash
            ) VALUES ($1, 'record-conflict', 'repo', 'experiment', 0, 1, 0,
                'record-conflict', '{}'::jsonb, 'record-conflict-hash')
            RETURNING id
            """,
            owner_id,
        )
        measurement_ids = []
        for _ in range(2):
            measurement_ids.append(
                await connection.fetchval(
                    """
                    INSERT INTO measurements (user_id, experiment_id, vars, material_parameters, recorded_at)
                    VALUES ($1, $2, '{}'::jsonb, '{}'::jsonb, now()) RETURNING id
                    """,
                    owner_id,
                    experiment_id,
                )
            )
        await connection.executemany(
            """
            INSERT INTO recorded_data (
                user_id, measurement_id, name, quantity_kind, tensor_order, dtype, data_schema, data
            ) VALUES ($1, $2, 'signal', 'Signal', 0, $3, '{}'::jsonb, '{}'::jsonb)
            """,
            [
                (owner_id, measurement_ids[0], "float32"),
                (owner_id, measurement_ids[1], "float64"),
            ],
        )
        return measurement_ids[0], measurement_ids[1]
    finally:
        await connection.close()


def _ready_calculation(
    experiment_id: int,
    name: str,
    source_code: str,
    preflight_measurement_id: int,
    *,
    calculation_id: int | None = None,
    description: str | None = None,
    output_layout: dict[str, object] | None = None,
    record_ids: list[int] | None = None,
) -> CalculationBase:
    return CalculationBase(
        id=calculation_id,
        experiment_id=experiment_id,
        name=name,
        description=description,
        source_code=source_code,
        source_hash=hashlib.sha256(source_code.encode("utf-8")).hexdigest(),
        output_layout=CalculationOutputLayout.model_validate(
            output_layout or {"dtype": "float64", "shape": [], "axes": []}
        ),
        preflight_measurement_id=preflight_measurement_id,
        contract_status="ready",
        experiment_record_ids=record_ids or [],
    )


async def _seed_calculation_data(database: str) -> tuple[str, str, int, int, int, int, int, int]:
    owner_id = "00000000-0000-0000-0000-000000000303"
    other_id = "00000000-0000-0000-0000-000000000404"
    connection = await asyncpg.connect(**_connect_arguments(database))
    try:
        await connection.executemany(
            "INSERT INTO users (id, is_active) VALUES ($1, true)",
            [(owner_id,), (other_id,)],
        )
        await connection.executemany(
            "INSERT INTO experiment_namespaces (namespace, user_id) VALUES ($1, $2)",
            [("calc-data-owner", owner_id), ("calc-data-other", other_id)],
        )
        experiment_ids = []
        for namespace, user_id in (("calc-data-owner", owner_id), ("calc-data-other", other_id)):
            experiment_ids.append(
                await connection.fetchval(
                    """
                    INSERT INTO experiments (
                        user_id, namespace, repository_slug, experiment_key,
                        version_major, version_minor, version_patch,
                        name, source_bundle, source_hash
                    ) VALUES ($1, $2, 'repo', 'calculation-data', 0, 1, 0, $3, $4::jsonb, $5)
                    RETURNING id
                    """,
                    user_id,
                    namespace,
                    namespace,
                    json.dumps({"files": {"experiment.tsx": "export default null"}}),
                    f"hash-{namespace}",
                )
            )
        measurement_ids = []
        for recorded in (True, True, False):
            measurement_ids.append(
                await connection.fetchval(
                    """
                    INSERT INTO measurements (
                        user_id, experiment_id, vars, material_parameters, recorded_at
                    ) VALUES ($1, $2, '{}'::jsonb, '{}'::jsonb, CASE WHEN $3 THEN now() ELSE NULL END)
                    RETURNING id
                    """,
                    owner_id,
                    experiment_ids[0],
                    recorded,
                )
            )
        other_measurement_id = await connection.fetchval(
            """
            INSERT INTO measurements (user_id, experiment_id, vars, material_parameters, recorded_at)
            VALUES ($1, $2, '{}'::jsonb, '{}'::jsonb, now()) RETURNING id
            """,
            other_id,
            experiment_ids[1],
        )
        return (
            owner_id,
            other_id,
            experiment_ids[0],
            experiment_ids[1],
            measurement_ids[0],
            measurement_ids[1],
            measurement_ids[2],
            other_measurement_id,
        )
    finally:
        await connection.close()


async def _verify_crud_contract(database: str) -> None:
    owner_id, other_id, experiment_id, other_experiment_id = await _seed_owners(database)
    engine = create_async_engine(make_async_db_url(_database_url(database)))
    sessions = async_sessionmaker(engine, expire_on_commit=False)
    owner = UserData(id=owner_id, roles=[RoleEnum.user])
    other = UserData(id=other_id, roles=[RoleEnum.user])
    admin = UserData(id=owner_id, roles=[RoleEnum.admin])
    try:
        async with sessions() as session:
            owner_preflight = Measurement(
                user_id=owner_id,
                experiment_id=experiment_id,
                vars={},
                material_parameters={},
                recorded_at=datetime.now(timezone.utc),
            )
            other_preflight = Measurement(
                user_id=other_id,
                experiment_id=other_experiment_id,
                vars={},
                material_parameters={},
                recorded_at=datetime.now(timezone.utc),
            )
            session.add_all([owner_preflight, other_preflight])
            await session.flush()
            owner_preflight_id = owner_preflight.id
            other_preflight_id = other_preflight.id
            await session.commit()

        async with sessions() as session:
            result = await upsert_calculations(
                session,
                [
                    _ready_calculation(
                        experiment_id=experiment_id,
                        name="Magnitude",
                        description="Example",
                        source_code="export default () => ({ shape: [], data: 1, axes: [] })",
                        preflight_measurement_id=owner_preflight_id,
                    )
                ],
                user=owner,
            )
            calculation_id = result[0]["id"]

        async with sessions() as session:
            request = CalculationListRequest(
                experiment_id=experiment_id,
                limit=None,
                sort=["name", "asc"],
                random=True,
            )
            response = await list_calculations(session, request, user=owner)
            assert response["total"] == 1
            assert response["items"][0].id == calculation_id
            assert request.sort == ["updated_at", "desc"]
            assert request.random is False

        async with sessions() as session:
            hidden = await list_calculations(
                session,
                CalculationListRequest(experiment_id=experiment_id, limit=None),
                user=other,
            )
            assert hidden["total"] == 0

        async with sessions() as session:
            try:
                await upsert_calculations(
                    session,
                    [
                        _ready_calculation(
                            calculation_id=calculation_id,
                            experiment_id=experiment_id,
                            name="Not mine",
                            source_code="export default () => ({ shape: [], data: 0, axes: [] })",
                            preflight_measurement_id=owner_preflight_id,
                        )
                    ],
                    user=other,
                )
            except HTTPException as error:
                assert error.status_code == 404
            else:
                raise AssertionError("Another owner updated a Calculation")

        async with sessions() as session:
            try:
                await delete_calculations(session, [calculation_id], user=other)
            except HTTPException as error:
                assert error.status_code == 404
            else:
                raise AssertionError("Another owner deleted a Calculation")

        async with sessions() as session:
            try:
                await upsert_calculations(
                    session,
                    [
                        _ready_calculation(
                            calculation_id=calculation_id,
                            experiment_id=other_experiment_id,
                            name="Magnitude",
                            source_code="export default () => ({ shape: [], data: 1, axes: [] })",
                            preflight_measurement_id=other_preflight_id,
                        )
                    ],
                    user=admin,
                )
            except HTTPException as error:
                assert error.status_code == 409
            else:
                raise AssertionError("Calculation moved to another Experiment")

        async with sessions() as session:
            try:
                await upsert_calculations(
                    session,
                    [
                        _ready_calculation(
                            experiment_id=experiment_id,
                            name="Magnitude",
                            source_code="export default () => ({ shape: [], data: 2, axes: [] })",
                            preflight_measurement_id=owner_preflight_id,
                        )
                    ],
                    user=owner,
                )
            except HTTPException as error:
                assert error.status_code == 409
            else:
                raise AssertionError("Duplicate Calculation name was accepted")

        async with sessions() as session:
            counts = (await _derived_counts(session, [experiment_id]))[experiment_id]
            assert counts["calculations"] == 1
            usage = await experiment_usage(session, [experiment_id], user=owner)
            assert usage["items"][0]["sourceLocked"] is True
            assert usage["items"][0]["derivedCounts"]["calculations"] == 1

        async with sessions() as session:
            try:
                await save_experiment(
                    session,
                    SaveExperimentRequest(
                        mode="overwrite",
                        namespace="calc-owner",
                        repository="repo",
                        key="experiment",
                        experimentId=experiment_id,
                        baseBundleHash="hash-calc-owner",
                        name="calc-owner",
                        sourceBundle=ExperimentSourceBundle(
                            files={"experiment.tsx": "export default 1"}
                        ),
                        bundleHash="client-value-is-not-trusted",
                        records=[],
                    ),
                    user=owner,
                )
            except HTTPException as error:
                assert error.status_code == 409
                assert error.detail["code"] == "experiment_source_locked"
                assert error.detail["derivedCounts"]["calculations"] == 1
            else:
                raise AssertionError("Experiment source overwrite ignored Calculation lock")

        async with sessions() as session:
            await delete_calculations(session, [calculation_id], user=owner)
            assert await session.scalar(select(func.count()).select_from(Calculation)) == 0

        async with sessions() as session:
            experiment_record = ExperimentRecord(
                experiment_id=experiment_id,
                name="signal",
                quantity_kind="Signal",
                tensor_order=0,
                dtype="float64",
                data_schema={},
                contract_hash="record-contract",
            )
            session.add(experiment_record)
            await session.flush()
            session.add(
                RecordedData(
                    user_id=owner_id,
                    measurement_id=owner_preflight_id,
                    experiment_record_id=experiment_record.id,
                    data={"shape": [], "storage": {"kind": "inline", "value": 1}},
                )
            )
            await session.commit()
            experiment_record_id = experiment_record.id

        async with sessions() as session:
            created = await upsert_calculations(
                session,
                [
                    _ready_calculation(
                        experiment_id=experiment_id,
                        name="Cascade",
                        source_code="export default () => ({ shape: [], data: 1, axes: [] })",
                        preflight_measurement_id=owner_preflight_id,
                        record_ids=[experiment_record_id],
                    )
                ],
                user=owner,
            )
            assert created
            await session.execute(delete(Experiment).where(Experiment.id == experiment_id))
            await session.commit()
            assert await session.scalar(select(func.count()).select_from(Calculation)) == 0
    finally:
        await engine.dispose()


async def _verify_calculation_data_contract(database: str) -> None:
    (
        owner_id,
        other_id,
        experiment_id,
        other_experiment_id,
        first_measurement_id,
        second_measurement_id,
        prepared_measurement_id,
        other_measurement_id,
    ) = await _seed_calculation_data(database)
    engine = create_async_engine(make_async_db_url(_database_url(database)))
    sessions = async_sessionmaker(engine, expire_on_commit=False)
    owner = UserData(id=owner_id, roles=[RoleEnum.user])
    other = UserData(id=other_id, roles=[RoleEnum.user])
    admin = UserData(id="00000000-0000-0000-0000-000000000001", roles=[RoleEnum.admin])
    source = "export default () => ({ dtype: 'float64', data: 1 })"
    source_hash = hashlib.sha256(source.encode("utf-8")).hexdigest()
    changed_source = "export default () => ({ dtype: 'float64', data: 2 })"
    scalar = {"dtype": "float64", "shape": [], "data": 1.5, "axes": []}
    try:
        async with sessions() as session:
            created = await upsert_calculations(
                session,
                [
                    _ready_calculation(experiment_id, "Scalar", source, first_measurement_id),
                    _ready_calculation(
                        experiment_id,
                        "Other",
                        source,
                        first_measurement_id,
                        output_layout={
                            "dtype": "float64",
                            "shape": [2],
                            "axes": [{"name": "x", "ticks": [0, 1]}],
                        },
                    ),
                ],
                user=owner,
            )
            first_calculation_id, second_calculation_id = (item["id"] for item in created)

        async with sessions() as session:
            other_created = await upsert_calculations(
                session,
                [_ready_calculation(other_experiment_id, "Hidden", source, other_measurement_id)],
                user=other,
            )
            other_calculation_id = other_created[0]["id"]

        async with sessions() as session:
            all_missing = await missing_calculation_data(
                session, experiment_id, None, None, user=owner
            )
            assert all_missing["total"] == 4
            assert prepared_measurement_id not in {
                item["measurement_id"] for item in all_missing["items"]
            }
            selected_calculation = await missing_calculation_data(
                session,
                experiment_id,
                first_calculation_id,
                None,
                user=owner,
            )
            assert selected_calculation["total"] == 2
            selected_measurement = await missing_calculation_data(
                session,
                experiment_id,
                None,
                first_measurement_id,
                user=owner,
            )
            assert selected_measurement["total"] == 2

        async with sessions() as session:
            saved = await save_calculation_data(
                session,
                first_calculation_id,
                first_measurement_id,
                source_hash,
                CalculationDataOutput.model_validate(scalar),
                user=owner,
            )
            duplicate = await save_calculation_data(
                session,
                first_calculation_id,
                first_measurement_id,
                source_hash,
                CalculationDataOutput.model_validate({**scalar, "data": 99}),
                user=owner,
            )
            assert saved["created"] is True
            assert duplicate["id"] == saved["id"]
            assert duplicate["created"] is False
            row = await session.get(CalculationData, saved["id"])
            assert row is not None and row.data["data"] == 1.5

        async with sessions() as session:
            await save_calculation_data(
                session,
                first_calculation_id,
                second_measurement_id,
                source_hash,
                CalculationDataOutput.model_validate({**scalar, "data": 3}),
                user=owner,
            )
            scalar_rows = await list_calculation_data_scalars(
                session,
                first_calculation_id,
                first_measurement_id,
                user=owner,
            )
            assert scalar_rows["total"] == 1
            assert scalar_rows["items"][0]["measurement_id"] == second_measurement_id
            assert scalar_rows["items"][0]["value"] == 3

        async with sessions() as session:
            tensor_saved = await save_calculation_data(
                session,
                second_calculation_id,
                first_measurement_id,
                source_hash,
                CalculationDataOutput.model_validate(
                    {
                        "dtype": "float64",
                        "shape": [2],
                        "data": [1, 2],
                        "axes": [{"name": "x", "ticks": [0, 1]}],
                    }
                ),
                user=owner,
            )
            selected_rows = await list_calculation_data(
                session,
                CalculationDataListRequest(
                    experiment_id=experiment_id,
                    selected_ids=[saved["id"], tensor_saved["id"]],
                    search_text="cannot widen the exact IDs",
                    filter={"calculation_id": [0, 999_999]},
                    limit=None,
                ),
                user=owner,
            )
            assert selected_rows["total"] == 2
            assert {item.id for item in selected_rows["items"]} == {
                saved["id"],
                tensor_saved["id"],
            }
            hidden_rows = await list_calculation_data(
                session,
                CalculationDataListRequest(
                    experiment_id=experiment_id,
                    selected_ids=[saved["id"], tensor_saved["id"]],
                    limit=None,
                ),
                user=other,
            )
            assert hidden_rows["total"] == 0
            scalar_rows = await list_calculation_data_scalars(
                session,
                second_calculation_id,
                None,
                user=owner,
            )
            assert scalar_rows["total"] == 0

        async with sessions() as session:
            measurement_response = await list_measurements(
                session,
                GetListRequestBase(
                    scope="mine",
                    limit=None,
                    filter={"experiment_id": [experiment_id, experiment_id]},
                ),
                user=owner,
            )
            counts = {
                item.id: item.calculation_data_count for item in measurement_response["items"]
            }
            assert counts[first_measurement_id] == 2
            assert counts[second_measurement_id] == 1
            assert counts[prepared_measurement_id] == 0
            hidden_measurements = await list_measurements(
                session,
                GetListRequestBase(
                    scope="mine",
                    limit=None,
                    filter={"experiment_id": [experiment_id, experiment_id]},
                ),
                user=other,
            )
            assert hidden_measurements["total"] == 0

        async with sessions() as session:
            extra = await upsert_calculations(
                session,
                [
                    _ready_calculation(
                        experiment_id,
                        "Single",
                        source,
                        first_measurement_id,
                        output_layout={
                            "dtype": "float64",
                            "shape": [1],
                            "axes": [{"name": "x", "ticks": [0]}],
                        },
                    ),
                    _ready_calculation(
                        experiment_id,
                        "Empty",
                        source,
                        first_measurement_id,
                        output_layout={
                            "dtype": "float64",
                            "shape": [0, 2],
                            "axes": [
                                {"name": "x", "ticks": []},
                                {"name": "y", "ticks": [0, 1]},
                            ],
                        },
                    ),
                ],
                user=owner,
            )
            single_calculation_id, empty_calculation_id = (item["id"] for item in extra)
            await save_calculation_data(
                session,
                single_calculation_id,
                first_measurement_id,
                source_hash,
                CalculationDataOutput.model_validate(
                    {
                        "dtype": "float64",
                        "shape": [1],
                        "data": [4],
                        "axes": [{"name": "x", "ticks": [0]}],
                    }
                ),
                user=owner,
            )
            await save_calculation_data(
                session,
                empty_calculation_id,
                first_measurement_id,
                source_hash,
                CalculationDataOutput.model_validate(
                    {
                        "dtype": "float64",
                        "shape": [0, 2],
                        "data": [],
                        "axes": [
                            {"name": "x", "ticks": []},
                            {"name": "y", "ticks": [0, 1]},
                        ],
                    }
                ),
                user=owner,
            )
            analysis = await analyze_calculation_data(
                session,
                experiment_id,
                user=owner,
            )
            assert analysis["total"] == 5
            assert analysis["measurement_count"] == 2
            assert len(
                {item["calculation_data_id"] for item in analysis["items"]}
            ) == analysis["total"]
            by_calculation = {
                item["calculation_id"]: item for item in analysis["items"]
            }
            assert by_calculation[first_calculation_id]["summary"]["kind"] == "scalar"
            tensor_summary = by_calculation[second_calculation_id]["summary"]
            assert tensor_summary["kind"] == "tensor"
            assert tensor_summary["mean"] == 1.5
            assert round(tensor_summary["std"] or 0, 8) == round(2 ** -0.5, 8)
            single_summary = by_calculation[single_calculation_id]["summary"]
            assert single_summary["kind"] == "tensor"
            assert single_summary["mean"] == 4
            assert single_summary["std"] == 0
            empty_summary = by_calculation[empty_calculation_id]["summary"]
            assert empty_summary["kind"] == "tensor"
            assert empty_summary["count"] == 0
            assert empty_summary["mean"] is None and empty_summary["std"] is None
            initial_analysis_fingerprint = analysis["fingerprint"]
            status_response = await calculation_data_analysis_status(
                session,
                experiment_id,
                user=owner,
            )
            assert status_response["fingerprint"] == initial_analysis_fingerprint
            assert status_response["total"] == analysis["total"]

        async with sessions() as session:
            try:
                await save_calculation_data(
                    session,
                    first_calculation_id,
                    other_measurement_id,
                    source_hash,
                    CalculationDataOutput.model_validate(scalar),
                    user=owner,
                )
            except HTTPException as error:
                assert error.status_code == 404
            else:
                raise AssertionError("CalculationData accepted a Measurement from another Experiment")

        async with sessions() as session:
            await upsert_calculations(
                session,
                [
                    _ready_calculation(
                        experiment_id,
                        "Scalar renamed",
                        source,
                        first_measurement_id,
                        calculation_id=first_calculation_id,
                        description="metadata only",
                    )
                ],
                user=owner,
            )
            assert await session.scalar(
                select(func.count()).select_from(CalculationData).where(
                    CalculationData.calculation_id == first_calculation_id
                )
            ) == 2
            renamed_status = await calculation_data_analysis_status(
                session,
                experiment_id,
                user=owner,
            )
            assert renamed_status["fingerprint"] != initial_analysis_fingerprint
            renamed_analysis_fingerprint = renamed_status["fingerprint"]

        async with sessions() as session:
            await upsert_calculations(
                session,
                [
                    _ready_calculation(
                        experiment_id,
                        "Scalar renamed",
                        changed_source,
                        first_measurement_id,
                        calculation_id=first_calculation_id,
                    )
                ],
                user=owner,
            )
            assert await session.scalar(
                select(func.count()).select_from(CalculationData).where(
                    CalculationData.calculation_id == first_calculation_id
                )
            ) == 0
            changed_status = await calculation_data_analysis_status(
                session,
                experiment_id,
                user=owner,
            )
            assert changed_status["fingerprint"] != renamed_analysis_fingerprint
            measurement_response = await list_measurements(
                session,
                GetListRequestBase(
                    scope="mine",
                    limit=None,
                    filter={"experiment_id": [experiment_id, experiment_id]},
                ),
                user=owner,
            )
            counts = {
                item.id: item.calculation_data_count for item in measurement_response["items"]
            }
            assert counts[first_measurement_id] == 3
            assert counts[second_measurement_id] == 0
            try:
                await save_calculation_data(
                    session,
                    first_calculation_id,
                    first_measurement_id,
                    source_hash,
                    CalculationDataOutput.model_validate(scalar),
                    user=owner,
                )
            except HTTPException as error:
                assert error.status_code == 409
            else:
                raise AssertionError("CalculationData accepted a stale Calculation source")

        async with sessions() as session:
            other_saved = await save_calculation_data(
                session,
                other_calculation_id,
                other_measurement_id,
                source_hash,
                CalculationDataOutput.model_validate(scalar),
                user=other,
            )
            admin_analysis = await analyze_calculation_data(
                session,
                other_experiment_id,
                user=admin,
            )
            assert admin_analysis["total"] == 1
            assert admin_analysis["items"][0]["calculation_data_id"] == other_saved["id"]

            session.add(ExperimentDemo(experiment_id=experiment_id, display_order=0, is_default=True))
            await session.commit()
            admin_demo_calculation = await upsert_calculations(
                session,
                [_ready_calculation(experiment_id, "Admin Demo Edit", source, first_measurement_id)],
                user=admin,
            )
            admin_demo_targets = await missing_calculation_data(
                session,
                experiment_id,
                admin_demo_calculation[0]["id"],
                None,
                user=admin,
            )
            assert admin_demo_targets["total"] >= 1
            await delete_calculations(session, [admin_demo_calculation[0]["id"]], user=admin)
            assert await session.get(ExperimentDemo, experiment_id) is not None
            guest_measurements = await list_measurements(
                session,
                GetListRequestBase(
                    limit=None,
                    filter={"experiment_id": [experiment_id, experiment_id]},
                ),
                user=None,
            )
            assert guest_measurements["total"] == 3
            guest_calculations = await list_calculations(
                session,
                CalculationListRequest(experiment_id=experiment_id, limit=None),
                user=None,
            )
            assert guest_calculations["total"] >= 1
            guest_analysis = await analyze_calculation_data(session, experiment_id, user=None)
            assert guest_analysis["total"] >= 1
            guest_ids = [item["calculation_data_id"] for item in guest_analysis["items"]]
            guest_data = await list_calculation_data(
                session,
                CalculationDataListRequest(
                    experiment_id=experiment_id,
                    selected_ids=guest_ids,
                    limit=None,
                ),
                user=None,
            )
            assert guest_data["total"] == len(guest_ids)
            try:
                await analyze_calculation_data(session, other_experiment_id, user=None)
            except HTTPException as error:
                assert error.status_code == 404
            else:
                raise AssertionError("Anonymous user could read a non-Demo Experiment")
            try:
                await missing_calculation_data(
                    session,
                    experiment_id,
                    None,
                    None,
                    user=None,  # type: ignore[arg-type]
                )
            except HTTPException as error:
                assert error.status_code == 404
            else:
                raise AssertionError("Anonymous user could mutate Demo CalculationData")

            await session.execute(delete(ExperimentDemo).where(ExperimentDemo.experiment_id == experiment_id))
            await session.commit()
            try:
                await analyze_calculation_data(session, experiment_id, user=None)
            except HTTPException as error:
                assert error.status_code == 404
            else:
                raise AssertionError("Anonymous Demo access survived public removal")

            owner_list = await list_calculation_data(
                session,
                CalculationDataListRequest(
                    experiment_id=other_experiment_id,
                    selected_ids=[other_saved["id"]],
                    limit=None,
                ),
                user=owner,
            )
            assert owner_list["total"] == 0
            wrong_experiment_list = await list_calculation_data(
                session,
                CalculationDataListRequest(
                    experiment_id=experiment_id,
                    selected_ids=[other_saved["id"]],
                    limit=None,
                ),
                user=admin,
            )
            assert wrong_experiment_list["total"] == 0
            admin_list = await list_calculation_data(
                session,
                CalculationDataListRequest(
                    experiment_id=other_experiment_id,
                    selected_ids=[other_saved["id"]],
                    limit=None,
                ),
                user=admin,
            )
            assert admin_list["total"] == 1
            assert admin_list["items"][0].data.data == scalar["data"]
            try:
                await missing_calculation_data(
                    session,
                    other_experiment_id,
                    None,
                    None,
                    user=owner,
                )
            except HTTPException as error:
                assert error.status_code == 404
            else:
                raise AssertionError("Another owner's CalculationData targets were visible")
            try:
                await save_calculation_data(
                    session,
                    other_calculation_id,
                    other_measurement_id,
                    source_hash,
                    CalculationDataOutput.model_validate(scalar),
                    user=owner,
                )
            except HTTPException as error:
                assert error.status_code == 404
            else:
                raise AssertionError("Another owner's CalculationData was writable")

        async with sessions() as session:
            await session.execute(delete(Measurement).where(Measurement.id == first_measurement_id))
            await session.commit()
            assert await session.scalar(
                select(func.count()).select_from(CalculationData).where(
                    CalculationData.measurement_id == first_measurement_id
                )
            ) == 0

        async with sessions() as session:
            session.add_all(
                [
                    ExperimentDemo(experiment_id=experiment_id, display_order=0, is_default=True),
                    ExperimentDemo(experiment_id=other_experiment_id, display_order=1, is_default=False),
                ]
            )
            await session.commit()
            await delete_experiment_versions(session, [experiment_id], user=admin)
            promoted = await session.get(ExperimentDemo, other_experiment_id)
            assert promoted is not None and promoted.is_default is True
    finally:
        await engine.dispose()


@unittest.skipUnless(
    os.getenv("RUN_CALCULATION_DB_TESTS") == "1",
    "Set RUN_CALCULATION_DB_TESTS=1 to use disposable PostgreSQL databases.",
)
class CalculationDatabaseIntegrationTests(unittest.TestCase):
    def test_measurement_coordinates_are_preserved_without_fixing_preflight_ticks(self) -> None:
        database = f"caemble_calculation_test_{uuid.uuid4().hex}"

        async def verify() -> None:
            owner_id, _, experiment_id, _, first_id, second_id, _, _ = await _seed_calculation_data(database)
            engine = create_async_engine(make_async_db_url(_database_url(database)))
            sessions = async_sessionmaker(engine, expire_on_commit=False)
            owner = UserData(id=owner_id, roles=[RoleEnum.user])
            source = "export default record => record.signal"
            source_hash = hashlib.sha256(source.encode("utf-8")).hexdigest()
            layout = {
                "dtype": "float64", "shape": [2],
                "axes": [{"name": "x", "unit": "m", "ticks": [0, 1]}],
            }
            shifted = {**layout, "axes": [{"name": "x", "unit": "m", "ticks": [2, 4]}]}
            try:
                async with sessions() as session:
                    created = await upsert_calculations(session, [
                        _ready_calculation(experiment_id, "Coordinates", source, first_id, output_layout=layout)
                    ], user=owner)
                    calculation_id = created[0]["id"]
                    saved_ids = []
                    for measurement_id, output_layout in ((first_id, layout), (second_id, shifted)):
                        saved = await save_calculation_data(
                            session, calculation_id, measurement_id, source_hash,
                            CalculationDataOutput.model_validate({**output_layout, "data": [10, 20]}),
                            user=owner,
                        )
                        saved_ids.append(saved["id"])
                    await upsert_calculations(session, [
                        _ready_calculation(
                            experiment_id, "Coordinates", source, second_id,
                            calculation_id=calculation_id, output_layout=shifted,
                        )
                    ], user=owner)
                    response = await list_calculation_data(
                        session, CalculationDataListRequest(
                            experiment_id=experiment_id, selected_ids=saved_ids, limit=None,
                        ), user=owner,
                    )
                    outputs = {
                        row.measurement_id: row.data.model_dump(mode="json")
                        for row in response["items"]
                    }
                    assert outputs[first_id]["axes"] == layout["axes"]
                    assert outputs[second_id]["axes"] == shifted["axes"]
                    assert all(output["data"] == [10, 20] for output in outputs.values())

                mismatches = [
                    {**shifted, "dtype": "float32"},
                    {**shifted, "shape": [1, 2], "axes": [
                        {"name": "row", "ticks": [0]}, shifted["axes"][0],
                    ]},
                    {**shifted, "axes": [{"name": "y", "unit": "m", "ticks": [2, 4]}]},
                    {**shifted, "axes": [{"name": "x", "unit": "mm", "ticks": [2, 4]}]},
                ]
                for mismatch in mismatches:
                    async with sessions() as session:
                        with self.assertRaises(HTTPException) as failure:
                            await save_calculation_data(
                                session, calculation_id, first_id, source_hash,
                                CalculationDataOutput.model_validate({**mismatch, "data": [10, 20]}),
                                user=owner,
                            )
                        self.assertEqual(failure.exception.status_code, 422)
                        with self.assertRaises(HTTPException) as failure:
                            await upsert_calculations(session, [
                                _ready_calculation(
                                    experiment_id, "Coordinates", source, second_id,
                                    calculation_id=calculation_id, output_layout=mismatch,
                                )
                            ], user=owner)
                        self.assertEqual(failure.exception.status_code, 409)

                for ticks in ([0], [0, float("nan")], [0, float("inf")], [0, True]):
                    with self.assertRaises(ValidationError):
                        CalculationDataOutput.model_validate({
                            **layout, "data": [10, 20],
                            "axes": [{"name": "x", "unit": "m", "ticks": ticks}],
                        })
            finally:
                await engine.dispose()

        try:
            asyncio.run(_create_database(database))
            _upgrade(database, "head")
            asyncio.run(verify())
        finally:
            settings.db_url = ORIGINAL_DB_URL
            asyncio.run(_drop_database(database))

    def test_empty_and_existing_head_migrations_and_crud(self) -> None:
        empty_database = f"caemble_calculation_test_{uuid.uuid4().hex}"
        legacy_database = f"caemble_calculation_test_{uuid.uuid4().hex}"
        conflict_database = f"caemble_calculation_test_{uuid.uuid4().hex}"
        try:
            asyncio.run(_create_database(empty_database))
            _upgrade(empty_database, "head")
            empty_tables = asyncio.run(_table_names(empty_database))
            self.assertIn("calculations", empty_tables)
            self.assertIn("calculation_data", empty_tables)
            self.assertIn("experiment_demos", empty_tables)
            self.assertNotIn("designer_models", empty_tables)
            self.assertNotIn("predictor_models", empty_tables)
            _check(empty_database)
            asyncio.run(_verify_crud_contract(empty_database))
            asyncio.run(_verify_calculation_data_contract(empty_database))

            asyncio.run(_create_database(legacy_database))
            _upgrade(legacy_database, "000000000001")
            asyncio.run(_replace_calculation_with_legacy_tables(legacy_database))
            _upgrade(legacy_database, "head")
            legacy_tables = asyncio.run(_table_names(legacy_database))
            self.assertIn("calculations", legacy_tables)
            self.assertIn("calculation_data", legacy_tables)
            self.assertIn("experiment_demos", legacy_tables)
            self.assertNotIn("designer_models", legacy_tables)
            self.assertNotIn("predictor_models", legacy_tables)
            _check(legacy_database)

            asyncio.run(_create_database(conflict_database))
            _upgrade(conflict_database, "000000000003")
            first_measurement_id, second_measurement_id = asyncio.run(
                _seed_conflicting_legacy_recorded_data(conflict_database)
            )
            with self.assertRaises(Exception) as migration_error:
                _upgrade(conflict_database, "head")
            message = str(migration_error.exception)
            self.assertIn("ExperimentRecord backfill found conflicting metadata", message)
            self.assertIn(str(first_measurement_id), message)
            self.assertIn(str(second_measurement_id), message)
            self.assertIn("dtype", message)
        finally:
            settings.db_url = ORIGINAL_DB_URL
            asyncio.run(_drop_database(empty_database))
            asyncio.run(_drop_database(legacy_database))
            asyncio.run(_drop_database(conflict_database))
        self.assertNotIn(empty_database, asyncio.run(_calculation_test_databases()))
        self.assertNotIn(legacy_database, asyncio.run(_calculation_test_databases()))
        self.assertNotIn(conflict_database, asyncio.run(_calculation_test_databases()))


if __name__ == "__main__":
    unittest.main()
