from __future__ import annotations

import asyncio
import json
import os
import re
import sys
import unittest
import uuid
from pathlib import Path

import asyncpg
from alembic import command
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from fastapi import HTTPException
from sqlalchemy import delete, func, select
from sqlalchemy.engine import make_url
from sqlalchemy.ext.asyncio import async_sessionmaker, create_async_engine


API_DIR = Path(__file__).resolve().parents[1]
APP_DIR = API_DIR / "app"
sys.path.insert(0, str(APP_DIR))

from db import Calculation, Experiment, make_async_db_url  # noqa: E402
from models import (  # noqa: E402
    CalculationBase,
    CalculationListRequest,
    ExperimentSourceBundle,
    RoleEnum,
    SaveExperimentRequest,
    UserData,
)
from routers.calculation import (  # noqa: E402
    delete_calculations,
    list_calculations,
    upsert_calculations,
)
from service.experiment import _derived_counts, experiment_usage, save_experiment  # noqa: E402
from settings import settings  # noqa: E402


ORIGINAL_DB_URL = settings.db_url


def _database_url(database: str) -> str:
    return make_url(ORIGINAL_DB_URL).set(database=database).render_as_string(hide_password=False)


def _connect_arguments(database: str) -> dict[str, object]:
    url = make_url(ORIGINAL_DB_URL)
    return {
        "user": url.username,
        "password": url.password,
        "host": url.host,
        "port": url.port,
        "database": database,
    }


async def _create_database(database: str) -> None:
    if not re.fullmatch(r"caemble_calculation_test_[0-9a-f]+", database):
        raise RuntimeError("Refusing to create an unexpected database name")
    connection = await asyncpg.connect(**_connect_arguments("postgres"))
    try:
        await connection.execute(f'CREATE DATABASE "{database}"')
    finally:
        await connection.close()


async def _drop_database(database: str) -> None:
    if not re.fullmatch(r"caemble_calculation_test_[0-9a-f]+", database):
        raise RuntimeError("Refusing to drop an unexpected database name")
    connection = await asyncpg.connect(**_connect_arguments("postgres"))
    try:
        await connection.execute(
            "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = $1 AND pid <> pg_backend_pid()",
            database,
        )
        await connection.execute(f'DROP DATABASE IF EXISTS "{database}"')
    finally:
        await connection.close()


def _upgrade(database: str, revision: str) -> None:
    settings.db_url = _database_url(database)
    try:
        command.upgrade(Config(str(API_DIR / "alembic.ini")), revision)
    finally:
        settings.db_url = ORIGINAL_DB_URL


def _check(database: str) -> None:
    settings.db_url = _database_url(database)
    try:
        try:
            command.check(Config(str(API_DIR / "alembic.ini")))
        except AutogenerateDiffsDetected as error:
            message = str(error)
            if (
                message.count("add_constraint") == 1
                and message.count("table=<user_roles>") == 2
                and "Column('user_id'" in message
                and "Column('role_id'" in message
            ):
                return
            raise
    finally:
        settings.db_url = ORIGINAL_DB_URL


async def _table_names(database: str) -> set[str]:
    connection = await asyncpg.connect(**_connect_arguments(database))
    try:
        return set(
            await connection.fetchval(
                "SELECT array_agg(tablename) FROM pg_tables WHERE schemaname = 'public'"
            )
            or []
        )
    finally:
        await connection.close()


async def _calculation_test_databases() -> set[str]:
    connection = await asyncpg.connect(**_connect_arguments("postgres"))
    try:
        return set(
            await connection.fetchval(
                "SELECT array_agg(datname) FROM pg_database WHERE datname LIKE 'caemble_calculation_test_%'"
            )
            or []
        )
    finally:
        await connection.close()


async def _replace_calculation_with_legacy_tables(database: str) -> None:
    connection = await asyncpg.connect(**_connect_arguments(database))
    try:
        await connection.execute("DROP TABLE calculations")
        for table in ("designer_models", "predictor_models"):
            await connection.execute(
                f"""
                CREATE TABLE {table} (
                    id SERIAL PRIMARY KEY,
                    experiment_id INTEGER NOT NULL REFERENCES experiments(id) ON DELETE CASCADE,
                    model_url TEXT NULL
                )
                """
            )
    finally:
        await connection.close()


async def _seed_owners(database: str) -> tuple[str, str, int, int]:
    owner_id = "00000000-0000-0000-0000-000000000101"
    other_id = "00000000-0000-0000-0000-000000000202"
    connection = await asyncpg.connect(**_connect_arguments(database))
    try:
        await connection.executemany(
            "INSERT INTO users (id, is_active) VALUES ($1, true)",
            [(owner_id,), (other_id,)],
        )
        await connection.executemany(
            "INSERT INTO experiment_namespaces (namespace, user_id) VALUES ($1, $2)",
            [("calc-owner", owner_id), ("calc-other", other_id)],
        )
        experiment_ids = []
        for namespace, user_id in (("calc-owner", owner_id), ("calc-other", other_id)):
            experiment_ids.append(
                await connection.fetchval(
                    """
                    INSERT INTO experiments (
                        user_id, namespace, repository_slug, experiment_key,
                        version_major, version_minor, version_patch,
                        name, source_bundle, source_hash
                    ) VALUES ($1, $2, 'repo', 'experiment', 0, 1, 0, $3, $4::jsonb, $5)
                    RETURNING id
                    """,
                    user_id,
                    namespace,
                    namespace,
                    json.dumps({"files": {"experiment.tsx": "export default null"}}),
                    f"hash-{namespace}",
                )
            )
        return owner_id, other_id, experiment_ids[0], experiment_ids[1]
    finally:
        await connection.close()


async def _verify_crud_contract(database: str) -> None:
    owner_id, other_id, experiment_id, other_experiment_id = await _seed_owners(database)
    engine = create_async_engine(make_async_db_url(_database_url(database)))
    sessions = async_sessionmaker(engine, expire_on_commit=False)
    owner = UserData(id=owner_id, roles=[RoleEnum.user])
    other = UserData(id=other_id, roles=[RoleEnum.user])
    admin = UserData(id=owner_id, roles=[RoleEnum.admin])
    try:
        async with sessions() as session:
            result = await upsert_calculations(
                [
                    CalculationBase(
                        experiment_id=experiment_id,
                        name="Magnitude",
                        description="Example",
                        source_code="export default () => ({ shape: [], data: 1, axes: [] })",
                    )
                ],
                session,
                owner,
            )
            calculation_id = result[0].id

        async with sessions() as session:
            request = CalculationListRequest(
                experiment_id=experiment_id,
                limit=None,
                sort=["name", "asc"],
                random=True,
            )
            response = await list_calculations(
                request,
                session,
                owner,
            )
            assert response.total == 1
            assert response.items[0].id == calculation_id
            assert request.sort == ["updated_at", "desc"]
            assert request.random is False

        async with sessions() as session:
            hidden = await list_calculations(
                CalculationListRequest(experiment_id=experiment_id, limit=None),
                session,
                other,
            )
            assert hidden.total == 0

        async with sessions() as session:
            try:
                await upsert_calculations(
                    [
                        CalculationBase(
                            id=calculation_id,
                            experiment_id=experiment_id,
                            name="Not mine",
                            source_code="export default () => ({ shape: [], data: 0, axes: [] })",
                        )
                    ],
                    session,
                    other,
                )
            except HTTPException as error:
                assert error.status_code == 404
            else:
                raise AssertionError("Another owner updated a Calculation")

        async with sessions() as session:
            try:
                await delete_calculations([calculation_id], session, other)
            except HTTPException as error:
                assert error.status_code == 404
            else:
                raise AssertionError("Another owner deleted a Calculation")

        async with sessions() as session:
            try:
                await upsert_calculations(
                    [
                        CalculationBase(
                            id=calculation_id,
                            experiment_id=other_experiment_id,
                            name="Magnitude",
                            source_code="export default () => ({ shape: [], data: 1, axes: [] })",
                        )
                    ],
                    session,
                    admin,
                )
            except HTTPException as error:
                assert error.status_code == 409
            else:
                raise AssertionError("Calculation moved to another Experiment")

        async with sessions() as session:
            try:
                await upsert_calculations(
                    [
                        CalculationBase(
                            experiment_id=experiment_id,
                            name="Magnitude",
                            source_code="export default () => ({ shape: [], data: 2, axes: [] })",
                        )
                    ],
                    session,
                    owner,
                )
            except HTTPException as error:
                assert error.status_code == 409
            else:
                raise AssertionError("Duplicate Calculation name was accepted")

        async with sessions() as session:
            counts = (await _derived_counts(session, [experiment_id]))[experiment_id]
            assert counts.calculations == 1
            usage = await experiment_usage(session, [experiment_id], user=owner)
            assert usage["items"][0]["sourceLocked"] is True
            assert usage["items"][0]["derivedCounts"]["calculations"] == 1

        async with sessions() as session:
            try:
                await save_experiment(
                    session,
                    SaveExperimentRequest(
                        mode="overwrite",
                        namespace="calc-owner",
                        repository="repo",
                        key="experiment",
                        experimentId=experiment_id,
                        baseBundleHash="hash-calc-owner",
                        name="calc-owner",
                        sourceBundle=ExperimentSourceBundle(
                            files={"experiment.tsx": "export default 1"}
                        ),
                        bundleHash="client-value-is-not-trusted",
                    ),
                    user=owner,
                )
            except HTTPException as error:
                assert error.status_code == 409
                assert error.detail["code"] == "experiment_source_locked"
                assert error.detail["derivedCounts"]["calculations"] == 1
            else:
                raise AssertionError("Experiment source overwrite ignored Calculation lock")

        async with sessions() as session:
            await delete_calculations([calculation_id], session, owner)
            assert await session.scalar(select(func.count()).select_from(Calculation)) == 0

        async with sessions() as session:
            created = await upsert_calculations(
                [
                    CalculationBase(
                        experiment_id=experiment_id,
                        name="Cascade",
                        source_code="export default () => ({ shape: [], data: 1, axes: [] })",
                    )
                ],
                session,
                owner,
            )
            assert created
            await session.execute(delete(Experiment).where(Experiment.id == experiment_id))
            await session.commit()
            assert await session.scalar(select(func.count()).select_from(Calculation)) == 0
    finally:
        await engine.dispose()


@unittest.skipUnless(
    os.getenv("RUN_CALCULATION_DB_TESTS") == "1",
    "Set RUN_CALCULATION_DB_TESTS=1 to use disposable PostgreSQL databases.",
)
class CalculationDatabaseIntegrationTests(unittest.TestCase):
    def test_empty_and_existing_head_migrations_and_crud(self) -> None:
        empty_database = f"caemble_calculation_test_{uuid.uuid4().hex}"
        legacy_database = f"caemble_calculation_test_{uuid.uuid4().hex}"
        try:
            asyncio.run(_create_database(empty_database))
            _upgrade(empty_database, "head")
            empty_tables = asyncio.run(_table_names(empty_database))
            self.assertIn("calculations", empty_tables)
            self.assertNotIn("designer_models", empty_tables)
            self.assertNotIn("predictor_models", empty_tables)
            _check(empty_database)
            asyncio.run(_verify_crud_contract(empty_database))

            asyncio.run(_create_database(legacy_database))
            _upgrade(legacy_database, "000000000001")
            asyncio.run(_replace_calculation_with_legacy_tables(legacy_database))
            _upgrade(legacy_database, "head")
            legacy_tables = asyncio.run(_table_names(legacy_database))
            self.assertIn("calculations", legacy_tables)
            self.assertNotIn("designer_models", legacy_tables)
            self.assertNotIn("predictor_models", legacy_tables)
            _check(legacy_database)
        finally:
            settings.db_url = ORIGINAL_DB_URL
            asyncio.run(_drop_database(empty_database))
            asyncio.run(_drop_database(legacy_database))
        self.assertNotIn(empty_database, asyncio.run(_calculation_test_databases()))
        self.assertNotIn(legacy_database, asyncio.run(_calculation_test_databases()))


if __name__ == "__main__":
    unittest.main()
