export const CALCULATION_MATHJS_REFERENCE = Object.freeze([
  Object.freeze({ group: 'Constructors', names: Object.freeze(['complex', 'matrix', 'index', 'number']) }),
  Object.freeze({ group: 'Constants', names: Object.freeze(['e', 'pi', 'i', 'tau']) }),
  Object.freeze({
    group: 'Arithmetic',
    names: Object.freeze([
      'abs',
      'add',
      'cbrt',
      'ceil',
      'cube',
      'divide',
      'dotDivide',
      'dotMultiply',
      'dotPow',
      'exp',
      'expm',
      'expm1',
      'fix',
      'floor',
      'hypot',
      'log',
      'log10',
      'log1p',
      'log2',
      'mod',
      'multiply',
      'nthRoot',
      'pow',
      'round',
      'sign',
      'sqrt',
      'sqrtm',
      'square',
      'subtract',
      'unaryMinus',
      'unaryPlus',
    ]),
  }),
  Object.freeze({ group: 'Complex', names: Object.freeze(['arg', 'conj', 'im', 're']) }),
  Object.freeze({
    group: 'Matrix',
    names: Object.freeze([
      'column',
      'concat',
      'cross',
      'ctranspose',
      'det',
      'diag',
      'dot',
      'flatten',
      'identity',
      'kron',
      'map',
      'matrixFromColumns',
      'matrixFromRows',
      'ones',
      'range',
      'reshape',
      'resize',
      'row',
      'size',
      'squeeze',
      'subset',
      'trace',
      'transpose',
      'zeros',
    ]),
  }),
  Object.freeze({
    group: 'Linear algebra',
    names: Object.freeze([
      'eigs',
      'inv',
      'lup',
      'lusolve',
      'lsolve',
      'lsolveAll',
      'pinv',
      'qr',
      'schur',
      'slu',
      'usolve',
      'usolveAll',
    ]),
  }),
  Object.freeze({ group: 'Numeric ODE', names: Object.freeze(['solveODE']) }),
  Object.freeze({ group: 'Signal', names: Object.freeze(['fft', 'freqz', 'ifft', 'zpk2tf']) }),
  Object.freeze({
    group: 'Special and deterministic probability',
    names: Object.freeze([
      'bellNumbers',
      'bernoulli',
      'catalan',
      'combinations',
      'combinationsWithRep',
      'erf',
      'factorial',
      'gamma',
      'lgamma',
      'multinomial',
      'nthRoots',
      'permutations',
      'polynomialRoot',
      'stirlingS2',
      'zeta',
    ]),
  }),
  Object.freeze({
    group: 'Statistics',
    names: Object.freeze([
      'corr',
      'count',
      'cumsum',
      'mad',
      'max',
      'mean',
      'median',
      'min',
      'mode',
      'prod',
      'quantileSeq',
      'std',
      'sum',
      'variance',
    ]),
  }),
  Object.freeze({
    group: 'Trigonometry',
    names: Object.freeze([
      'acos',
      'acosh',
      'acot',
      'acoth',
      'acsc',
      'acsch',
      'asec',
      'asech',
      'asin',
      'asinh',
      'atan',
      'atan2',
      'atanh',
      'cos',
      'cosh',
      'cot',
      'coth',
      'csc',
      'csch',
      'sec',
      'sech',
      'sin',
      'sinh',
      'tan',
      'tanh',
    ]),
  }),
  Object.freeze({
    group: 'Numeric checks',
    names: Object.freeze([
      'compare',
      'deepEqual',
      'equal',
      'isFinite',
      'isInteger',
      'isNaN',
      'isNegative',
      'isNumeric',
      'isPositive',
      'isPrime',
      'isZero',
      'larger',
      'largerEq',
      'smaller',
      'smallerEq',
      'typeOf',
      'unequal',
    ]),
  }),
] as const)

export const CALCULATION_MATHJS_NAMES = Object.freeze(CALCULATION_MATHJS_REFERENCE.flatMap(({ names }) => names))

export type CalculationMathJsName = (typeof CALCULATION_MATHJS_NAMES)[number]

export const CALCULATION_BLOCKED_MATHJS_NAMES = Object.freeze([
  'all',
  'bignumber',
  'chain',
  'compile',
  'config',
  'create',
  'createUnit',
  'derivative',
  'evaluate',
  'fraction',
  'help',
  'import',
  'parse',
  'parser',
  'pickRandom',
  'random',
  'randomInt',
  'rationalize',
  'resolve',
  'simplify',
  'simplifyConstant',
  'simplifyCore',
  'symbolicEqual',
  'typed',
  'unit',
] as const)
