import type { Optimization, OptimizationTrial } from '@/contracts/api/optimization'

export const optimizationFixture: Optimization = {
  id: 'optimization-1',
  name: 'Design search',
  experiment_id: 7,
  state: 'paused',
  pause_reason: 'trial_failed',
  created_at: '2026-09-30T00:00:00Z',
  updated_at: '2026-09-30T00:00:00Z',
  finished_at: null,
  max_trials: 20,
  max_parallel: 2,
  trial_count: 2,
  retry_count: 0,
  succeeded: 1,
  failed: 1,
  cancelled: 0,
  active: 0,
  executions_active: 0,
  cleanup_pending: false,
  manual_retry_pending: false,
  best_trial: {
    id: 'trial-1',
    ordinal: 1,
    variables: { width: 3 },
    result: { objective: 5, feasible: true, violation: 0, constraints: [] },
    measurement_id: 41,
  },
  definition: {
    source_bundle: { files: { 'experiment.tsx': 'export default null' } },
    source_hash: 'hash-7',
    catalog_revision: 'catalog',
    vars_schema: { width: { shape: [], min: 0, max: 10 } },
    calculations: [
      { key: 'objective', calculation_id: 9, source: 'source', source_hash: 'calculation', source_revision: 1 },
    ],
    hash: 'definition',
  },
  settings: {
    initial_vars: { width: 2 },
    axes: [{ name: 'width', indices: [], min: 0, max: 10, fixed: false }],
    objective: { direction: 'minimize' },
    constraints: [],
    max_trials: 20,
    max_parallel: 2,
    initial_step: 0.25,
    min_step: 0.001,
  },
  optimizer_state: {},
}
export const trialFixture: OptimizationTrial = {
  id: 'trial-2',
  optimization_id: 'optimization-1',
  ordinal: 2,
  round_index: 1,
  variables: { width: 4 },
  fingerprint: 'vars',
  state: 'failed',
  next_stage: 'calculate',
  measurement_id: 42,
  result: null,
  error: { message: 'Calculation failed', stage: 'calculate' },
  manual_retry_requested: false,
  retry_count: 0,
  created_at: '2026-09-30T00:00:00Z',
  updated_at: '2026-09-30T00:00:00Z',
  stages: [
    {
      id: 'build',
      stage: 'build',
      generation: 1,
      batch_id: 'build-batch',
      job_id: 'build-job',
      state: 'succeeded',
      result: {},
      error: null,
      job: null,
    },
    {
      id: 'solve',
      stage: 'solve',
      generation: 1,
      batch_id: 'solve-batch',
      job_id: 'solve-job',
      state: 'succeeded',
      result: {},
      error: null,
      job: null,
    },
    {
      id: 'calculate',
      stage: 'calculate',
      generation: 1,
      batch_id: 'calculate-batch',
      job_id: 'calculate-job',
      state: 'failed',
      result: null,
      error: { message: 'Calculation failed' },
      job: null,
    },
  ],
}
