// Generated by scripts/generate-cad-api.mjs from elements/manifest.json. Do not edit.
import type {
  ArrayAttributes,
  BooleanAttributes,
  BoxAttributes,
  CurvedEdgeCylinderAttributes,
  CurvedSurfaceSphereAttributes,
  CylinderAttributes,
  FiberAttributes,
  RotateAttributes,
  ScaleAttributes,
  ShellAttributes,
  SphereAttributes,
  TranslateAttributes,
} from '@caemble/core'

declare global {
  function h(type: unknown, attributes: unknown, ...children: unknown[]): unknown
  function Fragment(props: { children?: unknown }): unknown

  namespace JSX {
    interface IntrinsicElements {
      /** @deprecated Import { Box } from '@caemble/core'. */
      box: BoxAttributes
      /** @deprecated Import { Cylinder } from '@caemble/core'. */
      cylinder: CylinderAttributes
      /** @deprecated Import { CurvedEdgeCylinder } from '@caemble/core'. */
      curvedEdgeCylinder: CurvedEdgeCylinderAttributes
      /** @deprecated Import { Sphere } from '@caemble/core'. */
      sphere: SphereAttributes
      /** @deprecated Import { CurvedSurfaceSphere } from '@caemble/core'. */
      curvedSurfaceSphere: CurvedSurfaceSphereAttributes
      /** @deprecated Import { Fiber } from '@caemble/core'. */
      fiber: FiberAttributes
      translate: TranslateAttributes
      rotate: RotateAttributes
      scale: ScaleAttributes
      shell: ShellAttributes
      array: ArrayAttributes
      union: BooleanAttributes
      subtract: BooleanAttributes
      intersect: BooleanAttributes
    }
  }
}

export {}
