// Generated by scripts/generate-cad-api.mjs from elements/manifest.json. Do not edit.
import type {
  ArrayAttributes,
  BooleanAttributes,
  RotateAttributes,
  ScaleAttributes,
  ShellAttributes,
  TranslateAttributes,
  Geometry,
  GeometryInvocationAttributes,
} from '@caemble/core'

declare global {
  function h(type: unknown, attributes: unknown, ...children: unknown[]): unknown
  function Fragment(props: { children?: unknown }): unknown

  namespace JSX {
    type LibraryManagedAttributes<Component, Props> = Props extends { readonly id: string }
      ? Component extends Geometry<infer CustomProps>
        ? GeometryInvocationAttributes<CustomProps>
        : Props
      : Props

    interface IntrinsicElements {
      translate: TranslateAttributes
      rotate: RotateAttributes
      scale: ScaleAttributes
      shell: ShellAttributes
      array: ArrayAttributes
      union: BooleanAttributes
      subtract: BooleanAttributes
      intersect: BooleanAttributes
    }
  }
}

export {}
