// Generated by scripts/generate-cad-api.mjs. Do not edit.
export const CAEMBLE_CORE_DECLARATION_VERSION = '0.0.0' as const
export const CAEMBLE_MONACO_VERSION = '0.56.0' as const
export const CAEMBLE_TYPESCRIPT_VERSION = '5.9.3' as const
export const QUANTITY_KIND_DATA_VERSION = '0.0.1' as const
export const CAD_API_DECLARATION_FINGERPRINT =
  'c26e6a6fc9d8be1b7a1883492fa4524633ac00c797ad5d308c1f55d19ac40929' as const
