// Generated by scripts/generate-cad-api.mjs. Do not edit.
export const CAEMBLE_CORE_DECLARATION_VERSION = '0.7.0' as const
export const CAEMBLE_MONACO_VERSION = '0.56.0' as const
export const CAEMBLE_TYPESCRIPT_VERSION = '5.9.3' as const
export const CAD_API_DECLARATION_FINGERPRINT =
  '155fca94dffb1a83699ec69f006aa6fd42c5e24c9ac43c9c8c3f24525aed0835' as const
