// Generated by scripts/generate-cad-api.mjs. Do not edit.
export const CAEMBLE_CORE_DECLARATION_VERSION = '0.2.0' as const
export const CAEMBLE_MONACO_VERSION = '0.56.0' as const
export const CAEMBLE_TYPESCRIPT_VERSION = '5.9.3' as const
export const CAD_API_DECLARATION_FINGERPRINT =
  'b1859b08c184bbdc4001f9552d1dbc59636aac41b29c695a9771692dd6ff4731' as const
