// Generated by scripts/generate-cad-api.mjs from manifest.json. Do not edit.
import { boxManifest } from './primitives/box/definition'
import { cylinderManifest } from './primitives/cylinder/definition'
import { curvedEdgeCylinderManifest } from './primitives/curvedEdgeCylinder/definition'
import { sphereManifest } from './primitives/sphere/definition'
import { fiberManifest } from './primitives/fiber/definition'
import { translateManifest, rotateManifest, scaleManifest } from './operations/transforms/definition'
import { arrayManifest } from './operations/array/definition'
import { unionManifest, subtractManifest, intersectManifest } from './operations/booleans/definition'
import { asphericCylinderManifest } from './primitives/asphericCylinder/definition'
import { ellipsoidManifest } from './primitives/ellipsoid/definition'
import { hyperboloidManifest } from './primitives/hyperboloid/definition'
import { paraboloidManifest } from './primitives/paraboloid/definition'
import { boxDefinition } from './primitives/box/runtime'
import { cylinderDefinition } from './primitives/cylinder/runtime'
import { curvedEdgeCylinderDefinition } from './primitives/curvedEdgeCylinder/runtime'
import { sphereDefinition } from './primitives/sphere/runtime'
import { fiberDefinition } from './primitives/fiber/runtime'
import { translateDefinition, rotateDefinition, scaleDefinition } from './operations/transforms/runtime'
import { arrayDefinition } from './operations/array/runtime'
import { unionDefinition, subtractDefinition, intersectDefinition } from './operations/booleans/runtime'
import { asphericCylinderDefinition } from './primitives/asphericCylinder/runtime'
import { ellipsoidDefinition } from './primitives/ellipsoid/runtime'
import { hyperboloidDefinition } from './primitives/hyperboloid/runtime'
import { paraboloidDefinition } from './primitives/paraboloid/runtime'
import { cadAuthoringContract } from './authoringContract'
import type { CadElementDefinition } from '../evaluation/types'

export { cadAuthoringContract }

export const cadPrimitiveAuthoringBindings = Object.freeze({
  Box: 'box',
  Cylinder: 'cylinder',
  CurvedEdgeCylinder: 'curvedEdgeCylinder',
  Sphere: 'sphere',
  Fiber: 'fiber',
  AsphericCylinder: 'asphericCylinder',
  Ellipsoid: 'ellipsoid',
  Hyperboloid: 'hyperboloid',
  Paraboloid: 'paraboloid',
} as const)

export const cadElementCatalog = [
  boxManifest,
  cylinderManifest,
  curvedEdgeCylinderManifest,
  sphereManifest,
  fiberManifest,
  translateManifest,
  rotateManifest,
  scaleManifest,
  arrayManifest,
  unionManifest,
  subtractManifest,
  intersectManifest,
  asphericCylinderManifest,
  ellipsoidManifest,
  hyperboloidManifest,
  paraboloidManifest,
] as const

export const cadElementDefinitions = [
  boxDefinition,
  cylinderDefinition,
  curvedEdgeCylinderDefinition,
  sphereDefinition,
  fiberDefinition,
  translateDefinition,
  rotateDefinition,
  scaleDefinition,
  arrayDefinition,
  unionDefinition,
  subtractDefinition,
  intersectDefinition,
  asphericCylinderDefinition,
  ellipsoidDefinition,
  hyperboloidDefinition,
  paraboloidDefinition,
] as const satisfies readonly CadElementDefinition[]
