"""Explicit verification cost ownership; imports no test modules.

Low-cost checks exercise contracts, small numerical functions and synthetic children.
Product entry points and complete physical paths require an explicit smoke, example
or validation request, even when their own test source changed.
"""
from __future__ import annotations

MODULE_TIERS = {
    "tests/test_fdtd_parallel_smoke.py": "smoke",
    "tests/test_ray_batches.py": "lowcost",
    "tests/test_ray_parallel_smoke.py": "smoke",
    "tests/test_cpu_executor.py": "lowcost",
    "tests/test_ray_analytic.py": "lowcost",
    "tests/test_ray_analytic_smoke.py": "smoke",
    "tests/test_continuous_geometry.py": "lowcost",
    "tests/test_ray_thin_film.py": "lowcost",
    "tests/test_acoustic_fdtd.py": "lowcost",
    "tests/test_acoustic_fdtd_accuracy.py": "validation",
    "tests/test_acoustic_geometry_variants.py": "smoke",
    "tests/test_acoustic_recording.py": "smoke",
    "tests/test_acoustic_transient_lifecycle.py": "smoke",
    "tests/test_actual_solver_chain.py": "smoke",
    "tests/test_architecture_boundaries.py": "lowcost",
    "tests/test_architecture_imports.py": "lowcost",
    "tests/test_box_grid_outputs.py": "lowcost",
    "tests/test_catalog_examples.py": "example",
    "tests/test_complex_tensor_transport.py": "lowcost",
    "tests/test_composable_methods.py": "lowcost",
    "tests/test_coordinator_solver_chain.py": "smoke",
    "tests/test_coordinator_values.py": "lowcost",
    "tests/test_coupling_projection.py": "lowcost",
    "tests/test_dem_contracts.py": "lowcost",
    "tests/test_dem_contracts_smoke.py": "smoke",
    "tests/test_dem_particles.py": "lowcost",
    "tests/test_displacement_recording.py": "lowcost",
    "tests/test_domain_recording.py": "lowcost",
    "tests/test_electrothermal_feedback.py": "lowcost",
    "tests/test_electrothermal_interface_child.py": "smoke",
    "tests/test_electrothermal_runtime.py": "smoke",
    "tests/test_executor_shutdown.py": "lowcost",
    "tests/test_fdtd_cuda.py": "validation",
    "tests/test_fdtd_detector_sampling.py": "lowcost",
    "tests/test_fdtd_device.py": "lowcost",
    "tests/test_fdtd_domain.py": "lowcost",
    "tests/test_fdtd_field_recording.py": "lowcost",
    "tests/test_fdtd_physics.py": "lowcost",
    "tests/test_fdtd_propagation.py": "lowcost",
    "tests/test_fdtd_solver.py": "smoke",
    "tests/test_fdtd_tfsf.py": "lowcost",
    "tests/test_field_history.py": "lowcost",
    "tests/test_geometry_solids.py": "lowcost",
    "tests/test_geometry_volume_mesh.py": "lowcost",
    "tests/test_gold_fcc_example.py": "example",
    "tests/test_harmonic_mesh_recording.py": "lowcost",
    "tests/test_harmonic_surface_methods.py": "lowcost",
    "tests/test_hyperelastic.py": "lowcost",
    "tests/test_hyperelastic_smoke.py": "smoke",
    "tests/test_hyperelastic_validation.py": "validation",
    "tests/test_incompressible_domain.py": "lowcost",
    "tests/test_incompressible_evolution.py": "lowcost",
    "tests/test_incompressible_handoff.py": "smoke",
    "tests/test_incompressible_load_physics.py": "lowcost",
    "tests/test_incompressible_methods.py": "lowcost",
    "tests/test_incompressible_outputs.py": "lowcost",
    "tests/test_incompressible_periodic.py": "lowcost",
    "tests/test_incompressible_physics.py": "lowcost",
    "tests/test_incompressible_runtime.py": "smoke",
    "tests/test_incompressible_surfaces.py": "lowcost",
    "tests/test_incompressible_transient_physics.py": "lowcost",
    "tests/test_local_transport.py": "lowcost",
    "tests/test_material_interactions.py": "lowcost",
    "tests/test_material_models.py": "lowcost",
    "tests/test_microheater.py": "validation",
    "tests/test_microheater_contracts.py": "lowcost",
    "tests/test_microheater_validation.py": "validation",
    "tests/test_mixed_benchmarks.py": "validation",
    "tests/test_mixed_hyperelastic.py": "lowcost",
    "tests/test_mixed_hyperelastic_smoke.py": "smoke",
    "tests/test_mmap_executor.py": "lowcost",
    "tests/test_object_storage.py": "lowcost",
    "tests/test_particle_continuation.py": "smoke",
    "tests/test_particle_faults.py": "smoke",
    "tests/test_particle_field_handoff.py": "lowcost",
    "tests/test_particle_final_review.py": "lowcost",
    "tests/test_particle_methods.py": "lowcost",
    "tests/test_particle_mpm.py": "lowcost",
    "tests/test_particle_observation_independence.py": "smoke",
    "tests/test_particle_quantities.py": "lowcost",
    "tests/test_particle_runtime.py": "smoke",
    "tests/test_particle_solvers.py": "smoke",
    "tests/test_particle_sph.py": "lowcost",
    "tests/test_particle_sph_validation.py": "validation",
    "tests/test_preflight_execution.py": "lowcost",
    "tests/test_pressure_acoustics.py": "lowcost",
    "tests/test_program_state_contract.py": "lowcost",
    "tests/test_ray_grating.py": "lowcost",
    "tests/test_ray_detector.py": "lowcost",
    "tests/test_ray_detector_smoke.py": "smoke",
    "tests/test_ray_pixel_example.py": "smoke",
    "tests/test_ray_pixel_calculations.py": "lowcost",
    "tests/test_regression_runner.py": "lowcost",
    "tests/test_resource_types_cache.py": "lowcost",
    "tests/test_result_contracts.py": "lowcost",
    "tests/test_result_metadata.py": "lowcost",
    "tests/test_rigid_contact.py": "lowcost",
    "tests/test_rigid_methods.py": "lowcost",
    "tests/test_rigid_outputs.py": "lowcost",
    "tests/test_rigid_runtime.py": "smoke",
    "tests/test_rigid_solver.py": "smoke",
    "tests/test_runner_integration.py": "smoke",
    "tests/test_runtime_resources.py": "lowcost",
    "tests/test_scalar_fem.py": "lowcost",
    "tests/test_server_recording.py": "lowcost",
    "tests/test_simulation_coordinator.py": "lowcost",
    "tests/test_solver_entries.py": "smoke",
    "tests/test_solver_methods.py": "lowcost",
    "tests/test_solver_observer.py": "lowcost",
    "tests/test_spawn_executor.py": "lowcost",
    "tests/test_spectrometer_example.py": "validation",
    "tests/test_sph_outputs.py": "lowcost",
    "tests/test_state_lifecycle.py": "lowcost",
    "tests/test_structural_analysis.py": "lowcost",
    "tests/test_structural_clock.py": "lowcost",
    "tests/test_structural_clock_smoke.py": "smoke",
    "tests/test_structural_continuum.py": "lowcost",
    "tests/test_structural_corotation.py": "lowcost",
    "tests/test_structural_coupling.py": "lowcost",
    "tests/test_structural_csg.py": "lowcost",
    "tests/test_structural_csg_smoke.py": "smoke",
    "tests/test_structural_damping_definition.py": "lowcost",
    "tests/test_structural_eccentric_mass.py": "lowcost",
    "tests/test_structural_gravity.py": "lowcost",
    "tests/test_structural_harmonic.py": "lowcost",
    "tests/test_structural_harmonic_orientation.py": "lowcost",
    "tests/test_structural_harmonic_smoke.py": "smoke",
    "tests/test_structural_history.py": "lowcost",
    "tests/test_structural_identity.py": "lowcost",
    "tests/test_structural_joints.py": "lowcost",
    "tests/test_structural_load_transfer.py": "lowcost",
    "tests/test_structural_material_orientation.py": "lowcost",
    "tests/test_structural_newmark_guess.py": "lowcost",
    "tests/test_structural_reactions.py": "lowcost",
    "tests/test_structural_rotation_dynamics.py": "lowcost",
    "tests/test_structural_sets.py": "lowcost",
    "tests/test_structural_shell_dynamics.py": "lowcost",
    "tests/test_structural_shells.py": "lowcost",
    "tests/test_structural_solid_bending.py": "lowcost",
    "tests/test_structural_thermal.py": "lowcost",
    "tests/test_structural_volume_numerics.py": "lowcost",
    "tests/test_structured_topology.py": "lowcost",
    "tests/test_transient_coupling_methods.py": "lowcost",
    "tests/test_transient_surface_motion.py": "smoke",
    "tests/test_value_boundaries.py": "lowcost",
    "tests/test_value_coupling.py": "lowcost"
}

FUNCTION_TIERS = {
    "tests/test_acoustic_fdtd.py::test_first_resistive_reflection_has_correct_delay_sign_and_point_eight_ratio": "validation",
    "tests/test_acoustic_fdtd.py::test_prescribed_flux_energy_work_and_passive_decay_after_source_ends": "validation",
    "tests/test_acoustic_fdtd.py::test_three_dimensional_energy_balance_including_impedance_edges_and_corners": "validation",
    "tests/test_acoustic_fdtd.py::test_time_refinement_is_second_order_against_the_same_spatial_model": "validation",
    "tests/test_acoustic_fdtd.py::test_window_partition_and_checkpoint_retry_are_identical": "smoke",
    "tests/test_catalog_examples.py::test_boolean_vars_rebuild_mesh_and_preserve_semantic_boundaries": "smoke",
    "tests/test_catalog_examples.py::test_harmonic_surface_crosses_children_and_failed_frequency_call_rolls_back": "smoke",
    "tests/test_catalog_examples.py::test_structural_child_cancellation_preserves_checkpoint_and_releases_buffers": "smoke",
    "tests/test_catalog_examples.py::test_structural_child_rejects_foreign_motion_without_committing_trial": "smoke",
    "tests/test_catalog_examples.py::test_visualization_only_official_task_needs_no_outputs": "smoke",
    "tests/test_dem_particles.py::test_contact_damping_dissipates_energy_and_refines": "validation",
    "tests/test_dem_particles.py::test_different_mass_collision_matches_elastic_solution": "validation",
    "tests/test_dem_particles.py::test_gravity_floor_rebound_and_triangle_seam_contact": "validation",
    "tests/test_dem_particles.py::test_incline_above_static_limit_slips": "validation",
    "tests/test_dem_particles.py::test_incline_stick_means_rolling_not_a_stationary_sphere": "validation",
    "tests/test_electrothermal_feedback.py::test_consistent_capacity_robin_rc_heating_cooling_and_first_order_time_convergence": "validation",
    "tests/test_fdtd_propagation.py::test_cpml_reduces_returned_pulse_energy_by_three_orders_of_magnitude": "validation",
    "tests/test_fdtd_tfsf.py::test_broadband_auxiliary_line_reverse_wave_at_grid_transitions": "validation",
    "tests/test_fdtd_tfsf.py::test_tfsf_matches_auxiliary_plane_wave_and_cancels_all_exterior_faces": "validation",
    "tests/test_incompressible_evolution.py::test_partial_window_steps_retain_first_order_temporal_convergence": "validation",
    "tests/test_incompressible_load_physics.py::test_boolean_closed_obstacle_buoyancy_gauge_cancellation_and_surface_refinement": "validation",
    "tests/test_incompressible_load_physics.py::test_channel_wall_force_moment_and_traction_converge_independently": "validation",
    "tests/test_incompressible_load_physics.py::test_startup_global_momentum_budget_separates_residual_and_surface_error": "validation",
    "tests/test_incompressible_periodic.py::test_actual_csg_nonmatching_periodic_startup_matches_channel_series": "smoke",
    "tests/test_incompressible_periodic.py::test_periodic_channel_stokes_converges_without_pressure_jump": "validation",
    "tests/test_incompressible_physics.py::test_irregular_pressure_duct_converges_to_square_duct_reference": "validation",
    "tests/test_incompressible_physics.py::test_real_csg_catalog_duct_converges_with_full_nonorthogonal_flux": "validation",
    "tests/test_incompressible_transient_physics.py::test_actual_csg_startup_stays_bounded_and_matches_independent_series": "validation",
    "tests/test_incompressible_transient_physics.py::test_startup_duct_spatial_refinement_approaches_independent_series": "validation",
    "tests/test_incompressible_transient_physics.py::test_startup_duct_time_convergence_and_independent_series": "validation",
    "tests/test_incompressible_transient_physics.py::test_traveling_shear_advects_phase_and_converges_in_time": "validation",
    "tests/test_incompressible_transient_physics.py::test_traveling_shear_spatial_refinement_recovers_phase_and_decay": "validation",
    "tests/test_microheater.py::test_microheater_cancellation_during_real_child_mesh": "smoke",
    "tests/test_microheater.py::test_microheater_cancellation_during_structural_child": "smoke",
    "tests/test_particle_mpm.py::test_elastic_compression_converges_with_timestep_refinement": "validation",
    "tests/test_particle_mpm.py::test_fixed_base_gravity_displacement_converges_with_grid_refinement": "validation",
    "tests/test_pressure_acoustics.py::test_three_frequency_levels_converge_between_samples": "validation",
    "tests/test_pressure_acoustics.py::test_three_mesh_levels_resolve_complex_pressure_and_positive_power": "validation",
    "tests/test_rigid_methods.py::test_asymmetric_rotation_and_dense_output_converge_at_second_order": "validation",
    "tests/test_structural_analysis.py::test_cantilever_beam_mesh_convergence_and_reaction_balance": "validation",
    "tests/test_structural_analysis.py::test_free_asymmetric_rotor_euler_acceleration_and_conservation_refine_with_dt": "validation",
    "tests/test_structural_analysis.py::test_stiffness_damping_matches_underdamped_oscillator": "validation",
    "tests/test_structural_csg.py::test_csg_mesh_refinement_converges_clamped_volume_compliance": "validation",
    "tests/test_structural_eccentric_mass.py::test_eccentric_elastic_motion_under_gravity_converges_in_energy_and_momentum": "validation",
    "tests/test_structural_joints.py::test_free_tilting_base_and_spinning_rotor_conserve_energy_and_angular_momentum": "validation",
    "tests/test_structural_rotation_dynamics.py::test_loaded_multiaxis_beam_time_refinement_and_energy_work_balance": "validation",
    "tests/test_structural_shell_dynamics.py::test_loaded_three_axis_rotating_shell_refines_work_and_angular_impulse_balance": "validation",
    "tests/test_structural_solid_bending.py::test_solid_pure_moment_cantilever_converges_to_exact_three_dimensional_elasticity": "validation",
    "tests/test_structural_thermal.py::test_bimaterial_strip_bending_converges_to_independent_laminate_section": "validation"
}


def test_tier(nodeid: str) -> str:
    """Resolve an item without importing its module or guessing from its name."""
    path, *parts = nodeid.replace("\\", "/").split("::")
    if path not in MODULE_TIERS:
        raise ValueError(f"Missing test cost ownership: {path}")
    function = parts[-1].split("[", 1)[0] if parts else ""
    return FUNCTION_TIERS.get(f"{path}::{function}", MODULE_TIERS[path])


def module_candidates(allowed_tiers: set[str] | frozenset[str]) -> tuple[str, ...]:
    """Exclude whole disallowed modules before pytest imports and collects them."""
    modules = {path for path, tier in MODULE_TIERS.items() if tier in allowed_tiers}
    modules.update(key.split("::", 1)[0] for key, tier in FUNCTION_TIERS.items() if tier in allowed_tiers)
    return tuple(sorted(modules))
